---
- name: install auditd service
  apt: name={{item}} state=latest update_cache=true
  with_items:
  - auditd
  when: ansible_os_family == 'Debian' and ansible_lsb.major_release == '18'

- name: start auditd service
  shell: systemctl kill auditd && sleep 1 && systemctl start auditd
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7') or (ansible_os_family == 'Debian' and ansible_lsb.major_release == '18')
  
- name: enable auditd service
  shell: systemctl enable auditd
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7') or (ansible_os_family == 'Debian' and ansible_lsb.major_release == '18')

