---
- name: config /etc/pam.d/system-auth for password arguments
  lineinfile: 
    path: /etc/pam.d/system-auth
    regexp: '^password    requisite     pam_pwquality.so'
    insertafter: 'EOF'
    line: password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type= minlen=8 lcredit=-1 ucredit=-1 dcredit=-1 ocredit=-1 difok=5 enforce_for_root
    state: present
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: install required package of libpam-cracklib for ubuntu
  apt: name={{item}} state=latest update_cache=true
  with_items:
  - libpam-cracklib
  when: ansible_os_family == 'Debian' and ansible_lsb.major_release == '18'

- name: config /etc/pam.d/common-password for password arguments 
  lineinfile: 
    path: /etc/pam.d/common-password
    regexp: '^password        requisite                       pam_cracklib.so'
    insertafter: 'EOF'
    line: password        requisite                       pam_cracklib.so retry=3 minlen=8 difok=5 minlen=8 lcredit=-1 ucredit=-1 dcredit=-1 ocredit=-1 enforce_for_root
    state: present
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian' and ansible_lsb.major_release == '18'

- name: config /etc/login.defs for password arguments PASS_MAX_DAYS
  lineinfile: 
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    insertafter: 'EOF'
    line: PASS_MAX_DAYS 180
    state: present
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7') or (ansible_os_family == 'Debian' and ansible_lsb.major_release == '18')

- name: config /etc/login.defs for password arguments PASS_MIN_DAYS
  lineinfile: 
    path: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    insertafter: 'EOF'
    line: PASS_MIN_DAYS 0
    state: present
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7') or (ansible_os_family == 'Debian' and ansible_lsb.major_release == '18')

- name: config /etc/login.defs for password arguments PASS_MIN_LEN, #密码最小长度，pam设置优先
  lineinfile: 
    path: /etc/login.defs
    regexp: '^PASS_MIN_LEN'
    insertafter: 'EOF'
    line: PASS_MIN_LEN  8
    state: present
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7') or (ansible_os_family == 'Debian' and ansible_lsb.major_release == '18')

- name: config /etc/login.defs for password arguments PASS_WARN_AGE
  lineinfile: 
    path: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    insertafter: 'EOF'
    line: PASS_WARN_AGE 15
    state: present
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7') or (ansible_os_family == 'Debian' and ansible_lsb.major_release == '18')
