---
- name: install yum repo centos7 for centos
  copy: src=yum/centos-7.repo dest=/etc/yum.repos.d/ backup=yes mode=644
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: install yum repo epel for centos
  copy: src=yum/epel-7.repo dest=/etc/yum.repos.d/ backup=yes mode=644
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: install apt repo for ubuntu18
  copy: src=apt/sources-18.list dest=/etc/apt/sources.list backup=yes mode=644
  when: ansible_os_family == 'Debian' and ansible_lsb.major_release == '18'
