{
 "title": "Kubernetes Pods",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers",
 "tags": [
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_labels,namespace)"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "All Pods Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Milli Core ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{kubernetes_io_hostname=\"$Node\"} * 1000"
    }
   ]
  },
  {
   "title": "All Pod CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=\"$Node\",namespace=\"$namespace\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "All Pod Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=\"$Node\",namespace=\"$namespace\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "All Pod Network Received Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{kubernetes_io_hostname=\"$Node\",namespace=\"$namespace\"}[5m])) ",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "All Pod Network Sent Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{kubernetes_io_hostname=\"$Node\",namespace=\"$namespace\"}[5m])) ",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Single Pod Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pods CPU Usage (cores/m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",namespace=\"$namespace\"}[5m])) by (pod) * 1000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=\"$Node\",namespace=\"$namespace\"}) by (pod) ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{kubernetes_io_hostname=\"$Node\",namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "Received: {{pod}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{kubernetes_io_hostname=\"$Node\",namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "Sent: {{pod}}"
    }
   ]
  },
  { "title": "Single Container Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Containers CPU Usage(cores/m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",kubernetes_io_hostname=\"$Node\",namespace=\"$namespace\"}[5m])) by (pod,container)  * 1000",
     "legendFormat": "pod: {{ pod}} | containers: {{ container}}"
    }
   ]
  },
  {
   "title": "Containers Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=\"$Node\",namespace=\"$namespace\"}) by (pod,container) ",
     "legendFormat": "Pod: {{ pod }} | Containers: {{ container}}"
    }
   ]
  }
 ]
}