{
 "title": "Kubernetes Cluster",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter, nginx ingress controller",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(up{job=~\"kubernetes-node\"},job)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(up{job=\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(http_request_duration_seconds_count{status=\"200\", method=\"GET\"}[10m]))"
    }
   ]
  },
  {
   "title": "Idle CPU (avg)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[5m])) "
    }
   ]
  },
  {
   "title": "max Usage Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(((node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemAvailable_bytes{job=\"$job\"})/node_memory_MemTotal_bytes{job=\"$job\"}))"
    }
   ]
  },
  {
   "title": "Max Usage Storage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max((node_filesystem_size_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"} - node_filesystem_avail_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"}) / node_filesystem_size_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"})"
    }
   ]
  },
  {
   "title": "Restart Pods number(1h)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[1h]) > 0) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"kubernetes-kube-state-metric\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"$job\"} + node_memory_Buffers_bytes{job=\"$job\"} + node_memory_Cached_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"} /node_filesystem_size_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"}",
     "legendFormat": "{{instance}} | {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IO/ps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{job=\"$job\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Top 5 Pods for Usage Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,container_memory_usage_bytes{instance=\"$node\",image!=\"\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5  Containers for Usage CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,irate(container_cpu_usage_seconds_total{instance=\"$node\",image!=\"\",name=~\"^k8s_.*\",container!=\"POD\"}[5m]))",
     "legendFormat": "{{container}} in {{pod}}"
    }
   ]
  }
 ]
}