{
 "title": "Dell",
 "description": "A Dashboard for DELL iDRAC based on SNMP_EXPORTER and Prometheus",
 "tags": [
  "snmp",
  "idrac",
  "prometheus"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=~\"consul-snmp_idrac_exporter.*\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(systemServiceTag{instance=\"$instance\"}) by(systemServiceTag,ip)"
    },
    {
     "expr": "count(systemExpressServiceCode{instance=\"$instance\"}) by(systemExpressServiceCode)"
    },
    {
     "expr": "count(systemFQDN{instance=\"$instance\"}) by(name)"
    }
   ]
  },
  { "title": "General Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Number of logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "numEventLogEntries{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "intrusionStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " intrusionStatus{instance=\"$instance\"} / ignoring(intrusionLocationName) group_right intrusionLocationName{instance=\"$instance\"}",
     "legendFormat": "{{intrusionLocationName}}"
    }
   ]
  },
  {
   "title": "storageStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "globalStorageStatus{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "physicalDiskStatus",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "physicalDiskComponentStatus{instance=\"$instance\"}\n/ ignoring(physicalDiskName) group_right\nphysicalDiskName{instance=\"$instance\"}",
     "legendFormat": "{{physicalDiskName}}"
    }
   ]
  },
  {
   "title": "systemPowerState",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemPowerState{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "systemLCDStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "systemLCDStatus{instance=\"$instance\"}",
     "legendFormat": "{{systemBIOSVersionName}}"
    }
   ]
  },
  {
   "title": "systemStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "globalSystemStatus{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "virtualDiskStatus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "virtualDiskComponentStatus{instance=\"$instance\"}",
     "legendFormat": "{{virtualDiskNumber}}"
    }
   ]
  },
  {
   "title": "systemBIOSStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "systemBIOSStatus{instance=\"$instance\"}\n/ ignoring(systemBIOSVersionName) group_right\nsystemBIOSVersionName{instance=\"$instance\"}",
     "legendFormat": "{{systemBIOSVersionName}}"
    }
   ]
  },
  { "title": "Detailed Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cooling Device Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coolingDeviceStatus{instance=\"$instance\"}\n/ ignoring(coolingDeviceLocationName) group_right\ncoolingDeviceLocationName{instance=\"$instance\"}",
     "legendFormat": "{{coolingDeviceLocationName}}"
    }
   ]
  },
  {
   "title": "PCI Device Status",
   "type": "stat",
   "gridPos": { "h": 16, "w": 9, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pCIDeviceStatus{instance=\"$instance\"}\n/ ignoring(pCIDeviceDescriptionName) group_right\npCIDeviceDescriptionName{instance=\"$instance\"}",
     "legendFormat": "{{pCIDeviceDescriptionName}}"
    }
   ]
  },
  {
   "title": "firmwareStatus",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "firmwareStatus{instance=\"$instance\"}\n/ ignoring(firmwareTypeName) group_right\nfirmwareTypeName{instance=\"$instance\"}",
     "legendFormat": "{{firmwareTypeName}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "temperatureProbeReading{instance=\"$instance\"}/10\n/ ignoring(temperatureProbeLocationName) group_right\ntemperatureProbeLocationName{instance=\"$instance\"}",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  {
   "title": "Power supply Watt",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "powerSupplyLocationName{instance=\"$instance\"}"
    },
    {
     "expr": "powerSupplyOutputWatts{instance=\"$instance\"}/ 10"
    }
   ]
  },
  {
   "title": "Firmware Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "firmwareTypeName{instance=\"$instance\"}"
    },
    {
     "expr": "firmwareVersionName{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "memoryDeviceStatus{instance=\"$instance\"}\n/ ignoring(memoryDeviceLocationName) group_right\nmemoryDeviceLocationName{instance=\"$instance\"}",
     "legendFormat": "{{memoryDeviceLocationName}}"
    }
   ]
  },
  {
   "title": "Memory Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "memoryDeviceIndex{instance=\"$instance\"}"
    },
    {
     "expr": "memoryDeviceStateSettings{instance=\"$instance\"}"
    },
    {
     "expr": "memoryDeviceStatus{instance=\"$instance\"}"
    },
    {
     "expr": "memoryDeviceType_info{instance=\"$instance\"}"
    },
    {
     "expr": "memoryDeviceLocationName{instance=\"$instance\"}"
    },
    {
     "expr": "memoryDeviceSize{instance=\"$instance\"}  /1024 /1024"
    },
    {
     "expr": "memoryDeviceSpeed{instance=\"$instance\"}"
    },
    {
     "expr": "memoryDeviceManufacturerName{instance=\"$instance\"}"
    },
    {
     "expr": "memoryDevicePartNumberName{instance=\"$instance\"}"
    },
    {
     "expr": "memoryDeviceSerialNumberName{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Controller Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controllerRollUpStatus{instance=\"$instance\"}"
    },
    {
     "expr": "controllerComponentStatus{instance=\"$instance\"}"
    },
    {
     "expr": "controllerCacheSizeInMB{instance=\"$instance\"}"
    },
    {
     "expr": "controllerSecurityStatus{instance=\"$instance\"}"
    },
    {
     "expr": "controllerLoadBalanceSetting{instance=\"$instance\"}"
    },
    {
     "expr": "controllerMaxCapSpeed{instance=\"$instance\"}"
    },
    {
     "expr": "controllerDisplayName{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Controller Security",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controllerSecurityStatus{instance=\"$instance\"}"
    },
    {
     "expr": "controllerEncryptionKeyPresent{instance=\"$instance\"}"
    },
    {
     "expr": "controllerEncryptionCapability{instance=\"$instance\"}"
    },
    {
     "expr": "controllerDisplayName{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Controller rates",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controllerRebuildRate{instance=\"$instance\"}"
    },
    {
     "expr": "controllerReconstructRate{instance=\"$instance\"}"
    },
    {
     "expr": "controllerPatrolReadRate{instance=\"$instance\"}"
    },
    {
     "expr": "controllerBGIRate{instance=\"$instance\"}"
    },
    {
     "expr": "controllerCheckConsistencyRate{instance=\"$instance\"}"
    },
    {
     "expr": "controllerDisplayName{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Controller versions",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controllerName{instance=\"$instance\"}"
    },
    {
     "expr": "controllerFWVersion{instance=\"$instance\"}"
    },
    {
     "expr": "controllerDisplayName{instance=\"$instance\"}"
    },
    {
     "expr": "controllerDriverVersion{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "VirtualDiskRAIDLevel",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "virtualDiskLayout{instance=\"$instance\"}"
    },
    {
     "expr": "virtualDiskComponentStatus{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "physicalDiskName{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskManufacturer{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskSerialNo{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskProductID{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskRevision{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskBusType{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskPartNumber{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskMediaType{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskFormFactor{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskNegotiatedSpeed{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskCapableSpeed{instance=\"$instance\"}"
    },
    {
     "expr": "ceil(physicalDiskCapacityInMB{instance=\"$instance\"} * 1024 * 1024 /1000 /1000 /1000)"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "physicalDiskName{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskSpareState{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskComponentStatus{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskSmartAlertIndication{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskPowerState{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskOperationalState{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskProgress{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskSecurityStatus{instance=\"$instance\"}"
    },
    {
     "expr": "physicalDiskState{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Network Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "networkDeviceIndex{instance=\"$instance\"}"
    },
    {
     "expr": "networkDeviceStatus{instance=\"$instance\"}"
    },
    {
     "expr": "networkDeviceConnectionStatus{instance=\"$instance\"}"
    },
    {
     "expr": "networkDeviceCurrentMACAddress{instance=\"$instance\"}"
    },
    {
     "expr": "networkDevicePermanentMACAddress{instance=\"$instance\"}"
    },
    {
     "expr": "networkDeviceFQDD{instance=\"$instance\"}"
    },
    {
     "expr": "networkDeviceProductName{instance=\"$instance\"}"
    },
    {
     "expr": "networkDeviceVendorName{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "FRU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "FRU Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fruInformationStatus{instance=\"$instance\"}"
    },
    {
     "expr": "fruManufacturerName{instance=\"$instance\"}"
    },
    {
     "expr": "fruSerialNumberName{instance=\"$instance\"}"
    },
    {
     "expr": "fruPartNumberName{instance=\"$instance\"}"
    },
    {
     "expr": "fruRevisionName{instance=\"$instance\"}"
    },
    {
     "expr": "fruFQDD{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "PCI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "PCI Information",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pCIDeviceIndex{instance=\"$instance\"}"
    },
    {
     "expr": "pCIDeviceStateSettings{instance=\"$instance\"}"
    },
    {
     "expr": "pCIDeviceStatus{instance=\"$instance\"}"
    },
    {
     "expr": "pCIDeviceManufacturerName{instance=\"$instance\"}"
    },
    {
     "expr": "pCIDeviceDescriptionName{instance=\"$instance\"}"
    },
    {
     "expr": "pCIDeviceFQDD{instance=\"$instance\"}"
    }
   ]
  }
 ]
}