{
 "title": "IPMI",
 "description": "Charts from ipmitool in node exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "HOST:",
    "query": "label_values(ipmi_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "电源状态",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_chassis_power_state{instance='$node'}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "温度传感器状态",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_state {instance='$node'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "电压传感器状态",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_voltage_state{instance='$node'}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "功率传感器状态",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_power_state{instance='$node'}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "电流传感器状态",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_current_state{instance='$node'}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "30天使用功率",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{instance='$node',name=\"Pwr Consumption\"} * 30 * 24 "
    }
   ]
  },
  {
   "title": "温度",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance='$node'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "电源电压",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_voltage_volts{instance='$node'}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "电源功率",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{instance='$node'}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "电源电流",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_current_amperes{instance='$node'} ",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "风扇转速/m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{instance='$node'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "风扇传感器状态",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_state{instance='$node'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IPMI收集器状态",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ipmi_up{instance='$node'}", "legendFormat": "{{collector}}" }
   ]
  },
  {
   "title": "IPMI 传感器报告的状态的严重性",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor_state{instance=\"192.168.0.203\"} < 3",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}