---
- name: node selinux config disable
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled
    state: present
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'RedHat'
