<VERSION>4.1.1</VERSION>
<SQLQUERY>
<REMARK>
[标题]

[应用背景]

[结果列描述]
    配货频率：是在查询时间段内有出货的商品的记录数在每天的平均值。如3天出了10次货，那么
每天出货频率是3.33
    应徐经理的要求，把缺货的记录数也当作出库数，以反应真实的市场需要。
[必要的查询条件]
         不包含整箱指的是不包含配货规格大于1的商品
[实现方法]
drop table H4RTMP_ALCANALYZE cascade constraints;
prompt
prompt Creating table H4RTMP_ALCANALYZE
prompt ===============================
prompt
create global temporary table H4RTMP_ALCANALYZE
(
  GDGID       INTEGER,
  SORT        VARCHAR2(24),
  CLS         VARCHAR2(24),
  FRAQUENCY   NUMBER(24,4),
  FLAG        VARCHAR2(4),
  ALCQTY      NUMBER(24,2),
  INVQTY      NUMBER(24,2),
  STARDATE    DATE,
  ENDDATE     DATE,
  QPC         NUMBER(24,2),
  QPCSTR      VARCHAR2(10),
  SLOT        VARCHAR2(10),
  REGIONCODE  VARCHAR2(10),
  SLOTGROUP   VARCHAR2(10),
  LACKQTY     NUMBER(24,4),
  FITRATE     NUMBER(24,4),
  COUNTS      INTEGER,
  LINE        INTEGER,
  ANALYZEFLAG VARCHAR2(24),
  ORDQTY      NUMBER(24,4),
  ALCAMT      NUMBER(24,2),
  LACKAMT     NUMBER(24,2)
)
on commit preserve rows;
create index IDX_H4RTMP_ALCANALYZE on H4RTMP_ALCANALYZE (GDGID, FRAQUENCY, LINE);
exec hdcreatesynonym('H4RTMP_ALCANALYZE');
exec granttoqryrole('H4RTMP_ALCANALYZE');

drop table H4RTMP_ALCANALYZE1 cascade constraints;
prompt
prompt Creating table H4RTMP_ALCANALYZE1
prompt ================================
prompt
create global temporary table H4RTMP_ALCANALYZE1
(
  GDGID       INTEGER,
  SORT        VARCHAR2(24),
  CLS         VARCHAR2(24),
  FRAQUENCY   NUMBER(24,4),
  FLAG        VARCHAR2(4),
  ALCQTY      NUMBER(24,2),
  INVQTY      NUMBER(24,2),
  STARDATE    DATE,
  ENDDATE     DATE,
  QPC         NUMBER(24,2),
  QPCSTR      VARCHAR2(10),
  SLOT        VARCHAR2(10),
  REGIONCODE  VARCHAR2(10),
  SLOTGROUP   VARCHAR2(10),
  LACKQTY     NUMBER(24,4),
  FITRATE     NUMBER(24,4),
  COUNTS      INTEGER,
  LINE        INTEGER,
  ANALYZEFLAG VARCHAR2(24),
  ALCAMT      NUMBER(24,2),
  LACKAMT     NUMBER(24,2)
)
on commit delete rows;
exec hdcreatesynonym('H4RTMP_ALCANALYZE1');
exec granttoqryrole('H4RTMP_ALCANALYZE1');
[其它]
</REMARK>
<BEFORERUN>
DECLARE
  Vcount   Int;
  Vbgndate Date;
  Venddate Date;
  Vgdcnt   Int; ---商品总数
  Vcmd     Varchar2(1000);
  Vret     Int;
  Vcls     Varchar2(24);     
  Anayflag varchar2(24);   
  VMSG     VARCHAR2(255);  
  VUSERCODE varchar2(200);
  VLENGTH  INT;
  Vline		 int;
  Cursor c Is
    Select * From H4RTMP_ALCANALYZE Order By Fraquency Desc;
  Cursor c_Sort Is
    Select Distinct substr(Sort,1,VLENGTH) sort From H4RTMP_ALCANALYZE1;
  Cursor c_region Is
    select code from dc_slot_region;
Begin

    VUSERCODE := '\(USERCODE)';
delete TMP_VCODE;
insert into TMP_VCODE
select v.code  from psvdremp p ,employee e ,vendor v where p.vendor = v.gid and p.empgid = e.gid 
and e.code = VUSERCODE;

     DELETE FROM H4RTMP_ALCANALYZE;
     COMMIT;
     --VBGNDATE:=TO_DATE('2006.10.01','YYYY.MM.DD');
    -- VENDDATE:=TO_DATE('2006.11.01','YYYY.MM.DD');
     VBGNDATE:=TO_DATE('\(1,1)','YYYY.MM.DD');
     VENDDATE:=TO_DATE('\(2,1)','YYYY.MM.DD');
     VCLS:='\(4,1)';
     VLENGTH := 2 ; --按大类分析
     Anayflag := '\(5,1)';
 Select Trunc(Venddate) - Trunc(Vbgndate) Into Vcount From Dual;
  Insert Into H4RTMP_ALCANALYZE
    (Gdgid, Sort,regioncode, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls)
    Select a.Gdgid, b.Sort,region.code, Sum(a.Cnt), Sum(a.Fq), Vbgndate, Sum(a.Qty), Sum(nvl(a.Lackqty,0)),
           Vcls
      From (Select a.Gdgid, Count(a.Gdgid) Cnt, Round(Count(a.Gdgid) / Vcount, 4) Fq,
                    Sum(a.Qty) Qty, 0 Lackqty
               From Stkoutdtl a, Stkout b
              Where b.Num = a.Num
                And a.Cls = '统配出'
                And b.Cls = a.Cls
                And b.Stat In (700, 300)
                And b.Ocrdate < Venddate
                And b.Ocrdate >= Vbgndate
              Group By Gdgid
             Union All
             
             ---------------增加配货缺货数，这个是由于总部库存不足导致的，应该算作是商品出货频率的一部分
             Select Gdgid, Count(Gdgid) Cnt, Round(Count(Gdgid) / Vcount, 4) Fq, 0 Qty,
                    SUM(Reqqty - Acntqty) Lackqty
               From Gdlack
             Where Gendate < Venddate
                And Gendate >= Vbgndate
              Group By Gdgid) a, Goods b,da_slot_group DC ,dc_slot_region region
     Where a.Gdgid = b.Gid
       and Dc.Regioncode=Region.code
       and DC.Slotcode=b.slot
       and (Case When Not Exists (Select 1 From da_slot_group Where slotcode=b.slot)
                    Then '99999999' Else b.Slot End) =DC.Slotcode 
     Group By a.Gdgid,b.Sort, Region.code;

  --20070827增加有库存无配货商品
  Insert Into H4RTMP_ALCANALYZE
    (Gdgid, Sort,regioncode, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls)
    Select a.Gdgid, b.Sort,region.code, 0, 0, Vbgndate, 0, 0 , ''
      From Businvs a, Goods b,da_slot_group DC ,dc_slot_region region
     Where a.Store = 1000000
       And b.Gid = a.Gdgid
       And a.Wrh In (1, 1000002)
       And a.Qty <> 0
       and Dc.Regioncode=Region.code
       and (Case When Not Exists (Select 1 From da_slot_group Where slotcode=b.slot)
                    Then '99999999' Else b.Slot End) =DC.Slotcode 
       And a.Gdgid Not In (Select Gdgid From H4RTMP_ALCANALYZE);

  Select Count(Gdgid) Into Vgdcnt From H4RTMP_ALCANALYZE;

  If Vcls = '不包含整箱' Then
    Delete From H4RTMP_ALCANALYZE
     Where Exists (Select 1
              From Gdqpc
             Where Qpc <> 1
               And Isdu = 2
               And Gid = H4RTMP_ALCANALYZE.Gdgid);
  End If;

  If Anayflag = '类别' Then
    Vcmd := ''; ---通过一个临时表来对出货频次进行排序
    Begin
     Delete From H4RTMP_ALCANALYZE1 ; 
     Insert Into H4RTMP_ALCANALYZE1  (Gdgid, Sort, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls)
       Select Gdgid, Sort, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls From H4RTMP_ALCANALYZE  ;
    Exception
      When Others Then
        Null;
    End;
     
    Delete From H4RTMP_ALCANALYZE;
  
    For r_Sort In c_Sort Loop
    
      Insert Into H4RTMP_ALCANALYZE
        (Gdgid, Sort, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls , line)
        Select Gdgid, Sort, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls, Rownum
          From (Select Gdgid, Sort, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls
                   From H4RTMP_ALCANALYZE1
                  Where substr(Sort,1,VLENGTH) = r_Sort.Sort
                  Order By Fraquency Desc);
      Select Count(Gdgid) Into Vgdcnt From H4RTMP_ALCANALYZE Where substr(Sort,1,VLENGTH) = r_Sort.Sort;
    
      Update H4RTMP_ALCANALYZE
       Set Flag = 'A', Counts = Vcount
     Where Line <= Trunc(Vgdcnt * 20/ 100);
    Update H4RTMP_ALCANALYZE
       Set Flag = 'B', Counts = Vcount
     Where Line > Trunc(Vgdcnt * 20 / 100)
       And Line <= Trunc(Vgdcnt * 80 / 100);
    Update H4RTMP_ALCANALYZE
       Set Flag = 'C', Counts = Vcount
     Where Line > Trunc(Vgdcnt * 80 / 100)
       And Line <= Trunc(Vgdcnt * 95 / 100);
     Update H4RTMP_ALCANALYZE
       Set Flag = 'Z', Counts = Vcount
     Where Line > Trunc(Vgdcnt * 95 / 100);

    end loop;
    commit;
    
             --------如果筛选条件为货区
    elsif Anayflag = '货区' Then
    Vcmd := ''; ---通过一个临时表来对出货频次进行排序
    Begin
     Delete From H4RTMP_ALCANALYZE1 ; 
     Insert Into H4RTMP_ALCANALYZE1  (Gdgid, Sort,regioncode, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls)
       Select Gdgid, Sort,regioncode, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls 
       From H4RTMP_ALCANALYZE ;
    Exception
      When Others Then
        Null;
    End;
     
    Delete From H4RTMP_ALCANALYZE;
  
    For r_region In c_region Loop
    
      Insert Into H4RTMP_ALCANALYZE
        (Gdgid, Sort,regioncode, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls , line)
        Select Gdgid, Sort,regioncode, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls, Rownum
          From (Select Gdgid, Sort,regioncode, Counts, Fraquency, Stardate, Alcqty, Lackqty, Cls
                   From H4RTMP_ALCANALYZE1
                  Where regioncode = r_region.code
                  Order By Fraquency Desc);
      Select Count(Gdgid) Into Vgdcnt From H4RTMP_ALCANALYZE Where regioncode = r_region.code;
    
     Update H4RTMP_ALCANALYZE
       Set Flag = 'A', Counts = Vcount
     Where Line <= Trunc(Vgdcnt * 20/ 100);
    Update H4RTMP_ALCANALYZE
       Set Flag = 'B', Counts = Vcount
     Where Line > Trunc(Vgdcnt * 20 / 100)
       And Line <= Trunc(Vgdcnt * 80 / 100);
    Update H4RTMP_ALCANALYZE
       Set Flag = 'C', Counts = Vcount
     Where Line > Trunc(Vgdcnt * 80 / 100)
       And Line <= Trunc(Vgdcnt * 95 / 100);
     Update H4RTMP_ALCANALYZE
       Set Flag = 'Z', Counts = Vcount
     Where Line > Trunc(Vgdcnt * 95 / 100);
    
    End Loop;
 
  
    Commit;
  Else
    --------------使用序列号来排序，作为ABC分类的依据
    Vline := 0;
    For r In c Loop
      Vline := Vline + 1;
      Vret := 0;
      Update H4RTMP_ALCANALYZE
         Set Line = Vline
       Where Gdgid = r.Gdgid;
    
      Update H4RTMP_ALCANALYZE
         Set (Invqty,ordqty) = (Select Nvl(Sum(Qty), 0) , Nvl(Sum(OrdQty), 0)
                          From Businvs
                         Where Gdgid = r.Gdgid
                           And Store = 1000000
                           And Wrh In (1, 1000020))
       Where Gdgid = r.Gdgid;              
    
      Select Count(1)
        Into Vret
        From Gdqpc
       Where Isdu = 2
         And Gid = r.Gdgid;
      If Vret <> 0 Then
        Update H4RTMP_ALCANALYZE
           Set (Qpc, Qpcstr) = (Select Qpc, Qpcstr
                                   From Gdqpc
                                  Where Isdu = 2
                                    And Gid = r.Gdgid)
         Where Gdgid = r.Gdgid;
      Else
        Update H4RTMP_ALCANALYZE Set Qpc = 1.00, Qpcstr = '1*1' Where Gdgid = r.Gdgid;
      End If;
    End Loop;
  
     Update H4RTMP_ALCANALYZE
       Set Flag = 'A', Counts = Vcount
     Where Line <= Trunc(Vgdcnt * 20/ 100);
    Update H4RTMP_ALCANALYZE
       Set Flag = 'B', Counts = Vcount
     Where Line > Trunc(Vgdcnt * 20 / 100)
       And Line <= Trunc(Vgdcnt * 80 / 100);
    Update H4RTMP_ALCANALYZE
       Set Flag = 'C', Counts = Vcount
     Where Line > Trunc(Vgdcnt * 80 / 100)
       And Line <= Trunc(Vgdcnt * 95 / 100);
     Update H4RTMP_ALCANALYZE
       Set Flag = 'Z', Counts = Vcount
     Where Line > Trunc(Vgdcnt * 95 / 100);
    Commit;
  End If;
   
   If Anayflag in ('货区' , '类别') then
          Update H4RTMP_ALCANALYZE
             Set (Invqty , ordqty) = (Select Nvl(Sum(Qty), 0),Nvl(Sum(OrdQty), 0)
                              From Businvs
                             Where Gdgid = H4RTMP_ALCANALYZE.gdgid
                               And Store = 1000000
                               And Wrh In (1, 1000020)) ;

            Update H4RTMP_ALCANALYZE
               Set (Qpc, Qpcstr) = (Select Qpc, Qpcstr
                                       From Gdqpc
                                      Where Isdu = 2
                                        And Gid = H4RTMP_ALCANALYZE.Gdgid);   
    end if; 

  ----      更新分析标志
  Update H4RTMP_ALCANALYZE Set Analyzeflag = Anayflag;

  Commit;

End;
--select *from H4RTMP_ALCANALYZE
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>H4RTMP_ALCANALYZE</TABLE>
    <ALIAS>H4RTMP_ALCANALYZE</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
  <TABLEITEM>
    <TABLE>GOODS</TABLE>
    <ALIAS>GOODS</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
  <TABLEITEM>
    <TABLE>VENDOR</TABLE>
    <ALIAS>VENDOR</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
  <TABLEITEM>
    <TABLE>DA_SLOT_GROUP</TABLE>
    <ALIAS>DA_SLOT_GROUP</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
  <TABLEITEM>
    <TABLE>SORTNAME</TABLE>
    <ALIAS>SORTNAME</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
  <TABLEITEM>
    <TABLE>TMP_VCODE</TABLE>
    <ALIAS>TMP_VCODE</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
  <JOINITEM>
    <LEFT>GOODS.SLOT</LEFT>
    <OPERATOR>*=</OPERATOR>
    <RIGHT>DA_SLOT_GROUP.SLOTCODE</RIGHT>
  </JOINITEM>
  <JOINITEM>
    <LEFT>GOODS.VDRGID</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>VENDOR.GID</RIGHT>
  </JOINITEM>
  <JOINITEM>
    <LEFT>SORTNAME.ACODE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>'0000'</RIGHT>
  </JOINITEM>
  <JOINITEM>
    <LEFT>SORTNAME.SCODE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>substr(GOODS.SORT,1,2)</RIGHT>
  </JOINITEM>
  <JOINITEM>
    <LEFT>H4RTMP_ALCANALYZE.GDGID</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>GOODS.GID</RIGHT>
  </JOINITEM>
  <JOINITEM>
    <LEFT>VENDOR.CODE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>TMP_VCODE.VCODE</RIGHT>
  </JOINITEM>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>0</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>DA_SLOT_GROUP.REGIONCODE</COLUMN>
    <TITLE>货区</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>REGIONCODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>SORTNAME.SCODE</COLUMN>
    <TITLE>类别代码</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SCODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.Flag</COLUMN>
    <TITLE>分类</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>Flag</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>GOODS.CODE</COLUMN>
    <TITLE>商品代码</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>CODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>GOODS.CODE2</COLUMN>
    <TITLE>第二代码</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>CODE2</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>GOODS.NAME</COLUMN>
    <TITLE>商品名称</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>NAME</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>SORTNAME.SCODE || SORTNAME.SNAME</COLUMN>
    <TITLE>类别名称</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SNAME</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>GOODS.SPEC</COLUMN>
    <TITLE>含量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SPEC</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>GOODS.SLOT</COLUMN>
    <TITLE>货架</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SLOT</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.FRAQUENCY</COLUMN>
    <TITLE>配货频率</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>FRAQUENCY</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.ALCQTY</COLUMN>
    <TITLE>配送数量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ALCQTY</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.LACKQTY</COLUMN>
    <TITLE>缺货数量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>LACKQTY</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.ordqty</COLUMN>
    <TITLE>在单量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ordqty</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.INVQTY</COLUMN>
    <TITLE>库存数量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>INVQTY</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.ALCQTY/H4RTMP_ALCANALYZE.COUNTS</COLUMN>
    <TITLE>日配量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ALCAVGQTY</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.STARDATE</COLUMN>
    <TITLE>填单时间</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STARDATE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.COUNTS</COLUMN>
    <TITLE>统计天数</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>COUNTS</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.QPC</COLUMN>
    <TITLE>配货规格</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>QPC</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.QPCSTR</COLUMN>
    <TITLE>配货包装</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>QPCSTR</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.CLS</COLUMN>
    <TITLE>是否包含整箱</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>CLS</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>VENDOR.CODE</COLUMN>
    <TITLE>供应商代码</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>CODE1</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>VENDOR.NAME</COLUMN>
    <TITLE>供应商名称</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>NAME1</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.Analyzeflag</COLUMN>
    <TITLE>分析标志</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>Analyzeflag</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_ALCANALYZE.LINE</COLUMN>
    <TITLE>序号</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>LINE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>66</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>82</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>72</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>81</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>98</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>248</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>70</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>80</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>55</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>91</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>104</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>64</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>64</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>81</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>64</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>86</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>64</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>64</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>148</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>148</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>101</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>82</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>统计天数</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>H4RTMP_ALCANALYZE.STARDATE</LEFT>
    <OPERATOR>>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2015.04.01</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>月初</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_ALCANALYZE.STARDATE</LEFT>
    <OPERATOR><</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2015.04.12</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>明天</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_ALCANALYZE.Flag</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>A</PICKNAMEITEM>
      <PICKNAMEITEM>B</PICKNAMEITEM>
      <PICKNAMEITEM>C</PICKNAMEITEM>
      <PICKNAMEITEM>全部</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>A</PICKVALUEITEM>
      <PICKVALUEITEM>B</PICKVALUEITEM>
      <PICKVALUEITEM>C</PICKVALUEITEM>
      <PICKVALUEITEM></PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_ALCANALYZE.CLS</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>不包含整箱</PICKNAMEITEM>
      <PICKNAMEITEM>包含整箱</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>不包含整箱</PICKVALUEITEM>
      <PICKVALUEITEM></PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_ALCANALYZE.Analyzeflag</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>按类别</PICKNAMEITEM>
      <PICKNAMEITEM>按货区</PICKNAMEITEM>
      <PICKNAMEITEM>全部</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>类别</PICKVALUEITEM>
      <PICKVALUEITEM>货区</PICKVALUEITEM>
      <PICKVALUEITEM></PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_ALCANALYZE.INVQTY</LEFT>
    <OPERATOR>></OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>SORTNAME.SCODE</LEFT>
    <OPERATOR>NOT IN</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>SORTNAME.SCODE</LEFT>
    <OPERATOR>IN</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>97</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>112</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>90</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>127</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM>2015.04.01</SGLINEITEM>
    <SGLINEITEM>2015.04.12</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>0</NUMOFNEXTQRY>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>TRUE</DXLOADMETHOD>
  <DXSHOWGROUP>TRUE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>FALSE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>TRUE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>-2147483643</DXCOLORODDROW>
  <DXCOLOREVENROW>-2147483643</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERTYPE></DXFILTERTYPE>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE></RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>0</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
</RPTREPORTLIST>
</SQLREPORT>

