<VERSION>4.1.1</VERSION>
<SQLQUERY>
<REMARK>
[标题]
  入库单明细查询(门店视角)
[应用背景]
  可以用于以下场景:
   1)某个商品在某段时间被哪些配货及退货单据进行了引用,此配货单必须是影响了业务库存的
单据
   2)某张单据的单据明细,主要包含商品,发生额,成本额

[结果列描述]
  
[必要的查询条件]
  支持
[实现方法]
-- Create table
create global temporary table H4RTMP_PHMX
(
  NUM      VARCHAR2(14) not null,
  CLS      VARCHAR2(10) not null,
  GDCODE   VARCHAR2(13) not null,
  GDNAME   VARCHAR2(80),
  GDCODE2  VARCHAR2(20),
  STNAME   VARCHAR2(50) not null,
  QTY      NUMBER(24,4) not null,
  QTYSTR   VARCHAR2(15) not null,
  PRICE    NUMBER(24,4) not null,
  TOTAL    NUMBER(24,2) not null,
  TAX      NUMBER(24,2) not null,
  CAMT     NUMBER(24,2) not null,
  CTAX     NUMBER(24,2) not null,
  RTOTAL   NUMBER(24,2) not null,
  STATNAME VARCHAR2(20) not null,
  FILDATE  DATE not null,
  LINE     INTEGER not null,
  STCODE   VARCHAR2(20),
  STDSHOW  NUMBER(24,4),
  LOWINV   NUMBER(24,4),
  HIGHINV  NUMBER(24,4),
  ALCLINE  VARCHAR2(10),
  STDSHOW0 NUMBER(24,4)
)
on commit preserve rows;
-- Create/Recreate indexes 
create index IDX_H4RTMP_PHMX on H4RTMP_PHMX (NUM, CLS);
create index IDX_H4RTMP_PHMX1 on H4RTMP_PHMX (GDCODE);
create index IDX_H4RTMP_PHMX2 on H4RTMP_PHMX (FILDATE);
[版本]
CREATED BY fengchunliang 2010-4-25 16:10:50

[其它]
</REMARK>
<BEFORERUN>
DECLARE
  VBDATE  DATE;
  VEDATE  DATE;
  VNUM    VARCHAR2(2000);
  VGDCODE  VARCHAR2(20);
  VSTATNAME VARCHAR2(200);
  VFILTER1 VARCHAR2(1000);
  VCLS  VARCHAR2(14);
  valcline varchar2(10);
BEGIN

  VBDATE :=TO_DATE('\(1,1)','YYYY.MM.DD');
  VEDATE :=TO_DATE('\(2,1)','YYYY.MM.DD');
  --VNUM :=TRIM('\(3,1)');
  --PPS_CONVERSTR(VFILTER1,',',VNUM);
  VGDCODE:=TRIM('\(3,1)');
  -- VSTATNAME :=TRIM('\(5,1)');
  --VCLS := TRIM('\(5,1)');
  --valcline := trim('\(6,1)');

  DELETE FROM H4RTMP_PHMX;
  COMMIT;
    ---插入统配出数据
  INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,
TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE,stdshow,lowinv,highinv,
alcline,stdshow0)
    SELECT STKOUT.NUM , STKOUT.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      STORE.NAME , STKOUTDTL.QTY , STKOUTDTL.QTYSTR , 
      STKOUTDTL.PRICE , STKOUTDTL.TOTAL , STKOUTDTL.TAX , STKOUTDTL.CAMT , 
      STKOUTDTL.CTAX , STKOUTDTL.CRTOTAL , MODULESTAT.STATNAME,STKOUTLOG.TIME,
STKOUTDTL.LINE,STORE.CODE,gdstore.stdshow,gdstore.lowinv,gdstore.highinv,
sortstore.scode,goodsh.stdshow
    FROM STKOUT STKOUT, STKOUTLOG STKOUTLOG, STKOUTDTL STKOUTDTL, GOODSH GOODSH,
 MODULESTAT MODULESTAT, STORE STORE,sortstore,gdstore
      WHERE ((STKOUT.NUM = STKOUTDTL.NUM)
       and  (STKOUT.CLS = STKOUTDTL.CLS)
       and  (STKOUT.NUM = STKOUTLOG.NUM)
       and  (STKOUT.CLS = STKOUTLOG.CLS)
       and  (STKOUT.STAT = MODULESTAT.NO)
       and  (STKOUTDTL.GDGID = GOODSH.GID)
       and  ((STKOUT.CLS = VCLS AND VCLS IS NOT NULL) OR (STKOUT.CLS ='统配出' 
AND VCLS IS NULL))
       and  (STKOUT.BILLTO = STORE.GID)
       --and  (STKOUT.STAT = STKOUTLOG.STAT)
       and  (STKOUTLOG.STAT = 700)
       and  (STKOUTLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKOUTLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (STKOUT.NUM LIKE VNUM||'%' OR VNUM IS NULL)
       and  (GOODSH.CODE LIKE VGDCODE||'%' OR VGDCODE IS NULL) )
       and store.gid = sortstore.gid
  and gdstore.storegid = store.gid
  and gdstore.gdgid = goodsh.gid
  and sortstore.scode like valcline||'%';
  COMMIT;
    ---插入统配出退数据
  INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,
TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE,
alcline,stdshow0)
    SELECT STKOUT.NUM , STKOUT.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      STORE.NAME , STKOUTDTL.QTY , STKOUTDTL.QTYSTR , 
      STKOUTDTL.PRICE , STKOUTDTL.TOTAL , STKOUTDTL.TAX , STKOUTDTL.CAMT , 
      STKOUTDTL.CTAX , STKOUTDTL.CRTOTAL , MODULESTAT.STATNAME,STKOUTLOG.TIME,
STKOUTDTL.LINE,STORE.CODE,
sortstore.scode,goodsh.stdshow
    FROM STKOUTBCK STKOUT, STKOUTBCKLOG STKOUTLOG, STKOUTBCKDTL STKOUTDTL, 
GOODSH GOODSH, MODULESTAT MODULESTAT, STORE STORE,sortstore
      WHERE ((STKOUT.NUM = STKOUTDTL.NUM)
       and  (STKOUT.CLS = STKOUTDTL.CLS)
       and  (STKOUT.NUM = STKOUTLOG.NUM)
       and  (STKOUT.CLS = STKOUTLOG.CLS)
       and  (STKOUT.STAT = MODULESTAT.NO)
       and  (STKOUTDTL.GDGID = GOODSH.GID)
       and  ((STKOUT.CLS = VCLS AND VCLS IS NOT NULL) OR (STKOUT.CLS 
='统配出退' AND VCLS IS NULL))
       and  (STKOUT.BILLTO = STORE.GID)
       --and  (STKOUT.STAT = STKOUTLOG.STAT)
       and  (STKOUTLOG.STAT = 300 )
       and  (STKOUTLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKOUTLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (STKOUT.NUM LIKE VNUM||'%' OR VNUM IS NULL)
       and  (GOODSH.CODE LIKE VGDCODE||'%' OR VGDCODE IS NULL))
       and store.gid = sortstore.gid
  and sortstore.scode like valcline||'%';
  COMMIT;
---插入直配出数据
   INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,
TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE,stdshow,lowinv,highinv,
alcline,stdshow0)
    SELECT diralc.NUM , diralc.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      STORE.NAME , diralcDTL.QTY , diralcDTL.QTYSTR , 
      diralcDTL.PRICE , diralcDTL.TOTAL , diralcDTL.TAX , diralcDTL.CAMT , 
      diralcDTL.CTAX , diralcDTL.CRTLPRC , MODULESTAT.STATNAME,diralcLOG.TIME,
diralcDTL.LINE,STORE.CODE,gdstore.stdshow,gdstore.lowinv,gdstore.highinv,
sortstore.scode,goodsh.stdshow
    FROM diralc diralc, diralcLOG diralcLOG, diralcDTL diralcDTL, GOODSH GOODSH,
 MODULESTAT MODULESTAT, STORE STORE,sortstore,gdstore
      WHERE ((diralc.NUM = diralcDTL.NUM)
       and  (diralc.CLS = diralcDTL.CLS)
       and  (diralc.NUM = diralcLOG.NUM)
       and  (diralc.CLS = diralcLOG.CLS)
       and  (diralc.STAT = MODULESTAT.NO)
       and  (diralcDTL.GDGID = GOODSH.GID)
       and  ((diralc.CLS = VCLS AND VCLS IS NOT NULL) OR (diralc.CLS ='直配出' 
AND VCLS IS NULL))
       and  (diralc.BILLTO = STORE.GID)
       --and  (diralc.STAT = diralcLOG.STAT)
       and  (diralcLOG.STAT = 700)
       and  (diralcLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (diralcLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (diralc.NUM LIKE VNUM||'%' OR VNUM IS NULL)
       and  (GOODSH.CODE LIKE VGDCODE||'%' OR VGDCODE IS NULL) )
       and store.gid = sortstore.gid
  and gdstore.storegid = store.gid
  and gdstore.gdgid = goodsh.gid
  and sortstore.scode like valcline||'%';

  COMMIT;
---插入直配出退数据
INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,
TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE,
alcline,stdshow0)
    SELECT diralc.NUM , diralc.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      STORE.NAME , diralcDTL.QTY , diralcDTL.QTYSTR , 
      diralcDTL.PRICE , diralcDTL.TOTAL , diralcDTL.TAX , diralcDTL.CAMT , 
      diralcDTL.CTAX , diralcDTL.CRTLPRC , MODULESTAT.STATNAME,diralcLOG.TIME,
diralcDTL.LINE,STORE.CODE,
sortstore.scode,goodsh.stdshow
    FROM diralc diralc, diralcLOG diralcLOG, diralcdtl diralcDTL, 
GOODSH GOODSH, MODULESTAT MODULESTAT, STORE STORE,sortstore
      WHERE ((diralc.NUM = diralcDTL.NUM)
       and  (diralc.CLS = diralcDTL.CLS)
       and  (diralc.NUM = diralcLOG.NUM)
       and  (diralc.CLS = diralcLOG.CLS)
       and  (diralc.STAT = MODULESTAT.NO)
       and  (diralcDTL.GDGID = GOODSH.GID)
       and  ((diralc.CLS = VCLS AND VCLS IS NOT NULL) OR (diralc.CLS 
='直配出退' AND VCLS IS NULL))
       and  (diralc.BILLTO = STORE.GID)
       --and  (diralc.STAT = diralcLOG.STAT)
       and  (diralcLOG.STAT = 300 )
       and  (diralcLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (diralcLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (diralc.NUM LIKE VNUM||'%' OR VNUM IS NULL)
       and  (GOODSH.CODE LIKE VGDCODE||'%' OR VGDCODE IS NULL))
       and store.gid = sortstore.gid
  and sortstore.scode like valcline||'%';
  COMMIT;
END;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>H4RTMP_PHMX</TABLE>
    <ALIAS>H4RTMP_PHMX</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD>123</INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>1</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>NUM</COLUMN>
    <TITLE>单号</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>NUM</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>cls</COLUMN>
    <TITLE>单据类型</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>cls</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>line</COLUMN>
    <TITLE>行号</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>line</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>STCODE</COLUMN>
    <TITLE>门店代码</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STCODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>stname</COLUMN>
    <TITLE>门店名称</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>stname</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>substr(gdcode,1,2)</COLUMN>
    <TITLE>大类</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>sort</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>0</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>gdcode</COLUMN>
    <TITLE>商品代码</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>gdcode</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>gdname</COLUMN>
    <TITLE>商品名称</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>gdname</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>gdcode2</COLUMN>
    <TITLE>商品条码</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>gdcode2</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'直配出',1,'直配出退',-1,1)*qty</COLUMN>
    <TITLE>数量</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>qty</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>qtystr</COLUMN>
    <TITLE>包装数量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>qtystr</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>price</COLUMN>
    <TITLE>包装规格价</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>price</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'直配出',1,'直配出退',-1,1)*total</COLUMN>
    <TITLE>配货含税金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>total</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'直配出',1,'直配出退',-1,1)*tax</COLUMN>
    <TITLE>配货税额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>tax</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'直配出',1,'直配出退',-1,1)*camt</COLUMN>
    <TITLE>配货去税成本额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>camt</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'直配出',1,'直配出退',-1,1)*ctax</COLUMN>
    <TITLE>配货成本税额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ctax</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'直配出',1,'直配出退',-1,1)*rtotal</COLUMN>
    <TITLE>配货零售额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>rtotal</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>statname</COLUMN>
    <TITLE>单据状态</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>statname</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>fildate</COLUMN>
    <TITLE>完成时间</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>fildate</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>stdshow0</COLUMN>
    <TITLE>商品陈列标准量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>stdshow0</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>stdshow</COLUMN>
    <TITLE>门店陈列量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>stdshow</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>highinv</COLUMN>
    <TITLE>门店商品上限</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>highinv</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>alcline</COLUMN>
    <TITLE>路线号</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>alcline</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>64</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>166</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>101</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>100</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>210</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>83</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>102</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>78</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>97</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>78</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
  <GROUPITEM>
    <COLUMN>cls</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>STCODE</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>stname</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>substr(gdcode,1,2)</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>gdcode</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>gdname</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>gdcode2</COLUMN>
  </GROUPITEM>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>门店名称</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
  <ORDERITEM>
    <COLUMN>大类</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>fildate</LEFT>
    <OPERATOR>>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2015.01.01</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>昨天</DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>fildate</LEFT>
    <OPERATOR><</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2015.02.03</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>今天</DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>gdname</LEFT>
    <OPERATOR>LIKE</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>STCODE</LEFT>
    <OPERATOR>LIKE</OPERATOR>
    <RIGHT>
      <RIGHTITEM>40001</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>STCODE</LEFT>
    <OPERATOR>IN</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>stname</LEFT>
    <OPERATOR>LIKE</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>151</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>122</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>170</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>153</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>120</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>124</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM>2015.01.01</SGLINEITEM>
    <SGLINEITEM>2015.02.03</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM>40001</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>0</NUMOFNEXTQRY>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>TRUE</DXLOADMETHOD>
  <DXSHOWGROUP>TRUE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>TRUE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>TRUE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>16777215</DXCOLORODDROW>
  <DXCOLOREVENROW>15921906</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERTYPE></DXFILTERTYPE>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE>入库单明细查询（配货业务）</RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>18</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
  <RPTCOLUMNWIDTHITEM>92</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>32</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>97</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>86</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>38</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>80</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>92</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>80</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>122</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>128</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
</RPTREPORTLIST>
</SQLREPORT>

