version: '3'
services:
  elasticsearch:        
   # image: elasticsearch:7.1.1    
    image: 192.168.15.200:8888/elk/elasticsearch:7.1.1
    container_name: elasticsearch  
    hostname: elasticsearch
    restart: always                 
    environment:                                    
      - discovery.type=single-node 
      - node.name=node1                  
      - network.publish_host=192.168.15.199 
      - network.host=0.0.0.0               
      - bootstrap.memory_lock=true  
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"   
    ulimits:             
      memlock:
        soft: -1      
        hard: -1
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 2G
        reservations:
           cpus: '0.5'
           memory: 200M
    volumes:
      - /data/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
      - esdata:/usr/share/elasticsearch/data  
      - /etc/localtime:/etc/localtime
    ports:
      - 9200:9200 
      - 9300:9300  
  kibana:
    #image: docker.elastic.co/kibana/kibana:7.1.1
    image: 192.168.15.200:8888/elk/kibana:7.1.1
    container_name: kibana
    hostname: kibana
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200 
    depends_on:
      - elasticsearch  
    restart: always
    volumes:
      - /data/elk/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /etc/localtime:/etc/localtime
    ports:
      - 5601:5601
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 500M
        reservations:
           cpus: '0.5'
           memory: 100M
#  logstash:
#    #image: docker.elastic.co/logstash/logstash:7.1.1
#    image: 192.168.15.200:8888/elk/logstash:7.1.1
#    container_name: logstash
#    hostname: logstash
#    restart: always
#    volumes:
#      - /data/elk/production.conf:/usr/share/logstash/pipeline/logstash.conf
#      - /etc/localtime:/etc/localtime
#    depends_on:
#      - elasticsearch
#    ports:
#      - 34567:34567    #tcp
#      - 9600:9600      #API Interface
#      - 5044:5044      #filebeat
#      - 5140:5140      #syslog
#    deploy:
#     resources:
#        limits:
#           cpus: '2'
#           memory: 1G
#        reservations:
#           cpus: '0.5'
#           memory: 200M
  nginx:
    image: 192.168.15.200:8888/mydocker/nginx:1.19.1
    #image: nginx:1.19.1
    container_name: nginx
    hostname: nginx
    restart: always
    volumes:
      - /data/elk/.users:/etc/nginx/.users
      - /data/elk/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - elasticsearch
      - kibana
    network_mode: host
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 500M
        reservations:
           cpus: '0.5'
           memory: 100M
volumes:
  esdata:
    driver: local  
