apiVersion: v1
kind: Pod
metadata: 
  name: pod-demo
  labels: 
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "400m"
