apiVersion: v1
kind: Pod
metadata:
  name: nexus
  namespace: default
  labels: 
    app: nexus
spec:
  nodeSelector:
    custom.app.name: nexus
  containers: 
  - name: nexus
    image: sonatype/nexus3
    ports:
    - name: http
      containerPort: 8081
    volumeMounts:
    - name: nexusdata
      mountPath: /nexus-data
  volumes:
  - name: nexusdata
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: default
spec:
  type: NodePort
  ports:
  - name: nexus
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: nexus    

