{
 "title": "IIS",
 "description": "windows iis service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_os_time, job)"
   },
   {
    "name": "host",
    "label": "Hostname",
    "query": "label_values(windows_iis_worker_threads{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Start Time",
   "type": "graph",
   "description": "进程开始时间",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - windows_process_start_time{instance=\"$host\",process=~\"w3wp.*\"}",
     "legendFormat": "{{process}} | {{process_id}}"
    }
   ]
  },
  {
   "title": "Process Usage CPU Time",
   "type": "graph",
   "description": "返回此进程的所有线程使用处理器按模式（特权、用户）执行指令所用的时间。指令是计算机中的基本执行单位，线程是执行指令的对象，进程是程序运行时创建的对象。此计数中包括为处理某些硬件中断和陷阱条件而执行的代码。",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_cpu_time_total{instance=\"$host\",process=~\"w3wp.*\"}[1m])",
     "legendFormat": "{{process}} | {{process_id}}"
    }
   ]
  },
  {
   "title": "Process Usage Memory",
   "type": "graph",
   "description": "此进程已在分页文件中使用的当前字节数。页面文件用于存储进程使用的未包含在其他文件中的内存页面。页面文件由所有进程共享，页面文件中空间不足会阻止其他进程分配内存。",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_process_page_file_bytes{instance=\"$host\",process=~\"w3wp.*\"}",
     "legendFormat": "{{process}} | {{process_id}}"
    }
   ]
  },
  {
   "title": "Process Total  Read/Write IO Number",
   "type": "graph",
   "description": "以不同模式（读取、写入、其他）向 I/O 操作发出的字节数。此属性计算进程生成的所有 I/O 活动，包括文件、网络和设备 I/O。读写方式包括数据操作；其他模式包括那些不涉及数据的模式，例如控制操作。",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_process_io_bytes_total {instance=\"$host\",process=~\"w3wp.*\"}[5m])",
     "legendFormat": "{{process}} | {{process_id}}"
    }
   ]
  },
  {
   "title": "Process Open File Number",
   "type": "graph",
   "description": "进程已打开的句柄总数。这个数字是进程中每个线程当前打开的句柄的总和。",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_process_handles{instance=\"$host\",process=~\"w3wp.*\"}",
     "legendFormat": "{{process}} | {{process_id}}"
    }
   ]
  },
  {
   "title": "Process Reference Memory Error",
   "type": "graph",
   "description": "由在此进程中执行的线程引起的页面错误。当线程引用不在其在主内存中的工作集中的虚拟内存页面时，会发生页面错误。如果页面在备用列表中并因此已经在主内存中，或者如果它正在被与该页面共享的另一个进程使用，这可能会导致无法从磁盘获取该页面。",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_process_page_faults_total{instance=\"$host\",process=~\"w3wp.*\"}[5m])",
     "legendFormat": "{{process}} | {{process_id}}"
    }
   ]
  },
  { "title": "IIS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "VHost Uptime",
   "type": "graph",
   "description": "Web 服务或网站的正常运行时间（秒）",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "windows_iis_service_uptime{instance=~\"$host\"}",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Application Pool State",
   "type": "graph",
   "description": "应用程序池的当前状态（1 - 未初始化，2 - 已初始化，3 - 正在运行，4 - 正在禁用，5 - 已禁用，6 - 关闭挂起，7 - 删除挂起）",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_current_application_pool_state{instance=~\"$host\"} == 1",
     "legendFormat": "{{exported_app}} | {{state}}"
    }
   ]
  },
  {
   "title": "Current In Application Pool Run Process Number",
   "type": "graph",
   "description": "当前在应用程序池中运行的工作进程数",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_iis_current_worker_processes {instance=~\"$host\"} == 1",
     "legendFormat": "{{exported_app}}"
    }
   ]
  },
  {
   "title": "IIS Connections Number",
   "type": "graph",
   "description": "自服务启动后尝试连接到 Web 服务的次数",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_connection_attempts_all_instances_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Logon Number",
   "type": "graph",
   "description": "自服务启动后尝试登录 Web 服务的次数",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_logon_attempts_total {instance=~\"$host\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "VHost Sent Data Size",
   "type": "graph",
   "description": "自服务启动后 Web 服务已发送的数据字节数",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_sent_bytes_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "VHost Received Data Size",
   "type": "graph",
   "description": "自服务启动以来 Web 服务已接收的数据的总字节数",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_received_bytes_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Sent ISAPI Extended Request Number",
   "type": "graph",
   "description": "自 Web 服务启动以来发出的 ISAPI 扩展请求数",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_ipapi_extension_requests_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "HTTP Request Total",
   "type": "graph",
   "description": "工作进程处理的 HTTP 请求总数",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_worker_requests_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{exported_app}}"
    }
   ]
  },
  {
   "title": "HTTP GET Requests",
   "type": "graph",
   "description": "自 Web 服务启动以来发出的GET请求数",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_requests_total{instance=~\"$host\",method=\"GET\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "HTTP POST Requests",
   "type": "graph",
   "description": "自 Web 服务启动以来发出的POST请求数",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_requests_total{instance=~\"$host\",method=\"POST\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "HTTP 404",
   "type": "graph",
   "description": "通常报告为 HTTP 错误 404",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_not_found_errors_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "URI Cache Query Total",
   "type": "graph",
   "description": "uri 缓存查询总数（命中 + 未命中）",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_worker_uri_cache_queries_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{exported_app}}"
    }
   ]
  },
  {
   "title": "Current Cache File Size",
   "type": "graph",
   "description": "当前文件缓存使用的字节数",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_iis_worker_file_cache_memory_bytes{instance=~\"$host\"} ",
     "legendFormat": "{{exported_app}}"
    }
   ]
  },
  {
   "title": "Anonymous Users Rate ",
   "type": "graph",
   "description": "自 Web 服务启动以来建立匿名请求的用户数",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_anonymous_users_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  }
 ]
}