{
 "title": "IIS",
 "description": "Monitor your IIS server with metrics coming from wmi_exporter.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_os_time,job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(windows_iis_requests_total{job=~\"$job\"},instance)"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(windows_iis_current_application_pool_state{job=~\"$job\",instance=~\"$instance\"},app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Web Service Connections",
   "type": "graph",
   "description": "当前与 Web 服务建立的连接数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_iis_current_connections{instance=\"$instance\"}",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Total Requests by Type",
   "type": "graph",
   "description": "Total requests divided by type of request [5m]",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_iis_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{site}} {{method}}"
    }
   ]
  },
  {
   "title": "Use Web Service Connection Number",
   "type": "graph",
   "description": "已尝试使用 Web 服务的连接数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_iis_connection_attempts_all_instances_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "App Pool  Failed Of Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_iis_recent_worker_process_failures{instance=~\"$instance\"}",
     "legendFormat": "{{exported_app}}"
    }
   ]
  },
  {
   "title": "Received Files Number[5m]",
   "type": "graph",
   "description": "received Number of files",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_iis_files_received_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Sent Files Number [5m]",
   "type": "graph",
   "description": "sentNumber of files",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_iis_files_sent_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Data sent",
   "type": "graph",
   "description": "Increase in data sent by the application.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "irate(windows_iis_sent_bytes_total{instance=~\"$instance\"}[5m])/1024 ",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Data received",
   "type": "graph",
   "description": "Increase in data received by the application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "irate(windows_iis_received_bytes_total{instance=~\"$instance\"}[5m])/1024",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "New Anonymous Users[5m]",
   "type": "graph",
   "description": "Increase of anonymous users per 5m.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_iis_anonymous_users_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  }
 ]
}