{
 "title": "VMware ESXi",
 "description": "VMware ESXi single instance graphs.",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "esxhost",
    "label": "Host",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "vmware_host_boot_timestamp_seconds{host_name=~\"$esxhost\"} / 60"
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$esxhost\"} / vmware_host_cpu_max{host_name=~\"$esxhost\"})  * 100 "
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"} / vmware_host_memory_max{host_name=~\"$esxhost\"}) * 100 "
    }
   ]
  },
  {
   "title": "Host Datastore Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(vmware_datastore_capacity_size{app=~\"$esxhost\", ds_name=~\"datastore.*\"}) - (vmware_datastore_freespace_size{app=~\"$esxhost\", ds_name=~\"datastore.*\"})",
     "legendFormat": "{{ds_name}} Usage:"
    },
    {
     "expr": "vmware_datastore_capacity_size{app=~\"$esxhost\", ds_name=~\"datastore.*\"} ",
     "legendFormat": "{{ds_name}} Total:"
    },
    {
     "expr": "vmware_datastore_freespace_size{app=~\"$esxhost\", ds_name=~\"datastore.*\"}",
     "legendFormat": "{{ds_name}} Free:"
    }
   ]
  },
  {
   "title": "VM CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{host_name=~\"$esxhost\"} / (vmware_vm_num_cpu{host_name=~\"$esxhost\"} * 1000) * 100",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_vm_mem_usage_average{host_name=~\"$esxhost\"}  / vmware_vm_memory_max{host_name=~\"$esxhost\"} ) * 100",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  }
 ]
}