{
 "title": "Kubernetes API Server",
 "description": "Latency and cache hit graphs for Kubernetes apiserver.  Useful for observing performance of Amazon EKS clusters.",
 "tags": [
  "Prometheus ",
  "Kubernetes"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(up{instance=~\".*:6443\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "API Server Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$job\"}==1)"
    }
   ]
  },
  {
   "title": "API Server Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "host: {{instance}}"
    }
   ]
  },
  {
   "title": "apiserver request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "workqueue service time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "service time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "apiserver request latency",
   "type": "graph",
   "description": "95th percentile request latency for Kubernetes apiserver component",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p50 "
    }
   ]
  },
  {
   "title": "workqueue processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "processing time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "etcd helper cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_helper_cache_hit_total[5m]))/sum((rate(etcd_helper_cache_hit_total[5m])+rate(etcd_helper_cache_miss_total[5m])))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "etcd request latency",
   "type": "graph",
   "description": "etcd request latency (p95)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}