apiVersion: v1
kind: Pod
metadata: 
  name: liveness-exec
  namespace: default
  labels: 
    app: liveness
spec:
  containers:
  - name: liveness-exec-container
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sh"
    - "-c"
    - "touch /tmp/healthy;sleep 30; rm -f /tmp/healthy;sleep 3600"
    livenessProbe:
      exec:
        command:
        - "test"
        - "-e"
        - "/tmp/healthy"
      initialDelaySeconds: 2
      periodSeconds: 3
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
  restartPolicy: Always
  
