{
 "title": "my dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "instance",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "套接字连接数",
   "type": "graph",
   "description": "套接字连接数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netstat_established_connections",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Memory使用率",
   "type": "graph",
   "description": "Memory使用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - ((node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) /node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "description": "CPU使用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - ((sum(increase(node_cpu_seconds_total{mode=\"idle\"}[1m])) by(instance)) / (sum(increase(node_cpu_seconds_total[1m])) by (instance)))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk可用空间比率",
   "type": "graph",
   "description": "Disk可用空间比率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_free_bytes{device=~\"/dev/sd.*\"}) by(instance) / sum(node_filesystem_size_bytes{device=~\"/dev/sd.*\"}) by(instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk_IO使用率(Mb)",
   "type": "graph",
   "description": "Disk_IO使用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((rate(node_disk_read_bytes_total[1m]) + rate(node_disk_written_bytes_total[1m])) /1024 /1024) > 0",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  {
   "title": "ping prometheus_server 延迟",
   "type": "graph",
   "description": "ping prometheus_server 延迟",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ping_delay", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Network流量(Mb)",
   "type": "graph",
   "description": "Network流量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth.*\"}[1m]) /1024 /1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ping prometheus_server 抖动范围(ms)",
   "type": "graph",
   "description": "ping prometheus_server 抖动范围",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ping_shake_fu",
     "legendFormat": "ping_shake_fu {{exported_instance}}"
    },
    {
     "expr": "ping_shake_zheng",
     "legendFormat": "ping_shake_zheng {{exported_instance}}"
    }
   ]
  },
  {
   "title": "ping prometheus_server 丢包率",
   "type": "graph",
   "description": "ping prometheus_server 丢包率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ping_loss", "legendFormat": "{{exported_instance}}" }
   ]
  }
 ]
}