<VERSION>4.1.0</VERSION>
<SQLQUERY>
<REMARK>
[标题]：缺失流水号查询

[应用背景] ：该报表由谁提出，要解决什么问题，用途
用于检查对应日期、收银机，缺失的流水号

[结果列描述] ：

[必要的查询条件] ：

[实现方法] ：简要描述报表的数据源、构造算法，以及关键列的算法

[临时表结构]：如果有用到临时表，需要附加临时表的创建sql
CREATE GLOBAL TEMPORARY TABLE H4RTMP_MSDFLOWNUM
(
  MSDATE    DATE,
  POSNO     VARCHAR2(20),
  STOREGID  INTEGER,
  FLOWNO    VARCHAR2(20)
)
ON COMMIT PRESERVE ROWS;
EXEC hdcreatesynonym('H4RTMP_MSDFLOWNUM');
EXEC granttoqryrole('H4RTMP_MSDFLOWNUM');

CREATE GLOBAL TEMPORARY TABLE H4RTMP_MSDFLOWNUMEX
(
  MSDATE    DATE,
  POSNO     VARCHAR2(20),
  STOREGID  INTEGER,
  FLOWNO    VARCHAR2(20)
)
ON COMMIT PRESERVE ROWS;
EXEC hdcreatesynonym('H4RTMP_MSDFLOWNUMEX');
EXEC granttoqryrole('H4RTMP_MSDFLOWNUMEX');

CREATE GLOBAL TEMPORARY TABLE H4RTMP_MSDFLOWNUMEX2
(
  MSDATE    DATE,
  POSNO     VARCHAR2(20),
  STOREGID  INTEGER,
  FLOWNO    VARCHAR2(20)
)
ON COMMIT PRESERVE ROWS;
EXEC hdcreatesynonym('H4RTMP_MSDFLOWNUMEX2');
EXEC granttoqryrole('H4RTMP_MSDFLOWNUMEX2');


[版本记录]： 时间+创建人/修改人，后续修改在原有基础上追加
2010年10月03日 16:39 修改人：邹勇

[其它]：可选
</REMARK>
<BEFORERUN>
/*
CREATE GLOBAL TEMPORARY TABLE H4RTMP_MSDFLOWNUM
(
  MSDATE    DATE,
  POSNO     VARCHAR2(20),
  STOREGID  INTEGER,
  FLOWNO    VARCHAR2(20)
)
ON COMMIT PRESERVE ROWS;
EXEC hdcreatesynonym('H4RTMP_MSDFLOWNUM');
EXEC granttoqryrole('H4RTMP_MSDFLOWNUM');

CREATE GLOBAL TEMPORARY TABLE H4RTMP_MSDFLOWNUMEX
(
  MSDATE    DATE,
  POSNO     VARCHAR2(20),
  STOREGID  INTEGER,
  FLOWNO    VARCHAR2(20)
)
ON COMMIT PRESERVE ROWS;
EXEC hdcreatesynonym('H4RTMP_MSDFLOWNUMEX');
EXEC granttoqryrole('H4RTMP_MSDFLOWNUMEX');

CREATE GLOBAL TEMPORARY TABLE H4RTMP_MSDFLOWNUMEX2
(
  MSDATE    DATE,
  POSNO     VARCHAR2(20),
  STOREGID  INTEGER,
  FLOWNO    VARCHAR2(20)
)
ON COMMIT PRESERVE ROWS;
EXEC hdcreatesynonym('H4RTMP_MSDFLOWNUMEX2');
EXEC granttoqryrole('H4RTMP_MSDFLOWNUMEX2');

*/

DECLARE

	VPOSNO  VARCHAR2(20);
	vbdate	DATE;
	vedate	date;
	VMINFNUM  VARCHAR2(20);
	VMAXFNUM  VARCHAR2(20);
	VFNUM  VARCHAR2(20);
	Cursor C Is
		select msdate, posno, flowno  from H4RTMP_MSDFLOWNUMex;

BEGIN
	DELETE FROM H4RTMP_MSDFLOWNUM;
	DELETE FROM H4RTMP_MSDFLOWNUMex;
	DELETE FROM H4RTMP_MSDFLOWNUMex2;
	COMMIT;

	vbdate := to_date(TRIM('\(1,1)'),'YYYY.MM.DD');
	vedate := to_date(TRIM('\(2,1)'),'YYYY.MM.DD');
	VPOSNO := TRIM('\(3,1)');
	
	if vbdate is null then
		begin
			select to_date(substr(min(flowno), 1, 8), 'YYYY.MM.DD') into vbdate from buy1s;
		exception
			when no_data_found	then
				vbdate := to_date('1899.01.01', 'YYYY.MM.DD');
		end;
	end if;
	
	if vedate is null then
		vedate := trunc(sysdate);
	end if;
	
	insert into H4RTMP_MSDFLOWNUMex(msdate, posno, flowno)
	select to_date(substr(b1.flowno, 1, 8), 'YYYY.MM.DD'), b1.posno, max(b1.flowno)
	from buy1s b1
	where (to_date(substr(b1.flowno, 1, 8), 'YYYY.MM.DD') < vedate)
		and (to_date(substr(b1.flowno, 1, 8), 'YYYY.MM.DD') >= vbdate)
		and (b1.posno = vposno or vposno is null)
	group by substr(b1.flowno, 1, 8), b1.posno;
	commit;

	for R in c loop
		insert into H4RTMP_MSDFLOWNUMex2(posno, flowno)
		select r.posno, to_number(to_char(r.msdate, 'YYYYMMDD')||'0001') + rownum - 1 
		from all_objects
		where rownum <= to_number(substr(r.flowno, -4, 4));
	end loop;
	commit;

	insert into H4RTMP_MSDFLOWNUM(msdate, posno, flowno)
	select to_date(substr(ex2.flowno, 1, 8),'yyyy.mm.dd'), ex2.posno, ex2.flowno
	from H4RTMP_MSDFLOWNUMex2 ex2
	where not exists(
		select 1 from buy1s b1 where b1.posno = ex2.posno and b1.flowno = ex2.flowno	);
	commit;
END;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>H4RTMP_MSDFLOWNUM</TABLE>
    <ALIAS>H4RTMP_MSDFLOWNUM</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>0</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_MSDFLOWNUM.MSDATE</COLUMN>
    <TITLE>日期</TITLE>
    <FIELDTYPE>11</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>日期</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>yyyy.mm.dd</CDISFORMAT>
    <CGROUPINDEX>0</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_MSDFLOWNUM.POSNO</COLUMN>
    <TITLE>收银机号</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>收银机号</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_MSDFLOWNUM.FLOWNO</COLUMN>
    <TITLE>流水号</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>COUNT</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>流水号</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>233</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>186</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>318</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>流水号</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
  <ORDERITEM>
    <COLUMN>收银机号</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
  <ORDERITEM>
    <COLUMN>日期</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>H4RTMP_MSDFLOWNUM.MSDATE</LEFT>
    <OPERATOR>>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2010.09.26</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>昨天</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_MSDFLOWNUM.MSDATE</LEFT>
    <OPERATOR><=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2010.10.09</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>今天</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_MSDFLOWNUM.POSNO</LEFT>
    <OPERATOR>LIKE</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>122</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>139</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>88</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM>2010.09.26</SGLINEITEM>
    <SGLINEITEM>2010.10.09</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>0</NUMOFNEXTQRY>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>TRUE</DXLOADMETHOD>
  <DXSHOWGROUP>FALSE</DXSHOWGROUP>
  <DXSHOWFOOTER>FALSE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>FALSE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>FALSE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>12632256</DXCOLORODDROW>
  <DXCOLOREVENROW>15921906</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE>缺失流水号查询</RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>3</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>80</RPTCOLUMNWIDTHITEM>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
</RPTREPORTLIST>
</SQLREPORT>

