<VERSION>4.1.1</VERSION>
<SQLQUERY>
<REMARK>
[标题]

[应用背景]
         仓库缺货                              拣货缺货
	导致转单数量比定货数量少             导致货没有完全拣出来了
A商品        A缺                                   A缺
B            B缺                                   
C                                                    
D            D缺                                 
E                                                  E缺

总的缺货的商品品项ABDE 4个
其中仓库缺货ABD 3个
拣货缺货AE 2个

那仓库缺货品项占比是  3/4
拣货缺货品项占比是   2/4

仓库缺货品项占比 + 拣货缺货品项占比 >= 1

[结果列描述]
配货满足率：实际出货金额/需求金额
采购缺货占比：账面库存不足导致的缺货品项/所有缺货品项
拣货缺货占比：锁定库存后未拣出实物的缺货品项/所有缺货品项
配货额环比：本周配货额-上周配货额/上周配货额
满足率环比：本周配货满足率-上周配货满足率/上周配货满足率
采购缺货环比：本周采购缺货占比-上周采购缺货占比/上周采购缺货占比
拣货缺货环比：本周拣货缺货占比-上周拣货缺货占比/上周拣货缺货占比

[必要的查询条件]

[实现方法]

[其它]
</REMARK>
<BEFORERUN>
declare
vDate date;
vWeekEndDate date;
vWeekBegDate date;
begin
  vDate := to_date('\(1,1)','yyyy.mm.dd');
  vWeekEndDate := hdrpt_basic.getWeekEnddateByday(vDate);
  vWeekBegDate := vWeekEndDate -6;

  delete from H4RTMP_AlcFitDrpt;
  commit;
/*
  insert into H4RTMP_AlcFitDrpt(QueryDate,FILDATE,ALCFIT,ALCTOTAL,ORDLACK,WRHLACK,SORTALACK,SORTBLACK,SORTCLACK,ISWEEKAVG,ordqtylack,wrhqtylack
                                ,ALCFIT_LINK,ALCTOTAL_LINK,ORDLACK_LINK,WRHLACK_LINK,ORDQTYLACK_LINK,WRHQTYLACK_LINK)
  select vDate,C.FILDATE,NVL(R.ALCFIT,0)*100,NVL(R.ALCTOTAL,0),NVL(R.ORDLACK,0),NVL(R.WRHLACK,0),
         NVL(R.SORTALACK,0),NVL(R.SORTBLACK,0),NVL(R.SORTCLACK,0),NVL(R.ISWEEKAVG,0),nvl(r.ordqtylack,0),nvl(r.wrhqtylack,0),
         NVL(r_LINK.ALCFIT,0)*100,NVL(r_LINK.ALCTOTAL,0),NVL(r_LINK.ORDLACK,0),NVL(r_LINK.WRHLACK,0),nvl(r_LINK.ordqtylack,0),nvl(r_LINK.wrhqtylack,0)
  from (select * from RPT_AlcFitDrpt where isweekavg<>1) R,(SELECT FILDATE+7 FILDATE,ALCFIT,ALCTOTAL,ORDLACK,WRHLACK,ORDQTYLACK,WRHQTYLACK
    FROM RPT_AlcFitDrpt where isweekavg<>1) R_LINK
        ,HDRPTCALENDAR C
   where C.fildate between vWeekBegDate and vWeekEndDate
     AND C.FILDATE = R.FILDATE (+)
     AND C.FILDATE = R_LINK.FILDATE (+);


  insert into H4RTMP_AlcFitDrpt(QueryDate,FILDATE,ALCFIT,ALCTOTAL,ORDLACK,WRHLACK,SORTALACK,SORTBLACK,SORTCLACK,ISWEEKAVG,ordqtylack,wrhqtylack
                                ,ALCFIT_LINK,ALCTOTAL_LINK,ORDLACK_LINK,WRHLACK_LINK,ORDQTYLACK_LINK,WRHQTYLACK_LINK)
  select vDate,C.FILDATE,NVL(R.ALCFIT,0)*100,NVL(R.ALCTOTAL,0),NVL(R.ORDLACK,0),NVL(R.WRHLACK,0),
         NVL(R.SORTALACK,0),NVL(R.SORTBLACK,0),NVL(R.SORTCLACK,0),NVL(R.ISWEEKAVG,0),nvl(r.ordqtylack,0),nvl(r.wrhqtylack,0),
         NVL(r_LINK.ALCFIT,0)*100,NVL(r_LINK.ALCTOTAL,0),NVL(r_LINK.ORDLACK,0),NVL(r_LINK.WRHLACK,0),nvl(r_LINK.ordqtylack,0),nvl(r_LINK.wrhqtylack,0)
  from (select * from RPT_AlcFitDrpt where isweekavg=1) R,(SELECT FILDATE+7 FILDATE,ALCFIT,ALCTOTAL,ORDLACK,WRHLACK,ORDQTYLACK,WRHQTYLACK
    FROM RPT_AlcFitDrpt where isweekavg=1) R_LINK
        ,HDRPTCALENDAR C
   where C.fildate between vWeekBegDate and vWeekEndDate
     AND C.FILDATE = R.FILDATE (+)
     AND C.FILDATE = R_LINK.FILDATE;
*/
  --缺货占比按品项来统计
  insert into H4RTMP_AlcFitDrpt(QueryDate,FILDATE,ALCFIT,ALCTOTAL,ORDLACK,WRHLACK,SORTALACK,SORTBLACK,SORTCLACK,ISWEEKAVG,ordqtylack,wrhqtylack
                                ,ALCFIT_LINK,ALCTOTAL_LINK,ORDLACK_LINK,WRHLACK_LINK,ORDQTYLACK_LINK,WRHQTYLACK_LINK,REQTOTAL)
  select vDate,C.FILDATE,NVL(R.ALCFIT,0)*100,NVL(R.ALCTOTAL,0),NVL(R.ORDLACK,0),NVL(R.WRHLACK,0),
         NVL(R.SORTALACK,0),NVL(R.SORTBLACK,0),NVL(R.SORTCLACK,0),NVL(R.ISWEEKAVG,0),nvl(r.ordlack,0),nvl(r.wrhlack,0),
         NVL(r_LINK.ALCFIT,0)*100,NVL(r_LINK.ALCTOTAL,0),NVL(r_LINK.ORDLACK,0),NVL(r_LINK.WRHLACK,0),nvl(r_LINK.ordlack,0),nvl(r_LINK.wrhlack,0),NVL(R.REQTOTAL,0)
  from (select * from RPT_AlcFitDrpt where isweekavg<>1) R,(SELECT FILDATE+7 FILDATE,ALCFIT,ALCTOTAL,ORDLACK,WRHLACK,ORDQTYLACK,WRHQTYLACK
    FROM RPT_AlcFitDrpt where isweekavg<>1) R_LINK
        ,HDRPTCALENDAR C
   where C.fildate between vWeekBegDate and vWeekEndDate
     AND C.FILDATE = R.FILDATE (+)
     AND C.FILDATE = R_LINK.FILDATE (+);


  insert into H4RTMP_AlcFitDrpt(QueryDate,FILDATE,ALCFIT,ALCTOTAL,ORDLACK,WRHLACK,SORTALACK,SORTBLACK,SORTCLACK,ISWEEKAVG,ordqtylack,wrhqtylack
                                ,ALCFIT_LINK,ALCTOTAL_LINK,ORDLACK_LINK,WRHLACK_LINK,ORDQTYLACK_LINK,WRHQTYLACK_LINK,REQTOTAL)
  select vDate,C.FILDATE,NVL(R.ALCFIT,0)*100,NVL(R.ALCTOTAL,0),NVL(R.ORDLACK,0),NVL(R.WRHLACK,0),
         NVL(R.SORTALACK,0),NVL(R.SORTBLACK,0),NVL(R.SORTCLACK,0),NVL(R.ISWEEKAVG,0),nvl(r.ordlack,0),nvl(r.wrhlack,0),
         NVL(r_LINK.ALCFIT,0)*100,NVL(r_LINK.ALCTOTAL,0),NVL(r_LINK.ORDLACK,0),NVL(r_LINK.WRHLACK,0),nvl(r_LINK.ordlack,0),nvl(r_LINK.wrhlack,0),NVL(R.REQTOTAL,0)
  from (select * from RPT_AlcFitDrpt where isweekavg=1) R,(SELECT FILDATE+7 FILDATE,ALCFIT,ALCTOTAL,ORDLACK,WRHLACK,ORDQTYLACK,WRHQTYLACK
    FROM RPT_AlcFitDrpt where isweekavg=1) R_LINK
        ,HDRPTCALENDAR C
   where C.fildate between vWeekBegDate and vWeekEndDate
     AND C.FILDATE = R.FILDATE (+)
     AND C.FILDATE = R_LINK.FILDATE;

  commit; 

end;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>H4RTMP_AlcFitDrpt</TABLE>
    <ALIAS>H4RTMP_AlcFitDrpt</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>0</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>decode(H4RTMP_AlcFitDrpt.IsWeekAvg,1,'周汇总',to_char(H4RTMP_AlcFitDrpt.fildate,'yyyy.mm.dd'))</COLUMN>
    <TITLE>出货日期</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>fildate</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.QueryDate</COLUMN>
    <TITLE>统计日期</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>QueryDate</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>round(H4RTMP_AlcFitDrpt.REQTotal/10000,2)</COLUMN>
    <TITLE>门店需求额(万)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>REQTotal</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>round(H4RTMP_AlcFitDrpt.alcTotal/10000,2)</COLUMN>
    <TITLE>配货额(万)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>alcTotal</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.alcFit</COLUMN>
    <TITLE>配货满足率(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>alcFit</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>16711680</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>round((H4RTMP_AlcFitDrpt.REQTotal-H4RTMP_AlcFitDrpt.alcTotal)/10000,2)</COLUMN>
    <TITLE>缺货金额(万)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>lackTotal</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>decode(H4RTMP_AlcFitDrpt.alcTotal,0,0,(H4RTMP_AlcFitDrpt.REQTotal-H4RTMP_AlcFitDrpt.alcTotal)/H4RTMP_AlcFitDrpt.REQTotal)*100</COLUMN>
    <TITLE>缺货率(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>lackFit</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>16711680</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>round(H4RTMP_AlcFitDrpt.alcTotal_link/10000,2)</COLUMN>
    <TITLE>上周配货额(万)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>alcTotal_link</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.alcFit_link</COLUMN>
    <TITLE>上周配货满足率(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>alcFit_LINK</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>16711680</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.ordqtyLack*100</COLUMN>
    <TITLE>采购缺货占比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ordQTYLack</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>255</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.ordqtyLack_link*100</COLUMN>
    <TITLE>上周采购缺货占比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ordqtyLack_link</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>255</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.wrhqtyLack*100</COLUMN>
    <TITLE>拣货缺货占比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>wrhqtyLack</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>32768</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.wrhqtyLack_link*100</COLUMN>
    <TITLE>上周拣货缺货占比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>wrhqtyLack_link</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>32768</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>decode(H4RTMP_AlcFitDrpt.alctotal_link,0,0,round((H4RTMP_AlcFitDrpt.alctotal-H4RTMP_AlcFitDrpt.alctotal_LINK)/H4RTMP_AlcFitDrpt.alctotal_link,4)*100)</COLUMN>
    <TITLE>配货额环比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>alcTotal_linkrate</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>decode(H4RTMP_AlcFitDrpt.alcFit_link,0,0,round((H4RTMP_AlcFitDrpt.alcFit-H4RTMP_AlcFitDrpt.alcFit_LINK)/H4RTMP_AlcFitDrpt.alcFit_link,4)*100)</COLUMN>
    <TITLE>满足率环比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>alcFit_LINKrate</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>16711680</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>decode(H4RTMP_AlcFitDrpt.ordqtylack_link,0,0,round((H4RTMP_AlcFitDrpt.ordqtylack-H4RTMP_AlcFitDrpt.ordqtylack_LINK)/H4RTMP_AlcFitDrpt.ordqtylack_link,4)*100)</COLUMN>
    <TITLE>采购缺货环比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ordqtyLack_linkrate</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>255</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>decode(H4RTMP_AlcFitDrpt.wrhqtylack_link,0,0,round((H4RTMP_AlcFitDrpt.wrhqtylack-H4RTMP_AlcFitDrpt.wrhqtylack_LINK)/H4RTMP_AlcFitDrpt.wrhqtylack_link,4)*100)</COLUMN>
    <TITLE>拣货缺货环比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>wrhqtyLack_linkrate</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>32768</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.ordLack*100</COLUMN>
    <TITLE>采购缺货品项占比</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ordLack</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>16711680</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.ordLack_link*100</COLUMN>
    <TITLE>上周采购缺货品项占比</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ordLack_link</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>16711680</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.wrhLack*100</COLUMN>
    <TITLE>拣货缺货品项占比</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>wrhLack</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>16711680</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.wrhLack_link*100</COLUMN>
    <TITLE>上周拣货缺货品项占比</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>wrhLack_link</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>16711680</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.SortALack</COLUMN>
    <TITLE>A类品项缺货占比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SortALack</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.SortBLack</COLUMN>
    <TITLE>B类品项缺货占比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SortBLack</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_AlcFitDrpt.SortCLack</COLUMN>
    <TITLE>C类品项缺货占比(%)</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SortCLack</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>68</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>92</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>68</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>86</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>80</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>62</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>92</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>110</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>98</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>122</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>98</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>122</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>86</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>86</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>98</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>98</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>出货日期</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>H4RTMP_AlcFitDrpt.QueryDate</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2013.09.20</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>昨天</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>124</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM>2013.09.20</SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>4</NUMOFNEXTQRY>
  <NCRITERIALIST>
    <NEXTQUERY>配货缺货商品日报.sql</NEXTQUERY>
    <NCRITERIAITEM>
      <LEFT>出货日期等于</LEFT>
      <RIGHT>出货日期</RIGHT>
    </NCRITERIAITEM>
  </NCRITERIALIST>
  <NCRITERIALIST>
    <NEXTQUERY>配货数据门店日报.sql</NEXTQUERY>
    <NCRITERIAITEM>
      <LEFT>日期等于</LEFT>
      <RIGHT>出货日期</RIGHT>
    </NCRITERIAITEM>
  </NCRITERIALIST>
  <NCRITERIALIST>
    <NEXTQUERY>..\定制报表\拣货差异明细查询.sql</NEXTQUERY>
  </NCRITERIALIST>
  <NCRITERIALIST>
    <NEXTQUERY>门店叫货及实配金额查询.sql</NEXTQUERY>
  </NCRITERIALIST>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>FALSE</DXLOADMETHOD>
  <DXSHOWGROUP>FALSE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>FALSE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>FALSE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>16635360</DXCOLORODDROW>
  <DXCOLOREVENROW>16777215</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERTYPE></DXFILTERTYPE>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>0</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE>配货满足率日报</RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>13</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
  <RPTCOLUMNWIDTHITEM>76</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>86</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>110</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>86</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>98</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>86</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>96</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>122</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>98</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>98</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>122</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>98</RPTCOLUMNWIDTHITEM>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
</RPTREPORTLIST>
</SQLREPORT>

