<VERSION>4.1.1</VERSION>
<SQLQUERY>
<REMARK>
[标题]

[应用背景]

[结果列描述]

[必要的查询条件]

[实现方法]

[其它]
</REMARK>
<BEFORERUN>
DECLARE
VBDATE  DATE;
VEDATE  DATE;
VFLAG   VARCHAR2(10);

BEGIN
  VBDATE :=  TRIM('\(1,1)');
  VEDATE :=  TRIM('\(2,1)');
  VFLAG   :=  TRIM('\(3,1)');
  
  DELETE H4RTMP_STKINDVR ;
  COMMIT;
  IF VFLAG = '按记帐日期' THEN   -- 取LOG日期
    BEGIN
     -- 自营进
     INSERT INTO H4RTMP_STKINDVR(VENDORCOE,VENDORNAME,WRHCODE, WRHNAME, STKINTOTAL,STKINTAX, STKINCAMT, STKINCTAX,
     STKBCKTOTAL,STKBCKTAX, STKBCKCAMT, STKBCKCTAX, ADJTOTAL, TIME, FLAG)
     SELECT  VVENDOR.CODE ,
             VVENDOR.NAME , 
             W.CODE  WRHCODE, 
             W.NAME  WRHNAME,           
             DTL.TOTAL,
             DTL.TAX ,
             DTL.CAMT STKINCAMT,
             DTL.CTAX STKINCTAX,
             0 STKBCKTOTAL,
             0 STKBCKTAX,
             0 STKBCKCAMT,
             0 STKBCKCTAX,
             0 ADJTOTAL,
             TRUNC(LOG.TIME) TIME,
             VFLAG
        FROM STKIN        D,
             STKINDTL     DTL,
             STKINLOG LOG,
             VENDORH    VVENDOR,
             WAREHOUSE W
       WHERE D.NUM = DTL.NUM
         AND D.CLS = DTL.CLS
         AND D.NUM = LOG.NUM
         AND D.CLS = LOG.CLS
         AND DTL.WRH = W.GID
         AND D.CLS = '自营进'
         AND D.VENDOR = VVENDOR.GID
         AND LOG.STAT in (1000,1020,1040,320,340) 
         --AND D.STAT IN (1000,300)
         AND (LOG.TIME) >= VBDATE
         AND (LOG.TIME) <  VEDATE ;  
                
     -- 自营进退
     INSERT INTO H4RTMP_STKINDVR(VENDORCOE,VENDORNAME,WRHCODE, WRHNAME, STKINTOTAL,STKINTAX, STKINCAMT, STKINCTAX,
     STKBCKTOTAL,STKBCKTAX, STKBCKCAMT, STKBCKCTAX, ADJTOTAL, TIME, FLAG)
     SELECT  VVENDOR.CODE ,
             VVENDOR.NAME ,
             W.CODE  WRHCODE, 
             W.NAME  WRHNAME, 
             0 STKINTOTAL,
             0 STKINTAX,
             0 STKINCAMT,
             0 STKINCTAX,
             DTL.TOTAL,
             DTL.TAX ,
             DTL.CAMT STKBCKCAMT,
             DTL.CTAX STKBCKCTAX,
             0,
             TRUNC(LOG.TIME) TIME,
             VFLAG
        FROM STKINBCK      D,
             STKINBCKDTL     DTL,  
             STKINBCKLOG LOG,
             VENDORH    VVENDOR,
             WAREHOUSE W
       WHERE D.NUM = DTL.NUM
         AND D.CLS = DTL.CLS
         AND D.NUM = LOG.NUM
         AND D.CLS = LOG.CLS
         AND DTL.WRH = W.GID
         AND D.CLS = '自营进退'
         AND D.VENDOR = VVENDOR.GID
         AND LOG.STAT in (700,720,740,320 ,340) 
         --AND D.STAT IN (700,300)           
         AND (LOG.TIME) >= VBDATE
         AND (LOG.TIME) <  VEDATE ;         

    -- 库存价调整金额 
    INSERT INTO H4RTMP_STKINDVR(VENDORCOE,VENDORNAME,WRHCODE, WRHNAME, STKINTOTAL,STKINTAX, STKINCAMT, STKINCTAX,
     STKBCKTOTAL,STKBCKTAX, STKBCKCAMT, STKBCKCTAX, ADJTOTAL, TIME, FLAG)          
    SELECT V.CODE VDRCODE ,V.NAME VDRNAME, W.CODE WRHCODE, W.NAME WRHNAME, 0, 0, 0, 0, 0, 0, 0, 0, DTL.ADJAMT+DTL.ADJTAX, TRUNC(LOG.TIME), VFLAG
    FROM INVPRCADJBYGD D, INVPRCADJBYGDDTL DTL, INVPRCADJBYGDLOG LOG, VENDOR V, WAREHOUSE W
    WHERE D.NUM = DTL.NUM
    AND D.CLS = DTL.CLS
    AND D.NUM = LOG.NUM
    AND D.CLS = LOG.CLS
    AND D.VENDOR = V.GID
    AND DTL.WRH = W.GID
    AND LOG.TIME >= VBDATE
    AND LOG.TIME < VEDATE
    AND LOG.STAT = 100
    --AND D.STAT = 100
    AND W.GID <> 1 ; 
                                                          
    END;           
    ELSE
       BEGIN
     -- 自营进
     INSERT INTO H4RTMP_STKINDVR(VENDORCOE,VENDORNAME,WRHCODE, WRHNAME, STKINTOTAL,STKINTAX, STKINCAMT, STKINCTAX,
     STKBCKTOTAL,STKBCKTAX, STKBCKCAMT, STKBCKCTAX, ADJTOTAL, TIME, FLAG)
     SELECT  VVENDOR.CODE ,
             VVENDOR.NAME , 
             W.CODE  WRHCODE, 
             W.NAME  WRHNAME,           
             DTL.TOTAL,
             DTL.TAX ,
             DTL.CAMT STKINCAMT,
             DTL.CTAX STKINCTAX,             
             0 STKBCKTOTAL,
             0 STKBCKTAX,
             0 STKBCKCAMT,
             0 STKBCKCTAX,
             0 ADJTOTAL,
             TRUNC(D.OCRDATE) TIME,
             VFLAG
      FROM STKIN        D,
             STKINDTL     DTL,
             STKINLOG  LOG,
             VENDOR    VVENDOR,
             WAREHOUSE W
       WHERE D.NUM = DTL.NUM
         AND D.CLS = DTL.CLS
         AND D.NUM = LOG.NUM
         AND D.CLS = LOG.CLS
         AND DTL.WRH = W.GID
         AND D.CLS = '自营进'
         AND D.VENDOR = VVENDOR.GID
         AND LOG.STAT in (1000,1020,1040,320,340) 
         --AND D.STAT IN (1000,300)      
         AND (D.OCRDATE) >= VBDATE
         AND (D.OCRDATE) <  VEDATE  ; 
                
     -- 自营进退
      INSERT INTO H4RTMP_STKINDVR(VENDORCOE,VENDORNAME,WRHCODE, WRHNAME, STKINTOTAL,STKINTAX, STKINCAMT, STKINCTAX,
     STKBCKTOTAL,STKBCKTAX, STKBCKCAMT, STKBCKCTAX, ADJTOTAL, TIME, FLAG)
     SELECT  VVENDOR.CODE ,
             VVENDOR.NAME ,
             W.CODE  WRHCODE, 
             W.NAME  WRHNAME, 
             0 STKINTOTAL,
             0 STKINTAX,
             0 STKINCAMT,
             0 STKINCTAX,
             DTL.TOTAL,
             DTL.TAX ,
             DTL.CAMT STKBCKCAMT,
             DTL.CTAX STKBCKCTAX,
             0,     
             TRUNC(D.OCRDATE),
             VFLAG
        FROM STKINBCK       D,
             STKINBCKDTL     DTL,
             STKINBCKLOG LOG,
             VENDOR    VVENDOR,
             WAREHOUSE W
       WHERE D.NUM = DTL.NUM
         AND D.CLS = DTL.CLS
         AND D.NUM = LOG.NUM
         AND DTL.CLS = LOG.CLS
         AND DTL.WRH = W.GID
         AND D.CLS = '自营进退'
         AND D.VENDOR = VVENDOR.GID
         AND LOG.STAT in (700,720,740,320 ,340) 
         --AND D.STAT IN (700,300)      
         AND (D.OCRDATE) >= VBDATE
         AND (D.OCRDATE) <  VEDATE   ;       

    -- 库存价调整金额 
    INSERT INTO H4RTMP_STKINDVR(VENDORCOE,VENDORNAME,WRHCODE, WRHNAME, STKINTOTAL,STKINTAX, STKINCAMT, STKINCTAX,
     STKBCKTOTAL,STKBCKTAX, STKBCKCAMT, STKBCKCTAX, ADJTOTAL, TIME, FLAG)          
    SELECT V.CODE VDRCODE ,V.NAME VDRNAME, W.CODE WRHCODE, W.NAME WRHNAME, 0, 0, 0, 0, 0, 0, 0, 0, DTL.ADJAMT+DTL.ADJTAX, TRUNC(D.OCRDATE),VFLAG
    FROM INVPRCADJBYGD D, INVPRCADJBYGDDTL DTL, INVPRCADJBYGDLOG LOG, VENDOR V, WAREHOUSE W
    WHERE D.NUM = DTL.NUM
    AND D.CLS = DTL.CLS
    AND D.NUM = LOG.NUM
    AND D.CLS = LOG.CLS
    AND D.VENDOR = V.GID
    AND DTL.WRH = W.GID
    AND (D.OCRDATE) >= VBDATE
    AND (D.OCRDATE) <  VEDATE
    AND LOG.STAT = 100
    --AND D.STAT = 100
    AND W.GID <> 1 ; 
        
   -- COMMIT;  
    END;    
 END IF;        
END;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>H4RTMP_STKINDVR</TABLE>
    <ALIAS>H4RTMP_STKINDVR</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>0</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.VENDORCOE</COLUMN>
    <TITLE>供应商代码</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>VENDORCOE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.VENDORNAME</COLUMN>
    <TITLE>供应商名称</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>VENDORNAME</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.STKINCAMT+H4RTMP_STKINDVR.STKINCTAX</COLUMN>
    <TITLE>自营进金额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STKINTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.STKBCKTOTAL</COLUMN>
    <TITLE>自营退金额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STKBCKTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.STKINTOTAL-H4RTMP_STKINDVR.STKBCKTOTAL</COLUMN>
    <TITLE>自营进退合计发生金额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SUMTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.ADJTOTAL</COLUMN>
    <TITLE>库存价调整金额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ADJTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.TIME</COLUMN>
    <TITLE>记账日期</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>TIME</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>yyyy.mm.dd</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.FLAG</COLUMN>
    <TITLE>日期类型</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>FLAG</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.STKINCAMT+H4RTMP_STKINDVR.STKINCTAX</COLUMN>
    <TITLE>自营进含税成本</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STKINAMT</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_STKINDVR.STKBCKCAMT+H4RTMP_STKINDVR.STKBCKCTAX</COLUMN>
    <TITLE>自营退含税成本</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STKINBCKAMT</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>(H4RTMP_STKINDVR.STKINCAMT+H4RTMP_STKINDVR.STKINCTAX)-(H4RTMP_STKINDVR.STKBCKCAMT+H4RTMP_STKINDVR.STKBCKCTAX)</COLUMN>
    <TITLE>自营进退合计含税成本</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STKAMT</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>((H4RTMP_STKINDVR.STKINCAMT+H4RTMP_STKINDVR.STKINCTAX)-(H4RTMP_STKINDVR.STKBCKCAMT+H4RTMP_STKINDVR.STKBCKCTAX)) - (H4RTMP_STKINDVR.STKINTOTAL-H4RTMP_STKINDVR.STKBCKTOTAL)</COLUMN>
    <TITLE>退货差异</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STKDIF</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>93</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>133</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>133</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>102</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>126</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>64</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
  <GROUPITEM>
    <COLUMN>H4RTMP_STKINDVR.VENDORCOE</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>H4RTMP_STKINDVR.VENDORNAME</COLUMN>
  </GROUPITEM>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>供应商代码</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINDVR.TIME</LEFT>
    <OPERATOR>>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2015.05.01</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>月初</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINDVR.TIME</LEFT>
    <OPERATOR><</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2015.05.29</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>今天</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINDVR.FLAG</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>按记帐日期</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>按记帐日期</PICKNAMEITEM>
      <PICKNAMEITEM>按发生日期</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>按记帐日期</PICKVALUEITEM>
      <PICKVALUEITEM>按发生日期</PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE>按记帐日期</DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINDVR.VENDORCOE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINDVR.VENDORNAME</LEFT>
    <OPERATOR>LIKE</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>88</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM>2015.05.01</SGLINEITEM>
    <SGLINEITEM>2015.05.29</SGLINEITEM>
    <SGLINEITEM>按记帐日期</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>0</NUMOFNEXTQRY>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>FALSE</DXLOADMETHOD>
  <DXSHOWGROUP>FALSE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>FALSE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>FALSE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>15921906</DXCOLORODDROW>
  <DXCOLOREVENROW>12632256</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERTYPE></DXFILTERTYPE>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE>供应商进退货合计</RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>6</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
  <RPTCOLUMNWIDTHITEM>93</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>133</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>133</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>102</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>126</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>64</RPTCOLUMNWIDTHITEM>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
供应商进退货合计.frf
</RPTREPORTLIST>
</SQLREPORT>

