<VERSION>4.1.0</VERSION>
<SQLQUERY>
<REMARK>
[标题]

[应用背景]

[结果列描述]

[必要的查询条件]

[实现方法]

[其它]
</REMARK>
<BEFORERUN>
DECLARE
  VBDATE  DATE;
  VEDATE  DATE;
  VFLAG   VARCHAR2(20);
   
BEGIN

  VBDATE :=TRIM(TO_DATE('\(1,1)','YYYY.MM.DD'));
  VEDATE :=TRIM(TO_DATE('\(2,1)','YYYY.MM.DD'));
  VFLAG  :=TRIM('\(3,1)'); 

  DELETE FROM H4RTMP_PHMXVDR;
  COMMIT;
  
  IF VFLAG = '按记帐日期' THEN   -- 取LOG日期
    ---插入直配出数据
  INSERT INTO H4RTMP_PHMXVDR(STCODE,STNAME,VDRCODE,VDRNAME, VDRFLAG, ZPTOTAL, ZPTAX, ZPCAMT, ZPCTAX, ZPTTOTAL, ZPTTAX, ZPTCAMT, ZPTCTAX, ADJTOTAL, FILDATE, FLAG, SAMT, STAX, SCAMT, SCTAX, CLS)
    SELECT STORE.CODE, STORE.NAME, VDR.CODE, VDR.NAME, VDR.FLAG||DECODE(VDR.PAYWAYS, 0, '按发票结算', 1, '按单据结算', 2, '按销售结算', 3, '按对账结算'),   
           STKOUTDTL.TOTAL , STKOUTDTL.TAX , STKOUTDTL.CAMT, STKOUTDTL.CTAX, 0, 0, 0, 0 ,0 , TRUNC(STKOUTLOG.TIME), VFLAG,
           STKOUTDTL.SAMT, STKOUTDTL.STAX, STKOUTDTL.SCAMT, STKOUTDTL.SCTAX, STKOUT.CLS
    FROM DIRALC STKOUT, DIRALCLOG STKOUTLOG, DIRALCDTL STKOUTDTL, GOODSH GOODSH, STORE STORE, VENDOR VDR
      WHERE ((STKOUT.NUM = STKOUTDTL.NUM)
       and  (STKOUT.CLS = STKOUTDTL.CLS)
       and  (STKOUT.NUM = STKOUTLOG.NUM)
       and  (STKOUT.CLS = STKOUTLOG.CLS)
       and  (STKOUTDTL.GDGID = GOODSH.GID)
       and  (STKOUT.CLS ='直配出')
       and  (STKOUT.RECEIVER = STORE.GID)
       --and  (STKOUT.STAT = STKOUTLOG.STAT)
       and  (STKOUTLOG.STAT IN (1000, 1020, 1040, 320, 340))
       and  (STKOUTLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKOUTLOG.TIME < VEDATE OR VEDATE IS NULL) )
       AND   STKOUT.VENDOR = VDR.GID;
  COMMIT;
    ---插入直配出退数据
  INSERT INTO H4RTMP_PHMXVDR(STCODE,STNAME,VDRCODE,VDRNAME, VDRFLAG, ZPTOTAL, ZPTAX, ZPCAMT, ZPCTAX, ZPTTOTAL, ZPTTAX, ZPTCAMT, ZPTCTAX, ADJTOTAL, FILDATE, FLAG,SAMT, STAX, SCAMT, SCTAX, CLS)
    SELECT STORE.CODE, STORE.NAME, VDR.CODE, VDR.NAME, VDR.FLAG||DECODE(VDR.PAYWAYS, 0, '按发票结算', 1, '按单据结算', 2, '按销售结算', 3, '按对账结算'),   
           0, 0, 0, 0, STKOUTDTL.TOTAL , STKOUTDTL.TAX , STKOUTDTL.CAMT, STKOUTDTL.CTAX, 0, TRUNC(STKOUTLOG.TIME), VFLAG,
           STKOUTDTL.SAMT, STKOUTDTL.STAX, STKOUTDTL.SCAMT, STKOUTDTL.SCTAX, STKOUT.CLS
    FROM DIRALC STKOUT, DIRALCLOG STKOUTLOG,DIRALCDTL STKOUTDTL, STORE STORE, VENDOR VDR
      WHERE ((STKOUT.NUM = STKOUTDTL.NUM)
       and  (STKOUT.CLS = STKOUTDTL.CLS)
       and  (STKOUT.NUM = STKOUTLOG.NUM)
       and  (STKOUT.CLS = STKOUTLOG.CLS)
       and  (STKOUT.CLS ='直配出退')
       and  (STKOUT.RECEIVER = STORE.GID)
       --and  (STKOUT.STAT = STKOUTLOG.STAT)
       and  (STKOUTLOG.STAT IN (700, 720, 740, 320, 340) )
       and  (STKOUTLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKOUTLOG.TIME < VEDATE OR VEDATE IS NULL))
       AND   STKOUT.VENDOR = VDR.GID;

  -- 插入库存价调整单金额
  INSERT INTO H4RTMP_PHMXVDR(STCODE,STNAME,VDRCODE,VDRNAME, VDRFLAG, ZPTOTAL, ZPTAX, ZPCAMT, ZPCTAX, ZPTTOTAL, ZPTTAX, ZPTCAMT, ZPTCTAX, ADJTOTAL, FILDATE, FLAG, SAMT, STAX, SCAMT, SCTAX, CLS)
    SELECT S.CODE STORECODE, S.NAME STORENAME, V.CODE VDRCODE, V.NAME VDRNAME,V.FLAG||DECODE(V.PAYWAYS, 0, '按发票结算', 1, '按单据结算', 2, '按销售结算', 3, '按对账结算'),
    0, 0, 0, 0, 0, 0, 0, 0, DTL.ADJAMT+DTL.ADJTAX, TRUNC(LOG.TIME), VFLAG, 0, 0, 0, 0, D.CLS
    FROM INVPRCADJBYGD D, INVPRCADJBYGDDTL DTL, INVPRCADJBYGDLOG LOG, VENDOR V, WAREHOUSE W, STORE S
    WHERE D.NUM = DTL.NUM
    AND D.CLS = DTL.CLS
    AND D.NUM = LOG.NUM
    AND D.CLS = LOG.CLS
    AND D.VENDOR = V.GID
    AND DTL.WRH = W.GID
    AND DTL.STORE = S.GID
    AND LOG.TIME >= VBDATE
    AND LOG.TIME < VEDATE
    AND LOG.STAT = 100
    AND D.STAT = 100
    AND W.GID = 1 
    AND S.GID <> GETSTORE;        
    
  ELSE
    ---插入直配出数据
  INSERT INTO H4RTMP_PHMXVDR(STCODE,STNAME,VDRCODE,VDRNAME, VDRFLAG, ZPTOTAL, ZPTAX, ZPCAMT, ZPCTAX, ZPTTOTAL, ZPTTAX, ZPTCAMT, ZPTCTAX, ADJTOTAL, FILDATE, FLAG, SAMT, STAX, SCAMT, SCTAX, CLS)
    SELECT STORE.CODE, STORE.NAME, VDR.CODE, VDR.NAME, VDR.FLAG||DECODE(VDR.PAYWAYS, 0, '按发票结算', 1, '按单据结算', 2, '按销售结算', 3, '按对账结算'),   
           STKOUTDTL.TOTAL , STKOUTDTL.TAX , STKOUTDTL.CAMT, STKOUTDTL.CTAX, 0, 0, 0, 0, 0, TRUNC(STKOUT.OCRDATE), VFLAG,
           STKOUTDTL.SAMT, STKOUTDTL.STAX, STKOUTDTL.SCAMT, STKOUTDTL.SCTAX, STKOUT.CLS
    FROM DIRALC STKOUT, DIRALCLOG STKOUTLOG, DIRALCDTL STKOUTDTL, GOODSH GOODSH,  STORE STORE, VENDOR VDR
      WHERE ((STKOUT.NUM = STKOUTDTL.NUM)
       and  (STKOUT.CLS = STKOUTDTL.CLS)
       and  (STKOUT.NUM = STKOUTLOG.NUM)
       and  (STKOUT.CLS = STKOUTLOG.CLS)
       and  (STKOUTDTL.GDGID = GOODSH.GID)
       and  (STKOUT.CLS ='直配出')
       and  (STKOUT.RECEIVER = STORE.GID)
       --and  (STKOUT.STAT = STKOUTLOG.STAT)
       and  (STKOUTLOG.STAT IN (1000, 1020, 1040, 320, 340))
       and  (STKOUTLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKOUTLOG.TIME < VEDATE OR VEDATE IS NULL) )
       AND   STKOUT.VENDOR = VDR.GID;
  COMMIT;
    ---插入直配出退数据
  INSERT INTO H4RTMP_PHMXVDR(STCODE,STNAME,VDRCODE,VDRNAME, VDRFLAG, ZPTOTAL, ZPTAX, ZPCAMT, ZPCTAX, ZPTTOTAL, ZPTTAX, ZPTCAMT, ZPTCTAX, ADJTOTAL, FILDATE, FLAG, SAMT, STAX, SCAMT, SCTAX, CLS)
    SELECT STORE.CODE, STORE.NAME, VDR.CODE, VDR.NAME, VDR.FLAG||DECODE(VDR.PAYWAYS, 0, '按发票结算', 1, '按单据结算', 2, '按销售结算', 3, '按对账结算'),   
           0, 0, 0, 0, STKOUTDTL.TOTAL , STKOUTDTL.TAX , STKOUTDTL.CAMT, STKOUTDTL.CTAX, 0, TRUNC(STKOUT.OCRDATE), VFLAG,
           STKOUTDTL.SAMT, STKOUTDTL.STAX, STKOUTDTL.SCAMT, STKOUTDTL.SCTAX, STKOUT.CLS
    FROM DIRALC STKOUT, DIRALCLOG STKOUTLOG,DIRALCDTL STKOUTDTL,  STORE STORE, VENDOR VDR
      WHERE ((STKOUT.NUM = STKOUTDTL.NUM)
       and  (STKOUT.CLS = STKOUTDTL.CLS)
       and  (STKOUT.NUM = STKOUTLOG.NUM)
       and  (STKOUT.CLS = STKOUTLOG.CLS)
       and  (STKOUT.CLS ='直配出退')
       and  (STKOUT.RECEIVER = STORE.GID)
       --and  (STKOUT.STAT = STKOUTLOG.STAT)
       and  (STKOUTLOG.STAT IN (700, 720, 740, 320, 340) )
       and  (STKOUTLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKOUTLOG.TIME < VEDATE OR VEDATE IS NULL))
       AND   STKOUT.VENDOR = VDR.GID;

  -- 插入库存价调整单金额
  INSERT INTO H4RTMP_PHMXVDR(STCODE,STNAME,VDRCODE,VDRNAME, VDRFLAG, ZPTOTAL, ZPTAX, ZPCAMT, ZPCTAX, ZPTTOTAL, ZPTTAX, ZPTCAMT, ZPTCTAX, ADJTOTAL, FILDATE, FLAG,  SAMT, STAX, SCAMT, SCTAX,CLS)
    SELECT S.CODE STORECODE, S.NAME STORENAME, V.CODE VDRCODE, V.NAME VDRNAME, V.FLAG||DECODE(V.PAYWAYS, 0, '按发票结算', 1, '按单据结算', 2, '按销售结算', 3, '按对账结算'),
    0, 0, 0, 0, 0, 0, 0, 0, DTL.ADJAMT+DTL.ADJTAX,  TRUNC(D.OCRDATE), VFLAG, 0, 0, 0, 0, D.CLS
    FROM INVPRCADJBYGD D, INVPRCADJBYGDDTL DTL, INVPRCADJBYGDLOG LOG, VENDOR V, WAREHOUSE W, STORE S
    WHERE D.NUM = DTL.NUM
    AND D.CLS = DTL.CLS
    AND D.NUM = LOG.NUM
    AND D.CLS = LOG.CLS
    AND D.VENDOR = V.GID
    AND DTL.WRH = W.GID
    AND DTL.STORE = S.GID
    AND D.OCRDATE >= VBDATE
    AND D.OCRDATE < VEDATE
    AND LOG.STAT = 100
    AND D.STAT = 100
    AND W.GID = 1 
    AND S.GID <> GETSTORE;       
                      
  COMMIT;
  END IF;
END;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>H4RTMP_PHMXVDR</TABLE>
    <ALIAS>H4RTMP_PHMXVDR</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>0</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.STCODE</COLUMN>
    <TITLE>门店代码</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STCODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.STNAME</COLUMN>
    <TITLE>门店名称</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STNAME</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.VDRCODE</COLUMN>
    <TITLE>供应商代码</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>VDRCODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.VDRNAME</COLUMN>
    <TITLE>供应商名称</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>VDRNAME</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.VDRFLAG</COLUMN>
    <TITLE>供应商类型</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>VDRFLAG</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.ZPTOTAL-H4RTMP_PHMXVDR.ZPTTOTAL</COLUMN>
    <TITLE>直配出/退合计金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SUMTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.ADJTOTAL</COLUMN>
    <TITLE>库存价调整金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ADJTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.FILDATE</COLUMN>
    <TITLE>记账日期</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>FILDATE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.FLAG</COLUMN>
    <TITLE>日期类型</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>FLAG</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.ZPCAMT+H4RTMP_PHMXVDR.ZPCTAX</COLUMN>
    <TITLE>直配含税成本额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ZPAMTTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_PHMXVDR.ZPTCAMT+H4RTMP_PHMXVDR.ZPTCTAX</COLUMN>
    <TITLE>直配退含税成本额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ZPTCAMTTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>(H4RTMP_PHMXVDR.ZPCAMT+H4RTMP_PHMXVDR.ZPCTAX)-(H4RTMP_PHMXVDR.ZPTCAMT+H4RTMP_PHMXVDR.ZPTCTAX)</COLUMN>
    <TITLE>直配出/退合计含税成本额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>AMTTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>(H4RTMP_PHMXVDR.ZPTOTAL-H4RTMP_PHMXVDR.ZPTTOTAL)-((H4RTMP_PHMXVDR.ZPCAMT+H4RTMP_PHMXVDR.ZPCTAX)-(H4RTMP_PHMXVDR.ZPTCAMT+H4RTMP_PHMXVDR.ZPTCTAX))</COLUMN>
    <TITLE>直配毛利</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ZPML</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'直配出',1,'直配出退',-1,1)*(H4RTMP_PHMXVDR.SAMT +H4RTMP_PHMXVDR.STAX)</COLUMN>
    <TITLE>直配出/退门店合计发生额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SAMTTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'直配出',1,'直配出退',-1,1)*(H4RTMP_PHMXVDR.SCAMT +H4RTMP_PHMXVDR.SCTAX)</COLUMN>
    <TITLE>直配出/退门店成本额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SCAMTTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'直配出',1,'直配出退',-1,1)*(H4RTMP_PHMXVDR.SCAMT +H4RTMP_PHMXVDR.SCTAX)-decode(cls,'直配出',1,'直配出退',-1,1)*(H4RTMP_PHMXVDR.SAMT +H4RTMP_PHMXVDR.STAX)</COLUMN>
    <TITLE>门店发生与成本差异额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>DIFTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'直配出',1,'直配出退',-1,1)*(H4RTMP_PHMXVDR.SCAMT +H4RTMP_PHMXVDR.SCTAX)-(H4RTMP_PHMXVDR.ZPTOTAL-H4RTMP_PHMXVDR.ZPTTOTAL)</COLUMN>
    <TITLE>门店成本与总部发生差异</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>DIFAMTTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>52</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>91</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>102</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>168</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>107</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>122</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>126</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>121</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>95</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>118</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>167</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>161</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>138</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
  <GROUPITEM>
    <COLUMN>H4RTMP_PHMXVDR.STCODE</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>H4RTMP_PHMXVDR.STNAME</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>H4RTMP_PHMXVDR.VDRCODE</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>H4RTMP_PHMXVDR.VDRNAME</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>H4RTMP_PHMXVDR.VDRFLAG</COLUMN>
  </GROUPITEM>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>供应商类型</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>H4RTMP_PHMXVDR.FILDATE</LEFT>
    <OPERATOR>>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2011.01.13</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>月初</DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_PHMXVDR.FILDATE</LEFT>
    <OPERATOR><</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2011.01.16</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>昨天</DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_PHMXVDR.FLAG</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>按记帐日期</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>按记帐日期</PICKNAMEITEM>
      <PICKNAMEITEM>按发生日期</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>按记帐日期</PICKVALUEITEM>
      <PICKVALUEITEM>按发生日期</PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_PHMXVDR.STCODE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>#TABLE</PICKNAMEITEM>
      <PICKNAMEITEM>'['||CODE||']'||NAME</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>SELECT CODE, '['||CODE||']'||NAME FROM STORE WHERE CODE <> '9267' ORDER BY CODE</PICKVALUEITEM>
      <PICKVALUEITEM>CODE</PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_PHMXVDR.VDRCODE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_PHMXVDR.VDRNAME</LEFT>
    <OPERATOR>LIKE</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>106</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>94</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>108</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>88</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM>2011.01.13</SGLINEITEM>
    <SGLINEITEM>2011.01.16</SGLINEITEM>
    <SGLINEITEM>按记帐日期</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>0</NUMOFNEXTQRY>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>TRUE</DXLOADMETHOD>
  <DXSHOWGROUP>TRUE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>TRUE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>TRUE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>15921906</DXCOLORODDROW>
  <DXCOLOREVENROW>12632256</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE>供应商直配合计</RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>12</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
  <RPTCOLUMNWIDTHITEM>52</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>91</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>102</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>168</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>107</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>122</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>126</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>121</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>95</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>118</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>167</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>161</RPTCOLUMNWIDTHITEM>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
供应商直配合计_含成本
供应商直配合计
</RPTREPORTLIST>
</SQLREPORT>

