<VERSION>4.1.0</VERSION>
<SQLQUERY>
<REMARK>
[标题]
  入库单明细查询汇总(门店视角)
[应用背景]
  可以用于以下场景:
   1)某个商品在某段时间被哪些配货及退货单据进行了引用,此配货单必须是影响了业务库存的单据
   2)某张单据的单据明细,主要包含商品,发生额,成本额

[结果列描述]
  
[必要的查询条件]
  支持
[实现方法]
[版本]
CREATED BY fengchunliang 2010-4-25 16:10:50

[其它]
</REMARK>
<BEFORERUN>
DECLARE
  VBDATE  DATE;
  VEDATE  DATE;
  VSTORECODEB  VARCHAR2(20);
  VSTORECODEE  VARCHAR2(20);
  VSTATNAME VARCHAR2(200);
  VFILTER1 VARCHAR2(1000);
BEGIN

  VBDATE :=TO_DATE('\(1,1)','YYYY.MM.DD');
  VEDATE :=TO_DATE('\(2,1)','YYYY.MM.DD');
  VSTORECODEB:=TRIM('\(3,1)');
  VSTORECODEE:=TRIM('\(4,1)');
 -- VSTATNAME :=TRIM('\(5,1)');

  DELETE FROM H4RTMP_PHMX;
  COMMIT;
    ---插入统配出数据
  INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE, SAMT, STAX, SCAMT, SCTAX)
    SELECT STKOUT.NUM , STKOUT.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      STORE.NAME , STKOUTDTL.QTY , STKOUTDTL.QTYSTR , 
      STKOUTDTL.PRICE , STKOUTDTL.TOTAL , STKOUTDTL.TAX , STKOUTDTL.CAMT , 
      STKOUTDTL.CTAX , STKOUTDTL.CRTOTAL , MODULESTAT.STATNAME,STKOUTLOG.TIME,STKOUTDTL.LINE,STORE.CODE,
      STKOUTDTL.SAMT, STKOUTDTL.STAX, STKOUTDTL.SCAMT, STKOUTDTL.SCTAX
    FROM STKOUT STKOUT, STKOUTLOG STKOUTLOG, STKOUTDTL STKOUTDTL, GOODSH GOODSH, MODULESTAT MODULESTAT, STORE STORE
      WHERE ((STKOUT.NUM = STKOUTDTL.NUM)
       and  (STKOUT.CLS = STKOUTDTL.CLS)
       and  (STKOUT.NUM = STKOUTLOG.NUM)
       and  (STKOUT.CLS = STKOUTLOG.CLS)
       and  (STKOUT.STAT = MODULESTAT.NO)
       and  (STKOUTDTL.GDGID = GOODSH.GID)
       and  (STKOUT.CLS ='统配出')
       and  (STKOUT.BILLTO = STORE.GID)
       --and  (STKOUT.STAT = STKOUTLOG.STAT)
       and  (STKOUTLOG.STAT IN(700, 720, 740, 320, 340))
       and  (STKOUTLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKOUTLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (STORE.CODE >= VSTORECODEB OR VSTORECODEB IS NULL)
       and  (STORE.CODE <= VSTORECODEE OR VSTORECODEE IS NULL));
  COMMIT;
    ---插入统配出退数据
  INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE, SAMT, STAX, SCAMT, SCTAX)
    SELECT STKOUT.NUM , STKOUT.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      STORE.NAME , STKOUTDTL.QTY , STKOUTDTL.QTYSTR , 
      STKOUTDTL.PRICE , STKOUTDTL.TOTAL , STKOUTDTL.TAX , STKOUTDTL.CAMT , 
      STKOUTDTL.CTAX , STKOUTDTL.CRTOTAL , MODULESTAT.STATNAME,STKOUTLOG.TIME,STKOUTDTL.LINE,STORE.CODE,
      STKOUTDTL.SAMT, STKOUTDTL.STAX, STKOUTDTL.SCAMT, STKOUTDTL.SCTAX
    FROM STKOUTBCK STKOUT, STKOUTBCKLOG STKOUTLOG, STKOUTBCKDTL STKOUTDTL, GOODSH GOODSH, MODULESTAT MODULESTAT, STORE STORE
      WHERE ((STKOUT.NUM = STKOUTDTL.NUM)
       and  (STKOUT.CLS = STKOUTDTL.CLS)
       and  (STKOUT.NUM = STKOUTLOG.NUM)
       and  (STKOUT.CLS = STKOUTLOG.CLS)
       and  (STKOUT.STAT = MODULESTAT.NO)
       and  (STKOUTDTL.GDGID = GOODSH.GID)
       and  (STKOUT.CLS ='统配出退')
       and  (STKOUT.BILLTO = STORE.GID)
       --and  (STKOUT.STAT = STKOUTLOG.STAT)
       and  (STKOUTLOG.STAT IN (1000, 1020, 1040, 320, 340) )
       and  (STKOUTLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKOUTLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (STORE.CODE >= VSTORECODEB OR VSTORECODEB IS NULL)
       and  (STORE.CODE <= VSTORECODEE OR VSTORECODEE IS NULL));
  
-- 插入统配差异
  INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE, SAMT, STAX, SCAMT, SCTAX)
    SELECT STKOUT.NUM , STKOUT.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      STORE.NAME , STKOUTDTL.QTY , STKOUTDTL.CASES , 
      STKOUTDTL.PRICE , STKOUTDTL.TOTAL , STKOUTDTL.TAX , STKOUTDTL.CAMT , 
      STKOUTDTL.CTAX , STKOUTDTL.CRTOTAL , MODULESTAT.STATNAME,STKOUTLOG.TIME,STKOUTDTL.LINE,STORE.CODE,
      STKOUTDTL.SAMT, STKOUTDTL.STAX, STKOUTDTL.SCAMT, STKOUTDTL.SCTAX
    FROM ALCDIFF STKOUT, ALCDIFFLOG STKOUTLOG, ALCDIFFDTL STKOUTDTL, GOODSH GOODSH, MODULESTAT MODULESTAT, STORE STORE
      WHERE ((STKOUT.NUM = STKOUTDTL.NUM)
       and  (STKOUT.CLS = STKOUTDTL.CLS)
       and  (STKOUT.NUM = STKOUTLOG.NUM)
       and  (STKOUT.CLS = STKOUTLOG.CLS)
       and  (STKOUT.STAT = MODULESTAT.NO)
       and  (STKOUTDTL.GDGID = GOODSH.GID)
       and  (STKOUT.CLS ='配货差异')
       and  (STKOUT.BILLTO = STORE.GID)
       --and  (STKOUT.STAT = STKOUTLOG.STAT)
       and  (STKOUTLOG.STAT IN (400,420,440) )
       and  (STKOUTLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKOUTLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (STORE.CODE >= VSTORECODEB OR VSTORECODEB IS NULL)
       and  (STORE.CODE <= VSTORECODEE OR VSTORECODEE IS NULL));
  COMMIT;
END;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>H4RTMP_PHMX</TABLE>
    <ALIAS>H4RTMP_PHMX</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD>123</INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>3</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>STCODE</COLUMN>
    <TITLE>门店代码</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STCODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>stname</COLUMN>
    <TITLE>门店名称</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>stname</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'统配差异',1,1)*total</COLUMN>
    <TITLE>配货含税金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>total</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>fildate</COLUMN>
    <TITLE>收发货操作时间</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>fildate</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'统配差异',1,1)*(CAMT+CTAX)</COLUMN>
    <TITLE>配货含税成本额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>AMTTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'统配差异',1,1)*(TOTAL-(CAMT+CTAX))</COLUMN>
    <TITLE>配货毛利</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ALCML</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'统配差异',1,1)*(H4RTMP_PHMX.SAMT +H4RTMP_PHMX.STAX)</COLUMN>
    <TITLE>门店发生含税金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SAMTTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'统配差异',1,1)*(H4RTMP_PHMX.SCAMT +H4RTMP_PHMX.SCTAX)</COLUMN>
    <TITLE>门店含税成本额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SCAMTTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>decode(cls,'统配出',1,'统配出退',-1,'统配差异',1,1)*(H4RTMP_PHMX.SCAMT +H4RTMP_PHMX.SCTAX)-decode(cls,'统配出',1,'统配出退',-1,'统配差异',1,1)*(H4RTMP_PHMX.SAMT +H4RTMP_PHMX.STAX)</COLUMN>
    <TITLE>门店发生与成本差异额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>DIFML</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>165</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>97</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>113</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>104</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>74</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>109</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>108</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>68</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
  <GROUPITEM>
    <COLUMN>STCODE</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>stname</COLUMN>
  </GROUPITEM>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>门店代码</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>fildate</LEFT>
    <OPERATOR>>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>月初</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>fildate</LEFT>
    <OPERATOR><</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>今天</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>STCODE</LEFT>
    <OPERATOR>>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>STCODE</LEFT>
    <OPERATOR><=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>STCODE</LEFT>
    <OPERATOR>IN</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>151</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>122</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>170</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>153</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>160</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>0</NUMOFNEXTQRY>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>TRUE</DXLOADMETHOD>
  <DXSHOWGROUP>TRUE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>TRUE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>TRUE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>16777215</DXCOLORODDROW>
  <DXCOLOREVENROW>15921906</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE>仓库配货合计_20110105增加门店成本</RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>8</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
  <RPTCOLUMNWIDTHITEM>43</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>97</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>113</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>104</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>74</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>109</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>108</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
仓库配货合计
仓库配货合计_含门店成本
</RPTREPORTLIST>
</SQLREPORT>

