apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  name: monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- namespace: monitoring
  kind: ServiceAccount
  name: monitor
