apiVersion: v1
kind: Service
metadata:
  name: k8s-etcd
  namespace: kube-system
  labels:
    k8s-component: etcd
    component.kubernetes.io/name: etcd
spec:
  type: ClusterIP
  clusterIP: None 
  ports:
  - name: port
    port: 2379          
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-etcd
  namespace: kube-system
  labels:
    k8s-component: etcd
subsets:
- addresses:
  - ip: 192.168.13.31
  - ip: 192.168.13.32
  - ip: 192.168.13.33
  ports:
  - port: 2379
