
--修改机场信息
select Code,Name,EnglishName from homsomDB..Trv_Airport 
update homsomDB..Trv_Airport  set  EnglishName='Aba Hongyuan Airport' where Code='AHJ' and Name='阿坝红原机场'
update homsomDB..Trv_Airport  set  EnglishName='Akesu Airport' where Code='AKU' and Name='阿克苏机场'
update homsomDB..Trv_Airport  set  EnglishName='Alashanyouqi Airport' where Code='RHT' and Name='阿拉善右旗机场'
update homsomDB..Trv_Airport  set  EnglishName='Alashanzuoqi Airport' where Code='AXF' and Name='阿拉善左旗机场'
update homsomDB..Trv_Airport  set  EnglishName='Aletai Airport' where Code='AAT' and Name='阿勒泰机场'
update homsomDB..Trv_Airport  set  EnglishName='Alikunsha Airport' where Code='NGQ' and Name='阿里昆莎机场'
update homsomDB..Trv_Airport  set  EnglishName='Bailian Airport' where Code='LZH' and Name='白莲机场'
update homsomDB..Trv_Airport  set  EnglishName='Baitabu Airport' where Code='LYG' and Name='白塔埠机场'
update homsomDB..Trv_Airport  set  EnglishName='Baita International Airport' where Code='HET' and Name='白塔国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Baiyun International Airport' where Code='CAN' and Name='白云国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Baise Airport' where Code='AEB' and Name='百色机场'
update homsomDB..Trv_Airport  set  EnglishName='Bangda Airport' where Code='BPX' and Name='邦达机场'
update homsomDB..Trv_Airport  set  EnglishName='Baoan International Airport' where Code='SZX' and Name='宝安国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Baoanying Airport' where Code='PZI' and Name='保安营机场'
update homsomDB..Trv_Airport  set  EnglishName='Baoshan Airport' where Code='BSD' and Name='保山机场'
update homsomDB..Trv_Airport  set  EnglishName='Beidaihe Airport' where Code='BPE' and Name='北戴河机场'
update homsomDB..Trv_Airport  set  EnglishName='Beijiao Airport' where Code='LYA' and Name='北郊机场'
update homsomDB..Trv_Airport  set  EnglishName='Benniu Airport' where Code='CZX' and Name='奔牛机场'
update homsomDB..Trv_Airport  set  EnglishName='Binhai International Airport' where Code='TSN' and Name='滨海国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Boao Airport' where Code='BAR' and Name='博鳌机场'
update homsomDB..Trv_Airport  set  EnglishName='Bole Airport' where Code='BPL' and Name='博乐机场'
update homsomDB..Trv_Airport  set  EnglishName='Caiba Airport' where Code='YBP' and Name='菜坝机场'
update homsomDB..Trv_Airport  set  EnglishName='Caojiabao Airport' where Code='XNN' and Name='曹家堡机场'
update homsomDB..Trv_Airport  set  EnglishName='Chaganhu Airport' where Code='YSQ' and Name='查干湖机场'
update homsomDB..Trv_Airport  set  EnglishName='Changbei International Airport' where Code='KHN' and Name='昌北国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Changan Airport' where Code='DBC' and Name='长安机场'
update homsomDB..Trv_Airport  set  EnglishName='Changbaishan Airport' where Code='NBS' and Name='长白山机场'
update homsomDB..Trv_Airport  set  EnglishName='Changle International Airport' where Code='FOC' and Name='长乐国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Changshui International Airport' where Code='KMG' and Name='长水国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Changzhi Airport' where Code='CIH' and Name='长治机场'
update homsomDB..Trv_Airport  set  EnglishName='Changzhoudao Airport' where Code='WUZ' and Name='长洲岛机场'
update homsomDB..Trv_Airport  set  EnglishName='Chaoyangchuan Airport' where Code='YNJ' and Name='朝阳川机场'
update homsomDB..Trv_Airport  set  EnglishName='Chaoyang Airport' where Code='CHG' and Name='朝阳机场'
update homsomDB..Trv_Airport  set  EnglishName='Chaoshan Airport' where Code='SWA' and Name='潮汕机场'
update homsomDB..Trv_Airport  set  EnglishName='Chaoshan Airport' where Code='SWA' and Name='潮汕机场'
update homsomDB..Trv_Airport  set  EnglishName='Chaoshan Airport' where Code='SWA' and Name='潮汕机场'
update homsomDB..Trv_Airport  set  EnglishName='Chaoshan Airport' where Code='SWA' and Name='潮汕机场'
update homsomDB..Trv_Airport  set  EnglishName='Chengjisihan Airport' where Code='NZL' and Name='成吉思汗机场'
update homsomDB..Trv_Airport  set  EnglishName='Chengxian Airport' where Code='LNL' and Name='成县机场'
update homsomDB..Trv_Airport  set  EnglishName='Chenggu Airport' where Code='HZG' and Name='城固机场'
update homsomDB..Trv_Airport  set  EnglishName='Dali Airport' where Code='DLU' and Name='大理机场'
update homsomDB..Trv_Airport  set  EnglishName='Dashuibo Airport' where Code='WEH' and Name='大水泊机场'
update homsomDB..Trv_Airport  set  EnglishName='Dehongmangshi Airport' where Code='LUM' and Name='德宏芒市机场'
update homsomDB..Trv_Airport  set  EnglishName='Dehongmangshi Airport' where Code='LUM' and Name='德宏芒市机场'
update homsomDB..Trv_Airport  set  EnglishName='Delingha Airport' where Code='HXD' and Name='德令哈机场'
update homsomDB..Trv_Airport  set  EnglishName='Diwobao International Airport' where Code='URC' and Name='地窝堡国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Dongji Airport' where Code='FYJ' and Name='东极机场'
update homsomDB..Trv_Airport  set  EnglishName='Dongjiao Airport' where Code='JMU' and Name='东郊机场'
update homsomDB..Trv_Airport  set  EnglishName='Dongshan Airport' where Code='HLD' and Name='东山机场'
update homsomDB..Trv_Airport  set  EnglishName='Dunhuang Airport' where Code='DNH' and Name='敦煌机场'
update homsomDB..Trv_Airport  set  EnglishName='Erliban Airport' where Code='BAV' and Name='二里半机场'
update homsomDB..Trv_Airport  set  EnglishName='Feixiong Airport' where Code='BFJ' and Name='飞雄机场'
update homsomDB..Trv_Airport  set  EnglishName='Phoenix International Airport' where Code='SYX' and Name='凤凰国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Fucheng Airport' where Code='BHY' and Name='福成机场'
update homsomDB..Trv_Airport  set  EnglishName='Fuyun Airport' where Code='FYN' and Name='富蕴机场'
update homsomDB..Trv_Airport  set  EnglishName='Gasa International Airport' where Code='JHG' and Name='嘎洒国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Gasa International Airport' where Code='JHG' and Name='嘎洒国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Ganzhou Airport' where Code='YZY' and Name='甘州机场'
update homsomDB..Trv_Airport  set  EnglishName='Gaoping Airport' where Code='NAO' and Name='高坪机场'
update homsomDB..Trv_Airport  set  EnglishName='Gaoqi International Airport' where Code='XMN' and Name='高崎国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Golmud Airport' where Code='GOQ' and Name='格尔木机场'
update homsomDB..Trv_Airport  set  EnglishName='Gongar International Airport' where Code='LXA' and Name='贡嘎国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Guangong Airport' where Code='YCU' and Name='关公机场'
update homsomDB..Trv_Airport  set  EnglishName='Guanyin Airport' where Code='XUZ' and Name='观音机场'
update homsomDB..Trv_Airport  set  EnglishName='Guanzhishan Airport' where Code='LCX' and Name='冠豸山机场'
update homsomDB..Trv_Airport  set  EnglishName='Qiuci Airport' where Code='KCA' and Name='龟兹机场'
update homsomDB..Trv_Airport  set  EnglishName='Hami Airport' where Code='HMI' and Name='哈密机场'
update homsomDB..Trv_Airport  set  EnglishName='Haibei Airport' where Code='HBQ' and Name='海北机场'
update homsomDB..Trv_Airport  set  EnglishName='Hailang Airport' where Code='MDG' and Name='海浪机场'
update homsomDB..Trv_Airport  set  EnglishName='Handan Airport' where Code='HDG' and Name='邯郸机场'
update homsomDB..Trv_Airport  set  EnglishName='Shigatse Peace Airport' where Code='RKZ' and Name='和平机场'
update homsomDB..Trv_Airport  set  EnglishName='Hotan Airport' where Code='HTN' and Name='和田机场'
update homsomDB..Trv_Airport  set  EnglishName='Hedong Airport' where Code='INC' and Name='河东机场'
update homsomDB..Trv_Airport  set  EnglishName='Heshi Airport' where Code='DAX' and Name='河市机场'
update homsomDB..Trv_Airport  set  EnglishName='Heshi Airport' where Code='DAX' and Name='河市机场'
update homsomDB..Trv_Airport  set  EnglishName='Hehua Airport' where Code='DYG' and Name='荷花机场'
update homsomDB..Trv_Airport  set  EnglishName='Heihe Airport' where Code='HEK' and Name='黑河机场'
update homsomDB..Trv_Airport  set  EnglishName='Hongping Airport' where Code='HPG' and Name='红坪机场'
update homsomDB..Trv_Airport  set  EnglishName='Hongqiao International Airport' where Code='SHA' and Name='虹桥国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Huatugou Airport' where Code='HTT' and Name='花土沟机场'
update homsomDB..Trv_Airport  set  EnglishName='Huayuan Airport' where Code='SHF' and Name='花园机场'
update homsomDB..Trv_Airport  set  EnglishName='Huangguoshu Airport' where Code='AVA' and Name='黄果树机场'
update homsomDB..Trv_Airport  set  EnglishName='Huanghua International Airport' where Code='CSX' and Name='黄花国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Huangjin Airport' where Code='KOW' and Name='黄金机场'
update homsomDB..Trv_Airport  set  EnglishName='Huanglong Airport' where Code='JZH' and Name='黄龙机场'
update homsomDB..Trv_Airport  set  EnglishName='Huangping Airport' where Code='KJH' and Name='黄平机场'
update homsomDB..Trv_Airport  set  EnglishName='Huolinhe Airport' where Code='HUO' and Name='霍林河机场'
update homsomDB..Trv_Airport  set  EnglishName='Jiagedaqi Airport' where Code='JGD' and Name='加格达奇机场'
update homsomDB..Trv_Airport  set  EnglishName='Jiayuguan Airport' where Code='JGN' and Name='嘉峪关机场'
update homsomDB..Trv_Airport  set  EnglishName='Jiansanjiang Airport' where Code='JSJ' and Name='建三江机场'
update homsomDB..Trv_Airport  set  EnglishName='Jiangying Airport' where Code='NNY' and Name='姜营机场'
update homsomDB..Trv_Airport  set  EnglishName='Jiaohe Airport' where Code='TLQ' and Name='交河机场'
update homsomDB..Trv_Airport  set  EnglishName='Jinchengjiang Airport' where Code='HCJ' and Name='金城江机场'
update homsomDB..Trv_Airport  set  EnglishName='Jinchuan Airport' where Code='JIC' and Name='金川机场'
update homsomDB..Trv_Airport  set  EnglishName='Jinwan Airport' where Code='ZUH' and Name='金湾机场'
update homsomDB..Trv_Airport  set  EnglishName='Jinzhouwan Airport' where Code='JNZ' and Name='锦州湾机场'
update homsomDB..Trv_Airport  set  EnglishName='Jinjiang Airport' where Code='JJN' and Name='晋江机场'
update homsomDB..Trv_Airport  set  EnglishName='Jinjiang Airport' where Code='JJN' and Name='晋江机场'
update homsomDB..Trv_Airport  set  EnglishName='Jinggangshan Airport' where Code='JGS' and Name='井冈山机场'
update homsomDB..Trv_Airport  set  EnglishName='Jingdezhen Airport' where Code='JDZ' and Name='景德镇机场'
update homsomDB..Trv_Airport  set  EnglishName='Jingmai Airport' where Code='JMJ' and Name='景迈机场'
update homsomDB..Trv_Airport  set  EnglishName='Jiuhuashan Airport' where Code='JUH' and Name='九华山机场'
update homsomDB..Trv_Airport  set  EnglishName='Kanas Airport' where Code='KJI' and Name='喀纳斯机场'
update homsomDB..Trv_Airport  set  EnglishName='Kashi Airport' where Code='KHG' and Name='喀什机场'
update homsomDB..Trv_Airport  set  EnglishName='Kangding Airport' where Code='KGT' and Name='康定机场'
update homsomDB..Trv_Airport  set  EnglishName='Karamay Airport' where Code='KRY' and Name='克拉玛依机场'
update homsomDB..Trv_Airport  set  EnglishName='Korla Airport' where Code='KRL' and Name='库尔勒机场'
update homsomDB..Trv_Airport  set  EnglishName='Lanqi Airport' where Code='YKH' and Name='兰旗机场'
update homsomDB..Trv_Airport  set  EnglishName='Langtou Airport' where Code='DDG' and Name='浪头机场'
update homsomDB..Trv_Airport  set  EnglishName='Liping Airport' where Code='HZH' and Name='黎平机场'
update homsomDB..Trv_Airport  set  EnglishName='Lishe International Airport' where Code='NGB' and Name='栎社国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Libo Airport' where Code='LLB' and Name='荔波机场'
update homsomDB..Trv_Airport  set  EnglishName='Lianshui Airport' where Code='HIA' and Name='涟水机场'
update homsomDB..Trv_Airport  set  EnglishName='Liangjiang International Airport' where Code='KWL' and Name='两江国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Lindu Airport' where Code='LDS' and Name='林都机场'
update homsomDB..Trv_Airport  set  EnglishName='Lincang Airport' where Code='LNJ' and Name='临沧机场'
update homsomDB..Trv_Airport  set  EnglishName='Lingling Airport' where Code='LLF' and Name='零陵机场'
update homsomDB..Trv_Airport  set  EnglishName='Liuji Airport' where Code='XFN' and Name='刘集机场'
update homsomDB..Trv_Airport  set  EnglishName='Liuting International Airport' where Code='TAO' and Name='流亭国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Liupanshan Airport' where Code='GYU' and Name='六盘山机场'
update homsomDB..Trv_Airport  set  EnglishName='Longdongbao International Airport' where Code='KWE' and Name='龙洞堡国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Longjia International Airport' where Code='CGQ' and Name='龙嘉国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Longwan International Airport' where Code='WNZ' and Name='龙湾国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Loulan Airport' where Code='RQA' and Name='楼兰机场'
update homsomDB..Trv_Airport  set  EnglishName='Lushan Airport' where Code='JIU' and Name='庐山机场'
update homsomDB..Trv_Airport  set  EnglishName='Luguhu Airport' where Code='NLH' and Name='泸沽湖机场'
update homsomDB..Trv_Airport  set  EnglishName='Lukou International Airport' where Code='NKG' and Name='禄口国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Luqiao Airport' where Code='HYN' and Name='路桥机场'
update homsomDB..Trv_Airport  set  EnglishName='Lvliang Airport' where Code='LLV' and Name='吕梁机场'
update homsomDB..Trv_Airport  set  EnglishName='Maqin Airport' where Code='GMQ' and Name='玛沁机场'
update homsomDB..Trv_Airport  set  EnglishName='Maijishan Airport' where Code='THQ' and Name='麦积山机场'
update homsomDB..Trv_Airport  set  EnglishName='Maotai Airport' where Code='WMT' and Name='茅台机场'
update homsomDB..Trv_Airport  set  EnglishName='Meixian Airport' where Code='MXZ' and Name='梅县机场'
update homsomDB..Trv_Airport  set  EnglishName='Meilan International Airport' where Code='HAK' and Name='美兰国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Milin Airport' where Code='LZY' and Name='米林机场'
update homsomDB..Trv_Airport  set  EnglishName='Minggang Airport' where Code='XAI' and Name='明港机场'
update homsomDB..Trv_Airport  set  EnglishName='Mingyueshan Airport' where Code='YIC' and Name='明月山机场'
update homsomDB..Trv_Airport  set  EnglishName='Mohe Airport' where Code='OHE' and Name='漠河机场'
update homsomDB..Trv_Airport  set  EnglishName='Nalati Airport' where Code='NLT' and Name='那拉提机场'
update homsomDB..Trv_Airport  set  EnglishName='Nangan Airport' where Code='LZN' and Name='南竿机场'
update homsomDB..Trv_Airport  set  EnglishName='Nanjiao Airport' where Code='MIG' and Name='南郊机场'
update homsomDB..Trv_Airport  set  EnglishName='Nanniwan Airport' where Code='ENY' and Name='南泥湾机场'
update homsomDB..Trv_Airport  set  EnglishName='Nanyang Airport' where Code='YNZ' and Name='南洋机场'
update homsomDB..Trv_Airport  set  EnglishName='Nanyuan Airport' where Code='NAY' and Name='南苑机场'
update homsomDB..Trv_Airport  set  EnglishName='Nanyue Airport' where Code='HNY' and Name='南岳机场'
update homsomDB..Trv_Airport  set  EnglishName='Panlong Airport' where Code='GYS' and Name='盘龙机场'
update homsomDB..Trv_Airport  set  EnglishName='Penglai International Airport' where Code='YNT' and Name='蓬莱国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Pingtan Airport' where Code='HUZ' and Name='平潭机场'
update homsomDB..Trv_Airport  set  EnglishName='Pudong International Airport' where Code='PVG' and Name='浦东国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Puning Airport' where Code='CDE' and Name='普宁机场'
update homsomDB..Trv_Airport  set  EnglishName='Putuoshan Airport' where Code='HSN' and Name='普陀山机场'
update homsomDB..Trv_Airport  set  EnglishName='Qiaoli Airport' where Code='LFQ' and Name='乔李机场'
update homsomDB..Trv_Airport  set  EnglishName='Qiemo Airport' where Code='IQM' and Name='且末机场'
update homsomDB..Trv_Airport  set  EnglishName='Qingshan Airport' where Code='XIC' and Name='青山机场'
update homsomDB..Trv_Airport  set  EnglishName='Qingyang Airport' where Code='IQN' and Name='庆阳机场'
update homsomDB..Trv_Airport  set  EnglishName='Qufu Airport' where Code='JNG' and Name='曲阜机场'
update homsomDB..Trv_Airport  set  EnglishName='Quzhou Airport' where Code='JUZ' and Name='衢州机场'
update homsomDB..Trv_Airport  set  EnglishName='Saertu Airport' where Code='DQA' and Name='萨尔图机场'
update homsomDB..Trv_Airport  set  EnglishName='Saiwusu International Airport' where Code='ERL' and Name='赛乌苏国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Sanhe Airport' where Code='YYA' and Name='三荷机场'
update homsomDB..Trv_Airport  set  EnglishName='Sanjiazi Airport' where Code='NDG' and Name='三家子机场'
update homsomDB..Trv_Airport  set  EnglishName='Sannvhe Airport' where Code='TVS' and Name='三女河机场'
update homsomDB..Trv_Airport  set  EnglishName='Sanqingshan Airport' where Code='SQD' and Name='三清山机场'
update homsomDB..Trv_Airport  set  EnglishName='Sanxia Airport' where Code='YIH' and Name='三峡机场'
update homsomDB..Trv_Airport  set  EnglishName='Sanyi Airport' where Code='LJG' and Name='三义机场'
update homsomDB..Trv_Airport  set  EnglishName='Sanyuanpu Airport' where Code='TNH' and Name='三源浦机场'
update homsomDB..Trv_Airport  set  EnglishName='Shadi Airport' where Code='FUO' and Name='沙堤机场'
update homsomDB..Trv_Airport  set  EnglishName='Shaxian Airport' where Code='SQJ' and Name='沙县机场'
update homsomDB..Trv_Airport  set  EnglishName='Shache Airport' where Code='QSZ' and Name='莎车机场'
update homsomDB..Trv_Airport  set  EnglishName='Shanzihe Airport' where Code='RIZ' and Name='山字河机场'
update homsomDB..Trv_Airport  set  EnglishName='Shengli Airport' where Code='DOY' and Name='胜利机场'
update homsomDB..Trv_Airport  set  EnglishName='Beijing Capital International Airport' where Code='PEK' and Name='首都国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Shu Bu Ling Airport' where Code='LYI' and Name='沭埠岭机场'
update homsomDB..Trv_Airport  set  EnglishName='Shuangliu International Airport' where Code='CTU' and Name='双流国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Simao Airport' where Code='SYM' and Name='思茅机场'
update homsomDB..Trv_Airport  set  EnglishName='Sunan Shuofang International Airport' where Code='WUX' and Name='硕放国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Tacheng Minhang Airport' where Code='TCG' and Name='塔城民航机场'
update homsomDB..Trv_Airport  set  EnglishName='Taiping International Airport' where Code='HRB' and Name='太平国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Tumushuke Tangwangcheng Airport' where Code='TWC' and Name='唐王城机场'
update homsomDB..Trv_Airport  set  EnglishName='Taohuayuan Airport' where Code='CGD' and Name='桃花源机场'
update homsomDB..Trv_Airport  set  EnglishName='Taolai Airport' where Code='EJN' and Name='桃来机场'
update homsomDB..Trv_Airport  set  EnglishName='Taoxian International Airport' where Code='SHE' and Name='桃仙国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Tengao Airport' where Code='AOG' and Name='腾鳌机场'
update homsomDB..Trv_Airport  set  EnglishName='Tianhe International Airport' where Code='WUH' and Name='天河国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Tianjitai Airport' where Code='RLK' and Name='天吉泰机场'
update homsomDB..Trv_Airport  set  EnglishName='Tianzhushan Airport' where Code='AQG' and Name='天柱山机场'
update homsomDB..Trv_Airport  set  EnglishName='Tongliao Airport' where Code='TGO' and Name='通辽机场'
update homsomDB..Trv_Airport  set  EnglishName='Tongrenfenghuang Airport' where Code='TEN' and Name='铜仁凤凰机场'
update homsomDB..Trv_Airport  set  EnglishName='Tunxi Airport' where Code='TXN' and Name='屯溪机场'
update homsomDB..Trv_Airport  set  EnglishName='Tuofeng Airport' where Code='TCZ' and Name='驼峰机场'
update homsomDB..Trv_Airport  set  EnglishName='Washan Airport' where Code='CWJ' and Name='佤山机场'
update homsomDB..Trv_Airport  set  EnglishName='Weifang Airport' where Code='WEF' and Name='潍坊机场'
update homsomDB..Trv_Airport  set  EnglishName='Wenshanpuzhehei Airport' where Code='WNH' and Name='文山普者黑机场'
update homsomDB..Trv_Airport  set  EnglishName='Wuhai Airport' where Code='WUA' and Name='乌海机场'
update homsomDB..Trv_Airport  set  EnglishName='Ulanqab Airport' where Code='UCB' and Name='乌兰察布机场'
update homsomDB..Trv_Airport  set  EnglishName='Ulanhot Airport' where Code='HLH' and Name='乌兰浩特机场'
update homsomDB..Trv_Airport  set  EnglishName='Wuxu International Airport' where Code='NNG' and Name='吴圩国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Wuqiao Airport' where Code='WXN' and Name='五桥机场'
update homsomDB..Trv_Airport  set  EnglishName='Wutaishan Airport' where Code='WUT' and Name='五台山机场'
update homsomDB..Trv_Airport  set  EnglishName='Wudangshan Airport' where Code='WDS' and Name='武当山机场'
update homsomDB..Trv_Airport  set  EnglishName='Wugang Airport' where Code='WGN' and Name='武冈机场'
update homsomDB..Trv_Airport  set  EnglishName='Wulingshan Airport' where Code='JIQ' and Name='武陵山机场'
update homsomDB..Trv_Airport  set  EnglishName='Wusu International Airport' where Code='TYN' and Name='武宿国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Wuyishan Airport' where Code='WUS' and Name='武夷山机场'
update homsomDB..Trv_Airport  set  EnglishName='Xiguan Airport' where Code='FUG' and Name='西关机场'
update homsomDB..Trv_Airport  set  EnglishName='Xijiao Airport' where Code='NZH' and Name='西郊机场'
update homsomDB..Trv_Airport  set  EnglishName='Xilinhot Airport' where Code='XIL' and Name='锡林浩特机场'
update homsomDB..Trv_Airport  set  EnglishName='Xiahe Airport' where Code='GXH' and Name='夏河机场'
update homsomDB..Trv_Airport  set  EnglishName='Xianyang International Airport' where Code='XIY' and Name='咸阳国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Xianggelila Airport' where Code='DIG' and Name='香格里拉机场'
update homsomDB..Trv_Airport  set  EnglishName='Xiangshan Airport' where Code='ZHY' and Name='香山机场'
update homsomDB..Trv_Airport  set  EnglishName='Xiaoshan International Airport' where Code='HGH' and Name='萧山国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Xinqiao International Airport' where Code='HFE' and Name='新桥国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Xinzheng International Airport' where Code='CGO' and Name='新郑国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Xinzhou Airport' where Code='ZYI' and Name='新舟机场'
update homsomDB..Trv_Airport  set  EnglishName='Xingdong International Airport' where Code='NTG' and Name='兴东国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Xingkaihu Airport' where Code='JXA' and Name='兴凯湖机场'
update homsomDB..Trv_Airport  set  EnglishName='Xingyi Airport' where Code='ACX' and Name='兴义机场'
update homsomDB..Trv_Airport  set  EnglishName='Xujiaping Airport' where Code='ENH' and Name='许家坪机场'
update homsomDB..Trv_Airport  set  EnglishName='Yading Airport' where Code='DCY' and Name='亚丁机场'
update homsomDB..Trv_Airport  set  EnglishName='Yangzhoutaizhou Airport' where Code='YTY' and Name='扬州泰州机场'
update homsomDB..Trv_Airport  set  EnglishName='Taizhou Airport' where Code='YTY' and Name='扬州泰州机场'
update homsomDB..Trv_Airport  set  EnglishName='Yaoqiang International Airport' where Code='TNA' and Name='遥墙国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Yiershi Airport' where Code='YIE' and Name='伊尔施机场'
update homsomDB..Trv_Airport  set  EnglishName='Ejin Horo Airport' where Code='DSN' and Name='伊金霍洛机场'
update homsomDB..Trv_Airport  set  EnglishName='Yining Airport' where Code='YIN' and Name='伊宁机场'
update homsomDB..Trv_Airport  set  EnglishName='Yiwu Airport' where Code='YIW' and Name='义乌机场'
update homsomDB..Trv_Airport  set  EnglishName='Yuyang Airport' where Code='UYN' and Name='榆阳机场'
update homsomDB..Trv_Airport  set  EnglishName='Yulong Airport' where Code='CIF' and Name='玉龙机场'
update homsomDB..Trv_Airport  set  EnglishName='Batang Airport' where Code='YUS' and Name='玉树巴塘机场'
update homsomDB..Trv_Airport  set  EnglishName='Yuezhao Airport' where Code='LPF' and Name='月照机场'
update homsomDB..Trv_Airport  set  EnglishName='Yungang Airport' where Code='DAT' and Name='云冈机场'
update homsomDB..Trv_Airport  set  EnglishName='Yunlong Airport' where Code='LZO' and Name='云龙机场'
update homsomDB..Trv_Airport  set  EnglishName='Zhanjiang Airport' where Code='ZHA' and Name='湛江机场'
update homsomDB..Trv_Airport  set  EnglishName='Zhangjiakou Airport' where Code='ZQZ' and Name='张家口机场'
update homsomDB..Trv_Airport  set  EnglishName='Zhaotong Airport' where Code='ZAT' and Name='昭通机场'
update homsomDB..Trv_Airport  set  EnglishName='Zhengding International Airport' where Code='SJW' and Name='正定国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Zhijiang Airport' where Code='HJJ' and Name='芷江机场'
update homsomDB..Trv_Airport  set  EnglishName='Zhongchuan Airport' where Code='LHW' and Name='中川机场'
update homsomDB..Trv_Airport  set  EnglishName='Jiangbei International Airport' where Code='CKG' and Name='重庆江北国际机场'
update homsomDB..Trv_Airport  set  EnglishName='Zhoushuizi International Airport' where Code='DLC' and Name='周水子国际机场'

--城市信息修改
SELECT Code,Name,EnglishName FROM homsomDB..Trv_Cities where Code='AAT'
update homsomDB..Trv_Cities  set  EnglishName='Aletai' where Code='AAT' and Name='阿勒泰'
update homsomDB..Trv_Cities  set  EnglishName='Ali' where Code='NGQ' and Name='阿里'
update homsomDB..Trv_Cities  set  EnglishName='Liuzhou' where Code='LZH' and Name='柳州'
update homsomDB..Trv_Cities  set  EnglishName='Lianyungang' where Code='LYG' and Name='连云港'
update homsomDB..Trv_Cities  set  EnglishName='Hohhot' where Code='HET' and Name='呼和浩特'
update homsomDB..Trv_Cities  set  EnglishName='Guangzhou' where Code='CAN' and Name='广州'
update homsomDB..Trv_Cities  set  EnglishName='Baise' where Code='AEB' and Name='百色'
update homsomDB..Trv_Cities  set  EnglishName='Qamdo' where Code='BPX' and Name='昌都'
update homsomDB..Trv_Cities  set  EnglishName='Shenzhen' where Code='SZX' and Name='深圳'
update homsomDB..Trv_Cities  set  EnglishName='Panzhihua' where Code='PZI' and Name='攀枝花'
update homsomDB..Trv_Cities  set  EnglishName='Baoshan' where Code='BSD' and Name='保山'
update homsomDB..Trv_Cities  set  EnglishName='Qinhuangdao' where Code='BPE' and Name='秦皇岛'
update homsomDB..Trv_Cities  set  EnglishName='Luoyang' where Code='LYA' and Name='洛阳'
update homsomDB..Trv_Cities  set  EnglishName='Changzhou' where Code='CZX' and Name='常州'
update homsomDB..Trv_Cities  set  EnglishName='Tianjin' where Code='TSN' and Name='天津'
update homsomDB..Trv_Cities  set  EnglishName='Qionghai' where Code='BAR' and Name='琼海'
update homsomDB..Trv_Cities  set  EnglishName='Bole' where Code='BPL' and Name='博乐'
update homsomDB..Trv_Cities  set  EnglishName='Yibin' where Code='YBP' and Name='宜宾'
update homsomDB..Trv_Cities  set  EnglishName='Xining' where Code='XNN' and Name='西宁'
update homsomDB..Trv_Cities  set  EnglishName='Songyuan' where Code='YSQ' and Name='松原'
update homsomDB..Trv_Cities  set  EnglishName='Nanchang' where Code='KHN' and Name='南昌'
update homsomDB..Trv_Cities  set  EnglishName='Baicheng' where Code='DBC' and Name='白城'
update homsomDB..Trv_Cities  set  EnglishName='Baishan' where Code='NBS' and Name='白山'
update homsomDB..Trv_Cities  set  EnglishName='Fuzhou' where Code='FOC' and Name='福州'
update homsomDB..Trv_Cities  set  EnglishName='Kunming' where Code='KMG' and Name='昆明'
update homsomDB..Trv_Cities  set  EnglishName='Changzhi' where Code='CIH' and Name='长治'
update homsomDB..Trv_Cities  set  EnglishName='Wuzhou' where Code='WUZ' and Name='梧州'
update homsomDB..Trv_Cities  set  EnglishName='Yanji' where Code='YNJ' and Name='延吉'
update homsomDB..Trv_Cities  set  EnglishName='Chaoyang' where Code='CHG' and Name='朝阳'
update homsomDB..Trv_Cities  set  EnglishName='Chaoshan' where Code='SWA' and Name='潮汕'
update homsomDB..Trv_Cities  set  EnglishName='Chaozhou' where Code='SWA' and Name='潮州'
update homsomDB..Trv_Cities  set  EnglishName='Shantou' where Code='SWA' and Name='汕头'
update homsomDB..Trv_Cities  set  EnglishName='Jieyang' where Code='SWA' and Name='揭阳'
update homsomDB..Trv_Cities  set  EnglishName='Zhalantun' where Code='NZL' and Name='扎兰屯'
update homsomDB..Trv_Cities  set  EnglishName='Longnan' where Code='LNL' and Name='陇南'
update homsomDB..Trv_Cities  set  EnglishName='Hanzhong' where Code='HZG' and Name='汉中'
update homsomDB..Trv_Cities  set  EnglishName='Dali' where Code='DLU' and Name='大理'
update homsomDB..Trv_Cities  set  EnglishName='Weihai' where Code='WEH' and Name='威海'
update homsomDB..Trv_Cities  set  EnglishName='Dehong' where Code='LUM' and Name='德宏'
update homsomDB..Trv_Cities  set  EnglishName='Mangshi' where Code='LUM' and Name='芒市'
update homsomDB..Trv_Cities  set  EnglishName='Delingha' where Code='HXD' and Name='德令哈'
update homsomDB..Trv_Cities  set  EnglishName='Urumqi' where Code='URC' and Name='乌鲁木齐'
update homsomDB..Trv_Cities  set  EnglishName='Fuyuan' where Code='FYJ' and Name='抚远'
update homsomDB..Trv_Cities  set  EnglishName='Jiamusi' where Code='JMU' and Name='佳木斯'
update homsomDB..Trv_Cities  set  EnglishName='Hailar' where Code='HLD' and Name='海拉尔'
update homsomDB..Trv_Cities  set  EnglishName='Dunhuang' where Code='DNH' and Name='敦煌'
update homsomDB..Trv_Cities  set  EnglishName='Baotou' where Code='BAV' and Name='包头'
update homsomDB..Trv_Cities  set  EnglishName='Bijie' where Code='BFJ' and Name='毕节'
update homsomDB..Trv_Cities  set  EnglishName='Sanya' where Code='SYX' and Name='三亚'
update homsomDB..Trv_Cities  set  EnglishName='Beihai' where Code='BHY' and Name='北海'
update homsomDB..Trv_Cities  set  EnglishName='Fuyun' where Code='FYN' and Name='富蕴'
update homsomDB..Trv_Cities  set  EnglishName='Jinghong' where Code='JHG' and Name='景洪'
update homsomDB..Trv_Cities  set  EnglishName='Xishuangbanna' where Code='JHG' and Name='西双版纳'
update homsomDB..Trv_Cities  set  EnglishName='Zhangye' where Code='YZY' and Name='张掖'
update homsomDB..Trv_Cities  set  EnglishName='Nanchong' where Code='NAO' and Name='南充'
update homsomDB..Trv_Cities  set  EnglishName='Xiamen' where Code='XMN' and Name='厦门'
update homsomDB..Trv_Cities  set  EnglishName='Golmud' where Code='GOQ' and Name='格尔木'
update homsomDB..Trv_Cities  set  EnglishName='Lhasa' where Code='LXA' and Name='拉萨'
update homsomDB..Trv_Cities  set  EnglishName='Yuncheng' where Code='YCU' and Name='运城'
update homsomDB..Trv_Cities  set  EnglishName='Xuzhou' where Code='XUZ' and Name='徐州'
update homsomDB..Trv_Cities  set  EnglishName='Longyan' where Code='LCX' and Name='龙岩'
update homsomDB..Trv_Cities  set  EnglishName='Kuqa' where Code='KCA' and Name='库车'
update homsomDB..Trv_Cities  set  EnglishName='Hami' where Code='HMI' and Name='哈密'
update homsomDB..Trv_Cities  set  EnglishName='Qilian' where Code='HBQ' and Name='祁连'
update homsomDB..Trv_Cities  set  EnglishName='Mudanjiang' where Code='MDG' and Name='牡丹江'
update homsomDB..Trv_Cities  set  EnglishName='Handan' where Code='HDG' and Name='邯郸'
update homsomDB..Trv_Cities  set  EnglishName='Rikaze' where Code='RKZ' and Name='日喀则'
update homsomDB..Trv_Cities  set  EnglishName='Hotan' where Code='HTN' and Name='和田'
update homsomDB..Trv_Cities  set  EnglishName='Yinchuan' where Code='INC' and Name='银川'
update homsomDB..Trv_Cities  set  EnglishName='Daxian' where Code='DAX' and Name='达县'
update homsomDB..Trv_Cities  set  EnglishName='Dazhou' where Code='DAX' and Name='达州'
update homsomDB..Trv_Cities  set  EnglishName='Zhangjiajie' where Code='DYG' and Name='张家界'
update homsomDB..Trv_Cities  set  EnglishName='Heihe' where Code='HEK' and Name='黑河'
update homsomDB..Trv_Cities  set  EnglishName='Shennongjia' where Code='HPG' and Name='神农架'
update homsomDB..Trv_Cities  set  EnglishName='Shanghai' where Code='SHA' and Name='上海'
update homsomDB..Trv_Cities  set  EnglishName='Huatugou' where Code='HTT' and Name='花土沟'
update homsomDB..Trv_Cities  set  EnglishName='Shihezi' where Code='SHF' and Name='石河子'
update homsomDB..Trv_Cities  set  EnglishName='Anshun' where Code='AVA' and Name='安顺'
update homsomDB..Trv_Cities  set  EnglishName='Changsha' where Code='CSX' and Name='长沙'
update homsomDB..Trv_Cities  set  EnglishName='Ganzhou' where Code='KOW' and Name='赣州'
update homsomDB..Trv_Cities  set  EnglishName='Jiuzhaigou' where Code='JZH' and Name='九寨沟'
update homsomDB..Trv_Cities  set  EnglishName='Kaili' where Code='KJH' and Name='凯里'
update homsomDB..Trv_Cities  set  EnglishName='Huolinguole' where Code='HUO' and Name='霍林郭勒'
update homsomDB..Trv_Cities  set  EnglishName='Jiagedaqi' where Code='JGD' and Name='加格达奇'
update homsomDB..Trv_Cities  set  EnglishName='Jiayuguan' where Code='JGN' and Name='嘉峪关'
update homsomDB..Trv_Cities  set  EnglishName='Jiansanjiang' where Code='JSJ' and Name='建三江'
update homsomDB..Trv_Cities  set  EnglishName='Nanyang' where Code='NNY' and Name='南阳'
update homsomDB..Trv_Cities  set  EnglishName='Tulufan' where Code='TLQ' and Name='吐鲁番'
update homsomDB..Trv_Cities  set  EnglishName='Hechi' where Code='HCJ' and Name='河池'
update homsomDB..Trv_Cities  set  EnglishName='Jinchang' where Code='JIC' and Name='金昌'
update homsomDB..Trv_Cities  set  EnglishName='Zhuhai' where Code='ZUH' and Name='珠海'
update homsomDB..Trv_Cities  set  EnglishName='Jinzhou' where Code='JNZ' and Name='锦州'
update homsomDB..Trv_Cities  set  EnglishName='Jinjiang' where Code='JJN' and Name='晋江'
update homsomDB..Trv_Cities  set  EnglishName='Quanzhou' where Code='JJN' and Name='泉州'
update homsomDB..Trv_Cities  set  EnglishName='Jinggangshan' where Code='JGS' and Name='井冈山'
update homsomDB..Trv_Cities  set  EnglishName='Jingdezhen' where Code='JDZ' and Name='景德镇'
update homsomDB..Trv_Cities  set  EnglishName='Lancang' where Code='JMJ' and Name='澜沧'
update homsomDB..Trv_Cities  set  EnglishName='Chizhou' where Code='JUH' and Name='池州'
update homsomDB..Trv_Cities  set  EnglishName='Burqin' where Code='KJI' and Name='布尔津'
update homsomDB..Trv_Cities  set  EnglishName='Kashgar' where Code='KHG' and Name='喀什'
update homsomDB..Trv_Cities  set  EnglishName='Kangding' where Code='KGT' and Name='康定'
update homsomDB..Trv_Cities  set  EnglishName='Karamay' where Code='KRY' and Name='克拉玛依'
update homsomDB..Trv_Cities  set  EnglishName='Korla' where Code='KRL' and Name='库尔勒'
update homsomDB..Trv_Cities  set  EnglishName='Yingkou' where Code='YKH' and Name='营口'
update homsomDB..Trv_Cities  set  EnglishName='Dandong' where Code='DDG' and Name='丹东'
update homsomDB..Trv_Cities  set  EnglishName='Liping' where Code='HZH' and Name='黎平'
update homsomDB..Trv_Cities  set  EnglishName='Ningbo' where Code='NGB' and Name='宁波'
update homsomDB..Trv_Cities  set  EnglishName='Libo' where Code='LLB' and Name='荔波'
update homsomDB..Trv_Cities  set  EnglishName='HuaiAn' where Code='HIA' and Name='淮安'
update homsomDB..Trv_Cities  set  EnglishName='Guilin' where Code='KWL' and Name='桂林'
update homsomDB..Trv_Cities  set  EnglishName='Yichun' where Code='LDS' and Name='伊春'
update homsomDB..Trv_Cities  set  EnglishName='Lincang' where Code='LNJ' and Name='临沧'
update homsomDB..Trv_Cities  set  EnglishName='Yongzhou' where Code='LLF' and Name='永州'
update homsomDB..Trv_Cities  set  EnglishName='Xiangyang' where Code='XFN' and Name='襄阳'
update homsomDB..Trv_Cities  set  EnglishName='Qingdao' where Code='TAO' and Name='青岛'
update homsomDB..Trv_Cities  set  EnglishName='Guyuan' where Code='GYU' and Name='固原'
update homsomDB..Trv_Cities  set  EnglishName='Guiyang' where Code='KWE' and Name='贵阳'
update homsomDB..Trv_Cities  set  EnglishName='Changchun' where Code='CGQ' and Name='长春'
update homsomDB..Trv_Cities  set  EnglishName='Wenzhou' where Code='WNZ' and Name='温州'
update homsomDB..Trv_Cities  set  EnglishName='Ruoqiang' where Code='RQA' and Name='若羌'
update homsomDB..Trv_Cities  set  EnglishName='Jiujiang' where Code='JIU' and Name='九江'
update homsomDB..Trv_Cities  set  EnglishName='Ninglang' where Code='NLH' and Name='宁蒗'
update homsomDB..Trv_Cities  set  EnglishName='Nanjing' where Code='NKG' and Name='南京'
update homsomDB..Trv_Cities  set  EnglishName='Taizhou' where Code='HYN' and Name='台州'
update homsomDB..Trv_Cities  set  EnglishName='Lvliang' where Code='LLV' and Name='吕梁'
update homsomDB..Trv_Cities  set  EnglishName='Golog' where Code='GMQ' and Name='果洛'
update homsomDB..Trv_Cities  set  EnglishName='Tianshui' where Code='THQ' and Name='天水'
update homsomDB..Trv_Cities  set  EnglishName='Zunyimaotai' where Code='WMT' and Name='遵义'
update homsomDB..Trv_Cities  set  EnglishName='Meizhou' where Code='MXZ' and Name='梅州'
update homsomDB..Trv_Cities  set  EnglishName='Haikou' where Code='HAK' and Name='海口'
update homsomDB..Trv_Cities  set  EnglishName='Nyingtri' where Code='LZY' and Name='林芝'
update homsomDB..Trv_Cities  set  EnglishName='Xinyang' where Code='XAI' and Name='信阳'
update homsomDB..Trv_Cities  set  EnglishName='Yichun' where Code='YIC' and Name='宜春'
update homsomDB..Trv_Cities  set  EnglishName='Mohe' where Code='OHE' and Name='漠河'
update homsomDB..Trv_Cities  set  EnglishName='Xinyuan' where Code='NLT' and Name='新源'
update homsomDB..Trv_Cities  set  EnglishName='Nangan' where Code='LZN' and Name='南竿'
update homsomDB..Trv_Cities  set  EnglishName='Mianyang' where Code='MIG' and Name='绵阳'
update homsomDB..Trv_Cities  set  EnglishName='YanAn' where Code='ENY' and Name='延安'
update homsomDB..Trv_Cities  set  EnglishName='Yancheng' where Code='YNZ' and Name='盐城'
update homsomDB..Trv_Cities  set  EnglishName='Beijing' where Code='BJS' and Name='北京'
update homsomDB..Trv_Cities  set  EnglishName='Hengyang' where Code='HNY' and Name='衡阳'
update homsomDB..Trv_Cities  set  EnglishName='Guangyuan' where Code='GYS' and Name='广元'
update homsomDB..Trv_Cities  set  EnglishName='Yantai' where Code='YNT' and Name='烟台'
update homsomDB..Trv_Cities  set  EnglishName='Huizhou' where Code='HUZ' and Name='惠州'
update homsomDB..Trv_Cities  set  EnglishName='Shanghai' where Code='SHA' and Name='上海'
update homsomDB..Trv_Cities  set  EnglishName='Chengde' where Code='CDE' and Name='承德'
update homsomDB..Trv_Cities  set  EnglishName='Zhoushan' where Code='HSN' and Name='舟山'
update homsomDB..Trv_Cities  set  EnglishName='Linfen' where Code='LFQ' and Name='临汾'
update homsomDB..Trv_Cities  set  EnglishName='Qiemo' where Code='IQM' and Name='且末'
update homsomDB..Trv_Cities  set  EnglishName='Xichang' where Code='XIC' and Name='西昌'
update homsomDB..Trv_Cities  set  EnglishName='Qingyang' where Code='IQN' and Name='庆阳'
update homsomDB..Trv_Cities  set  EnglishName='Jining' where Code='JNG' and Name='济宁'
update homsomDB..Trv_Cities  set  EnglishName='Quzhou' where Code='JUZ' and Name='衢州'
update homsomDB..Trv_Cities  set  EnglishName='Daqing' where Code='DQA' and Name='大庆'
update homsomDB..Trv_Cities  set  EnglishName='Erenhot' where Code='ERL' and Name='二连浩特'
update homsomDB..Trv_Cities  set  EnglishName='Yueyang' where Code='YYA' and Name='岳阳'
update homsomDB..Trv_Cities  set  EnglishName='Qiqihar' where Code='NDG' and Name='齐齐哈尔'
update homsomDB..Trv_Cities  set  EnglishName='Tangshan' where Code='TVS' and Name='唐山'
update homsomDB..Trv_Cities  set  EnglishName='Shangrao' where Code='SQD' and Name='上饶'
update homsomDB..Trv_Cities  set  EnglishName='Yichang' where Code='YIH' and Name='宜昌'
update homsomDB..Trv_Cities  set  EnglishName='Lijiang' where Code='LJG' and Name='丽江'
update homsomDB..Trv_Cities  set  EnglishName='Tonghua' where Code='TNH' and Name='通化'
update homsomDB..Trv_Cities  set  EnglishName='Foshan' where Code='FUO' and Name='佛山'
update homsomDB..Trv_Cities  set  EnglishName='Sanming' where Code='SQJ' and Name='三明'
update homsomDB..Trv_Cities  set  EnglishName='Shache' where Code='QSZ' and Name='莎车'
update homsomDB..Trv_Cities  set  EnglishName='Rizhao' where Code='RIZ' and Name='日照'
update homsomDB..Trv_Cities  set  EnglishName='Dongying' where Code='DOY' and Name='东营'
update homsomDB..Trv_Cities  set  EnglishName='Beijing' where Code='BJS' and Name='北京'
update homsomDB..Trv_Cities  set  EnglishName='Linyi' where Code='LYI' and Name='临沂'
update homsomDB..Trv_Cities  set  EnglishName='Chengdu' where Code='CTU' and Name='成都'
update homsomDB..Trv_Cities  set  EnglishName='PuEr' where Code='SYM' and Name='普洱'
update homsomDB..Trv_Cities  set  EnglishName='Wuxi' where Code='WUX' and Name='无锡'
update homsomDB..Trv_Cities  set  EnglishName='Tacheng' where Code='TCG' and Name='塔城'
update homsomDB..Trv_Cities  set  EnglishName='Harbin' where Code='HRB' and Name='哈尔滨'
update homsomDB..Trv_Cities  set  EnglishName='Tumushuke' where Code='TWC' and Name='图木舒克'
update homsomDB..Trv_Cities  set  EnglishName='Changde' where Code='CGD' and Name='常德'
update homsomDB..Trv_Cities  set  EnglishName='Ejinaqi' where Code='EJN' and Name='额济纳旗'
update homsomDB..Trv_Cities  set  EnglishName='Shenyang' where Code='SHE' and Name='沈阳'
update homsomDB..Trv_Cities  set  EnglishName='Anshan' where Code='AOG' and Name='鞍山'
update homsomDB..Trv_Cities  set  EnglishName='Wuhan' where Code='WUH' and Name='武汉'
update homsomDB..Trv_Cities  set  EnglishName='Bayan Nur' where Code='RLK' and Name='巴彦淖尔'
update homsomDB..Trv_Cities  set  EnglishName='Anqing' where Code='AQG' and Name='安庆'
update homsomDB..Trv_Cities  set  EnglishName='Tongliao' where Code='TGO' and Name='通辽'
update homsomDB..Trv_Cities  set  EnglishName='Tongren' where Code='TEN' and Name='铜仁'
update homsomDB..Trv_Cities  set  EnglishName='Huangshan' where Code='TXN' and Name='黄山'
update homsomDB..Trv_Cities  set  EnglishName='Tengchong' where Code='TCZ' and Name='腾冲'
update homsomDB..Trv_Cities  set  EnglishName='Cangyuan' where Code='CWJ' and Name='沧源'
update homsomDB..Trv_Cities  set  EnglishName='Weifang' where Code='WEF' and Name='潍坊'
update homsomDB..Trv_Cities  set  EnglishName='Wenshan' where Code='WNH' and Name='文山'
update homsomDB..Trv_Cities  set  EnglishName='Wuhai' where Code='WUA' and Name='乌海'
update homsomDB..Trv_Cities  set  EnglishName='Ulanqab' where Code='UCB' and Name='乌兰察布'
update homsomDB..Trv_Cities  set  EnglishName='Ulanhot' where Code='HLH' and Name='乌兰浩特'
update homsomDB..Trv_Cities  set  EnglishName='Nanning' where Code='NNG' and Name='南宁'
update homsomDB..Trv_Cities  set  EnglishName='Wanzhou' where Code='WXN' and Name='万州'
update homsomDB..Trv_Cities  set  EnglishName='Xinzhou' where Code='WUT' and Name='忻州'
update homsomDB..Trv_Cities  set  EnglishName='Shiyan' where Code='WDS' and Name='十堰'
update homsomDB..Trv_Cities  set  EnglishName='Shaoyang' where Code='WGN' and Name='邵阳'
update homsomDB..Trv_Cities  set  EnglishName='Qianjiang' where Code='JIQ' and Name='黔江'
update homsomDB..Trv_Cities  set  EnglishName='Taiyuan' where Code='TYN' and Name='太原'
update homsomDB..Trv_Cities  set  EnglishName='Wuyishan' where Code='WUS' and Name='武夷山'
update homsomDB..Trv_Cities  set  EnglishName='Fuyang' where Code='FUG' and Name='阜阳'
update homsomDB..Trv_Cities  set  EnglishName='Manzhouli' where Code='NZH' and Name='满洲里'
update homsomDB..Trv_Cities  set  EnglishName='Xilinhot' where Code='XIL' and Name='锡林浩特'
update homsomDB..Trv_Cities  set  EnglishName='Xiahe' where Code='GXH' and Name='夏河'
update homsomDB..Trv_Cities  set  EnglishName='Xian' where Code='SIA' and Name='西安'
update homsomDB..Trv_Cities  set  EnglishName='Diqing' where Code='DIG' and Name='迪庆'
update homsomDB..Trv_Cities  set  EnglishName='Zhongwei' where Code='ZHY' and Name='中卫'
update homsomDB..Trv_Cities  set  EnglishName='Hangzhou' where Code='HGH' and Name='杭州'
update homsomDB..Trv_Cities  set  EnglishName='Hefei' where Code='HFE' and Name='合肥'
update homsomDB..Trv_Cities  set  EnglishName='Zhengzhou' where Code='CGO' and Name='郑州'
update homsomDB..Trv_Cities  set  EnglishName='Zunyi' where Code='ZYI' and Name='遵义'
update homsomDB..Trv_Cities  set  EnglishName='Nantong' where Code='NTG' and Name='南通'
update homsomDB..Trv_Cities  set  EnglishName='Jixi' where Code='JXA' and Name='鸡西'
update homsomDB..Trv_Cities  set  EnglishName='Xingyi' where Code='ACX' and Name='兴义'
update homsomDB..Trv_Cities  set  EnglishName='Enshi' where Code='ENH' and Name='恩施'
update homsomDB..Trv_Cities  set  EnglishName='Daocheng' where Code='DCY' and Name='稻城'
update homsomDB..Trv_Cities  set  EnglishName='Taizhou' where Code='YTY' and Name='泰州'
update homsomDB..Trv_Cities  set  EnglishName='Yangzhou' where Code='YTY' and Name='扬州'
update homsomDB..Trv_Cities  set  EnglishName='Jinan' where Code='TNA' and Name='济南'
update homsomDB..Trv_Cities  set  EnglishName='Aershan' where Code='YIE' and Name='阿尔山'
update homsomDB..Trv_Cities  set  EnglishName='Ordos' where Code='DSN' and Name='鄂尔多斯'
update homsomDB..Trv_Cities  set  EnglishName='Yining' where Code='YIN' and Name='伊宁'
update homsomDB..Trv_Cities  set  EnglishName='Yiwu' where Code='YIW' and Name='义乌'
update homsomDB..Trv_Cities  set  EnglishName='Yulin' where Code='UYN' and Name='榆林'
update homsomDB..Trv_Cities  set  EnglishName='Chifeng' where Code='CIF' and Name='赤峰'
update homsomDB..Trv_Cities  set  EnglishName='Yushu' where Code='YUS' and Name='玉树'
update homsomDB..Trv_Cities  set  EnglishName='Liupanshui' where Code='LPF' and Name='六盘水'
update homsomDB..Trv_Cities  set  EnglishName='Datong' where Code='DAT' and Name='大同'
update homsomDB..Trv_Cities  set  EnglishName='Luzhou' where Code='LZO' and Name='泸州'
update homsomDB..Trv_Cities  set  EnglishName='Zhanjiang' where Code='ZHA' and Name='湛江'
update homsomDB..Trv_Cities  set  EnglishName='Zhangjiakou' where Code='ZQZ' and Name='张家口'
update homsomDB..Trv_Cities  set  EnglishName='Zhaotong' where Code='ZAT' and Name='昭通'
update homsomDB..Trv_Cities  set  EnglishName='Shijiazhuang' where Code='SJW' and Name='石家庄'
update homsomDB..Trv_Cities  set  EnglishName='Huaihua' where Code='HJJ' and Name='怀化'
update homsomDB..Trv_Cities  set  EnglishName='Lanzhou' where Code='LHW' and Name='兰州'
update homsomDB..Trv_Cities  set  EnglishName='Chongqing' where Code='CKG' and Name='重庆'
update homsomDB..Trv_Cities  set  EnglishName='Dalian' where Code='DLC' and Name='大连'


--航司信息修改
SELECT code2,airname,sx1,sx,enairname,* FROM ehomsom..tbInfAirCompany where airname='地平线航空'
update ehomsom..tbInfAirCompany  set enairname='Alaska Airlines' where code2='AS'
update ehomsom..tbInfAirCompany  set enairname='Air Caledonie International' where code2='SB'
update ehomsom..tbInfAirCompany  set enairname='China Yunnan Airlines' where code2='3Q'
update ehomsom..tbInfAirCompany  set enairname='Air Pacific' where code2='FJ'
update ehomsom..tbInfAirCompany  set enairname='Uni Air (Taiwan)' where code2='B7'
update ehomsom..tbInfAirCompany  set enairname='Thai Airways' where code2='TG'
update ehomsom..tbInfAirCompany  set enairname='Indian Airlines' where code2='IC'
update ehomsom..tbInfAirCompany  set enairname='Aom French Airlines' where code2='IW'
update ehomsom..tbInfAirCompany  set enairname='Jatayu Airlines' where code2='VJ'
update ehomsom..tbInfAirCompany  set enairname='Philippine Airlines' where code2='PR'
update ehomsom..tbInfAirCompany  set enairname='Singapore Silk Air' where code2='MI'
update ehomsom..tbInfAirCompany  set enairname='Lam - Linhas Aéreas De Mo?Ambique' where code2='TM'
update ehomsom..tbInfAirCompany  set enairname='Tarom' where code2='RO'
update ehomsom..tbInfAirCompany  set enairname='China Eastern Airlines' where code2='MU'
update ehomsom..tbInfAirCompany  set enairname='Loong Air' where code2='GJ'
update ehomsom..tbInfAirCompany  set airname='天马航空公司',sx1='天马航空', sx='天马航空',enairname='TAM Airline' where code2='JJ'
update ehomsom..tbInfAirCompany  set enairname='Aerovias De Mexico' where code2='AM'
update ehomsom..tbInfAirCompany  set enairname='Garuda Indonesia' where code2='GA'
update ehomsom..tbInfAirCompany  set enairname=' Transavia Holland N.V' where code2='HV'
update ehomsom..tbInfAirCompany  set enairname='Juneyao Airlines' where code2='HO'
update ehomsom..tbInfAirCompany  set enairname='Southwest Airlines' where code2='WN'
update ehomsom..tbInfAirCompany  set enairname='Chengdu Airlines' where code2='EU'
update ehomsom..tbInfAirCompany  set enairname='Czech Airlines (Csa)' where code2='OK'
update ehomsom..tbInfAirCompany  set enairname='Jeju Air' where code2='7C'
update ehomsom..tbInfAirCompany  set enairname='TransAsia Airways' where code2='GE'
update ehomsom..tbInfAirCompany  set airname='爱尔兰航空',sx1='爱尔兰航空', sx='爱尔兰航空',enairname='Aer Lingus Regional' where code2='EI'
update ehomsom..tbInfAirCompany  set enairname='Jet Airways' where code2='9W'
update ehomsom..tbInfAirCompany  set enairname='Air Namibia' where code2='SW'
update ehomsom..tbInfAirCompany  set enairname='Kuwait Airways' where code2='KU'
update ehomsom..tbInfAirCompany  set enairname='Overseas National Airways (Ona)' where code2='OV'
update ehomsom..tbInfAirCompany  set enairname='Linhas Aereas De Angola Airlines' where code2='DT'
update ehomsom..tbInfAirCompany  set enairname='Compania Mexicana De Aviation' where code2='MX'
update ehomsom..tbInfAirCompany  set enairname='Air Berlin' where code2='AB'
update ehomsom..tbInfAirCompany  set enairname='Air Astana' where code2='KC'
update ehomsom..tbInfAirCompany  set enairname='Aero Costa Rica' where code2='LR'
update ehomsom..tbInfAirCompany  set enairname='Indigo Airline' where code2='6E'
update ehomsom..tbInfAirCompany  set enairname='Albanian Airlines' where code2='LV'
update ehomsom..tbInfAirCompany  set enairname='Air Koryo' where code2='JS'
update ehomsom..tbInfAirCompany  set enairname='MIAT Mongolia' where code2='OM'
update ehomsom..tbInfAirCompany  set enairname='Emirates Airline' where code2='EK'
update ehomsom..tbInfAirCompany  set enairname='British Midland Airlines' where code2='BM'
update ehomsom..tbInfAirCompany  set enairname='Far East Air Transport' where code2='FE'
update ehomsom..tbInfAirCompany  set enairname='SNCF' where code2='2C'
update ehomsom..tbInfAirCompany  set enairname='La Compagnie' where code2='B0'
update ehomsom..tbInfAirCompany  set enairname='Ural Airlines' where code2='U6'
update ehomsom..tbInfAirCompany  set enairname='Varig Brasil' where code2='RG'
update ehomsom..tbInfAirCompany  set enairname='Norwegian Air Shuttle ASA' where code2='DI'
update ehomsom..tbInfAirCompany  set airname='德国之翼航空公司',sx1='德国之翼航空', sx='德国之翼航空',enairname='Germanwings' where code2='4U'
update ehomsom..tbInfAirCompany  set airname='智利国家航空',sx1='智利国家航空', sx='智利国家航空',enairname='Lan Airlines Sa' where code2='LA'
update ehomsom..tbInfAirCompany  set airname='大新华航空',sx1='大新华航空', sx='大新华航空',enairname='Grand China Airlines' where code2='CN'
update ehomsom..tbInfAirCompany  set airname='地平线航空',sx1='地平线航空', sx='地平线航空',enairname='Horizon Air' where code2='QX'
update ehomsom..tbInfAirCompany  set airname='LAUDA航空',sx1='LAUDA航空', sx='LAUDA航空',enairname='Lauda Air' where code2='NG'
update ehomsom..tbInfAirCompany  set airname='桂林航空',sx1='桂航', sx='桂航',enairname='Guilin Airlines' where code2='GT'
update ehomsom..tbInfAirCompany  set airname='摩尔多瓦航空',sx1='摩尔多瓦航空', sx='摩尔多瓦航空',enairname='Air Moldova' where code2='9U'
update ehomsom..tbInfAirCompany  set airname='中华航空',sx1='中华航空', sx='华航',enairname='China Airlines' where code2='CI'
update ehomsom..tbInfAirCompany  set airname='布拉克航空',sx1='布拉克航空', sx='布拉克航空',enairname='Bouraq Indonesia Airlines' where code2='BO'
update ehomsom..tbInfAirCompany  set airname='多洛米蒂航空公司',sx1='多洛米蒂航空', sx='多洛米蒂航空',enairname='Air Dolomiti' where code2='EN'
update ehomsom..tbInfAirCompany  set airname='美国西北航空',sx1='美国西北航空', sx='美国西北航空',enairname='Northwest Airlines' where code2='NW'
update ehomsom..tbInfAirCompany  set airname='海南航空',sx1='海航', sx='海航',enairname='Hainan Airlines Company' where code2='HU'
update ehomsom..tbInfAirCompany  set airname='美国航空',sx1='美国航空', sx='美航',enairname='American Airlines' where code2='AA'
update ehomsom..tbInfAirCompany  set airname='合众国航空',sx1='合众国航空', sx='合众国航空',enairname='Usair' where code2='US'
update ehomsom..tbInfAirCompany  set airname='山东航空',sx1='山航', sx='山航',enairname='Shandong Airlines' where code2='SC'
update ehomsom..tbInfAirCompany  set airname='内华达航空',sx1='内华达航空', sx='内华达航空',enairname='Lloydairways' where code2='LW'
update ehomsom..tbInfAirCompany  set airname='昆明航空',sx1='昆航', sx='昆航',enairname='Kun Ming Airlines' where code2='KY'
update ehomsom..tbInfAirCompany  set airname='英国易捷航空',sx1='英国易捷航空', sx='英国易捷航空',enairname='Easyjet Airline Company Limited' where code2='U2'
update ehomsom..tbInfAirCompany  set airname='文莱皇家航空',sx1='文莱皇家航空', sx='文莱皇家航空',enairname='Royal Brunei Airlines' where code2='BI'
update ehomsom..tbInfAirCompany  set airname='东海航空',sx1='东海', sx='东海',enairname='Donghai Airlines' where code2='DZ'
update ehomsom..tbInfAirCompany  set airname='塞内加尔航空',sx1='塞内加尔航空', sx='塞内加尔航空',enairname='Volotea Airlines' where code2='V7'
update ehomsom..tbInfAirCompany  set airname='巴勒斯坦航空',sx1='巴勒斯坦航空', sx='巴勒斯坦航空',enairname='Palestinian Airlines' where code2='PF'
update ehomsom..tbInfAirCompany  set airname='阿根廷航空',sx1='阿根廷航空', sx='阿根廷航空',enairname='Aerolineas Argentinas' where code2='AR'
update ehomsom..tbInfAirCompany  set airname='非洲航空',sx1='非洲航空', sx='非洲航空',enairname='Air Afrique' where code2='RK'
update ehomsom..tbInfAirCompany  set airname='弗莱比航空',sx1='弗莱比航空', sx='弗莱比航空',enairname='Flybe' where code2='BE'
update ehomsom..tbInfAirCompany  set airname='伊朗航空',sx1='伊朗航空', sx='伊朗航空',enairname='Iran Air' where code2='IR'
update ehomsom..tbInfAirCompany  set airname='沙哈拉航空',sx1='沙哈拉航空', sx='沙哈拉航空',enairname='Sahara Airlines' where code2='S2'
update ehomsom..tbInfAirCompany  set airname='约旦皇家航空',sx1='约旦皇家航空', sx='约旦皇家航空',enairname='Royal Jordanian Airlines' where code2='RJ'
update ehomsom..tbInfAirCompany  set airname='多莫杰多沃航空',sx1='多莫杰多航空', sx='多莫杰多航空',enairname='Domodedovo Airlines' where code2='E3'
update ehomsom..tbInfAirCompany  set airname='奥凯航空',sx1='奥凯航空', sx='奥凯航空',enairname='Okay Airlines' where code2='BK'
update ehomsom..tbInfAirCompany  set airname='弗拉门戈航空',sx1='弗拉门戈航空', sx='弗拉门戈航空',enairname='Flamenco' where code2='F4'
update ehomsom..tbInfAirCompany  set airname='巴尔干半岛航空',sx1='巴尔干半岛航空', sx='巴尔干半岛航空',enairname='Belle Air' where code2='LZ'
update ehomsom..tbInfAirCompany  set airname='地中海科西嘉航空',sx1='地中海航空', sx='地中海航空',enairname='Ccm Airlines' where code2='XK'
update ehomsom..tbInfAirCompany  set airname='全日空航空',sx1='全日空航空', sx='全日空航空',enairname='All Nippon Airways' where code2='NH'
update ehomsom..tbInfAirCompany  set airname='澳大利亚航空',sx1='澳大利亚航空', sx='澳大利亚航空',enairname='Qantas Airways' where code2='QF'
update ehomsom..tbInfAirCompany  set airname='埃及航空',sx1='埃及航空', sx='埃及航空',enairname='Egypt Air' where code2='MS'
update ehomsom..tbInfAirCompany  set airname='INTERIMPEX-AVIOMPEX航空',sx1='INTERIMPEX-AVIOMPEX航空', sx='INTERIMPEX-AVIOMPEX航空',enairname='' where code2='M4'
update ehomsom..tbInfAirCompany  set airname='Scat航空',sx1='Scat航空', sx='Scat航空',enairname='Scat Airlines' where code2='DV'
update ehomsom..tbInfAirCompany  set airname='远东航空',sx1='远东航空', sx='远东航空',enairname='Far Eastern Air Transport' where code2='FE'
update ehomsom..tbInfAirCompany  set airname='奥地利航空',sx1='奥地利航空', sx='奥地利航空',enairname='Austrian Airlines' where code2='OS'
update ehomsom..tbInfAirCompany  set airname='大韩航空',sx1='大韩航空', sx='大韩',enairname='Korean Airlines' where code2='KE'
update ehomsom..tbInfAirCompany  set airname='坦桑尼亚航空',sx1='坦桑尼亚航空', sx='坦桑尼亚航空',enairname='Trans Caribbean Airways' where code2='TC'
update ehomsom..tbInfAirCompany  set airname='斯潘航空',sx1='斯潘航空', sx='斯潘航空',enairname='Span Air' where code2='JK'
update ehomsom..tbInfAirCompany  set airname='祥鹏航空',sx1='祥鹏', sx='祥鹏',enairname='Lucky Airlines' where code2='8L'
update ehomsom..tbInfAirCompany  set airname='广西北部湾航空',sx1='北部湾航空', sx='北部湾航空',enairname='Guangxi Beibu Gulf Airlines' where code2='GX'
update ehomsom..tbInfAirCompany  set airname='符拉迪沃斯托克航空公司',sx1='符拉迪沃斯托克航空', sx='符拉迪沃斯托克航空',enairname='Vladivostok Air' where code2='XF'
update ehomsom..tbInfAirCompany  set airname='几内亚航空公司',sx1='几内亚航空', sx='几内亚航空',enairname='Air Guinee' where code2='GI'
update ehomsom..tbInfAirCompany  set airname='英安航空',sx1='英安航空', sx='英安航空',enairname='Air Ying An' where code2='YI'
update ehomsom..tbInfAirCompany  set airname='国龙航空',sx1='国龙航空', sx='国龙航空',enairname='Hmy Airways . D/B/A Harmony Airways' where code2='HQ'
update ehomsom..tbInfAirCompany  set airname='红土航空',sx1='红航', sx='红航',enairname='Hongtu Airlines' where code2='A6'
update ehomsom..tbInfAirCompany  set airname='Vistara航空公司',sx1='Vistara', sx='Vistara',enairname='vistaraairline' where code2='UK'
update ehomsom..tbInfAirCompany  set airname='长荣航空',sx1='长荣航空', sx='长荣',enairname='EVA Airways Corporation' where code2='BR'
update ehomsom..tbInfAirCompany  set airname='九元航空',sx1='九元航空', sx='九元航空',enairname='9 Air Co.,Ltd.' where code2='AQ'
update ehomsom..tbInfAirCompany  set airname='捷星亚洲航空',sx1='捷星航空', sx='捷星航空',enairname='Jetstarasia' where code2='3K'
update ehomsom..tbInfAirCompany  set airname='危地马拉航空',sx1='危地马拉航空', sx='危地马拉航空',enairname='Aviateca' where code2='GU'
update ehomsom..tbInfAirCompany  set airname='韩国真航空公司',sx1='真航空', sx='真航空',enairname='Jin Air' where code2='LJ'
update ehomsom..tbInfAirCompany  set airname='维珍航空',sx1='维珍航空', sx='珍航',enairname='Virgin Atlantic Airways' where code2='VS'
update ehomsom..tbInfAirCompany  set airname='海湾航空',sx1='海湾航空', sx='海湾航空',enairname='Gulf Air' where code2='GF'
update ehomsom..tbInfAirCompany  set airname='芬兰航空',sx1='芬兰航空', sx='芬航',enairname='Finnair Oyj' where code2='AY'
update ehomsom..tbInfAirCompany  set airname='香港快运航空',sx1='香港快运航空', sx='香港快运航空',enairname='Hong Kong Express Airlines' where code2='UO'
update ehomsom..tbInfAirCompany  set airname='加蓬航空',sx1='加蓬航空', sx='加蓬航空',enairname='Air Gabon' where code2='GN'
update ehomsom..tbInfAirCompany  set airname='亚美尼亚也门航空',sx1='亚美尼亚也门航空', sx='亚美尼亚也门航空',enairname='Yemenia - Yemen Airways' where code2='IY'
update ehomsom..tbInfAirCompany  set airname='韩亚航空',sx1='韩亚航空', sx='韩亚',enairname='Aisana Airlines' where code2='OZ'
update ehomsom..tbInfAirCompany  set airname='荷兰皇家航空',sx1='荷兰皇家航空', sx='荷航',enairname='Klm Royal Dutch Airlines' where code2='KL'
update ehomsom..tbInfAirCompany  set airname='环球航空',sx1='环球航空', sx='环球航空',enairname='Trans World Airlines' where code2='TW'
update ehomsom..tbInfAirCompany  set airname='新加坡航',sx1='新加坡航', sx='新航',enairname='Singapore Airlines' where code2='SQ'
update ehomsom..tbInfAirCompany  set airname='西部航空',sx1='西部', sx='西部',enairname='China West Airlines' where code2='PN'
update ehomsom..tbInfAirCompany  set airname='夏威夷航空',sx1='夏威夷航空', sx='夏航',enairname='Hawaiian Airlines' where code2='HA'
update ehomsom..tbInfAirCompany  set airname='印度航空',sx1='印度航空', sx='印航',enairname='Air India' where code2='AI'
update ehomsom..tbInfAirCompany  set airname='南非航空',sx1='南非航空', sx='南非航空',enairname='South African Airways' where code2='SA'
update ehomsom..tbInfAirCompany  set airname='马达加斯加航空',sx1='马达加斯航空', sx='马达加斯航空',enairname='Air Madagascar' where code2='MD'
update ehomsom..tbInfAirCompany  set airname='以色列航空',sx1='以色列航空', sx='以航',enairname='El Al Israel Airlines' where code2='LY'
update ehomsom..tbInfAirCompany  set airname='釜山航空',sx1='釜山航空', sx='釜山航空',enairname='Airbusan' where code2='BX'
update ehomsom..tbInfAirCompany  set airname='西班牙航空',sx1='西班牙航空', sx='西班牙航空',enairname='Spanair ' where code2='IB'
update ehomsom..tbInfAirCompany  set airname='亚速尔航空',sx1='亚速尔航空', sx='亚速尔航空',enairname='Sata Air Acores' where code2='SP'
update ehomsom..tbInfAirCompany  set airname='奥斯特拉尔航空',sx1='奥斯特拉航空', sx='奥斯特拉航空',enairname='Austral Lineas Aereas' where code2='AU'
update ehomsom..tbInfAirCompany  set airname='苏丹航空',sx1='苏丹航空', sx='苏丹航空',enairname='Sudan Airways' where code2='SD'
update ehomsom..tbInfAirCompany  set airname='布鲁塞尔航空公司',sx1='布鲁塞尔航空', sx='布鲁塞尔航空',enairname='Sn Brussels Airlines' where code2='SN'
update ehomsom..tbInfAirCompany  set airname='塔特拉航空',sx1='塔特拉航空', sx='塔特拉航空',enairname='Tatra Air' where code2='QS'
update ehomsom..tbInfAirCompany  set airname='萨马拉航空',sx1='萨马拉航空', sx='萨马拉航空',enairname='Samara Airlines' where code2='E5'
update ehomsom..tbInfAirCompany  set airname='亚美利加西方航空',sx1='亚美利加西方航空', sx='亚美利加西方航空',enairname='America West Airlines' where code2='HP'
update ehomsom..tbInfAirCompany  set airname='瑞士航空',sx1='瑞士航空', sx='瑞航',enairname='Swiss International Air Lines' where code2='LX'
update ehomsom..tbInfAirCompany  set airname='欧洲翼航空',sx1='欧洲翼航空', sx='欧洲翼航空',enairname='Eurowings' where code2='EW'
update ehomsom..tbInfAirCompany  set airname='牙买加航空',sx1='牙买加航空', sx='牙买加航空',enairname='Air Jamaica' where code2='JM'
update ehomsom..tbInfAirCompany  set airname='地平线航空',sx1='地平线航空', sx='地平线航空',enairname='Horizon Air' where code2='QX'
update ehomsom..tbInfAirCompany  set airname='欧洲航空',sx1='欧洲航空', sx='欧洲航空',enairname='Air Europa' where code2='UX'
update ehomsom..tbInfAirCompany  set airname='加那利航空',sx1='加那利航空', sx='加那利航空',enairname='Binter Canarias' where code2='NT'
update ehomsom..tbInfAirCompany  set airname='西藏航空',sx1='西藏航', sx='西藏航',enairname='Tibet Airlines' where code2='TV'
update ehomsom..tbInfAirCompany  set airname='国泰航空',sx1='国泰航空', sx='国泰航空',enairname='Cathay Pacific Airways' where code2='CX'
update ehomsom..tbInfAirCompany  set airname='河北航空',sx1='河北航空', sx='河北航空',enairname='Hebei Airlines' where code2='NS'
update ehomsom..tbInfAirCompany  set airname='东星航空',sx1='东星航空', sx='东星航空',enairname='Shanxi Airlines' where code2='8C'
update ehomsom..tbInfAirCompany  set airname='德国汉莎航空',sx1='德国汉莎航空', sx='汉莎',enairname='Deutsche Lufthansa Airlines' where code2='LH'
update ehomsom..tbInfAirCompany  set airname='吉尔吉斯坦国航空',sx1='吉尔吉斯坦国航空', sx='吉尔吉斯坦国航空',enairname='Kyrgyastan-EX' where code2='K2'
update ehomsom..tbInfAirCompany  set airname='马绍尔群岛航空',sx1='马绍尔群岛航空', sx='马绍尔群岛航空',enairname='Air Marshall Islands' where code2='CW'
update ehomsom..tbInfAirCompany  set airname='中国联航',sx1='中国联航', sx='中国联航',enairname='China United Airlines' where code2='KN'
update ehomsom..tbInfAirCompany  set airname='蓝色全景航空公司',sx1='蓝色全景航空', sx='蓝色全景航空',enairname='Blue Panorama Airlines' where code2='BV'
update ehomsom..tbInfAirCompany  set airname='鲲鹏航空',sx1='鲲鹏航空', sx='鲲鹏航空',enairname='Kun Peng Airlines' where code2='VD'
update ehomsom..tbInfAirCompany  set airname='老挝航空',sx1='老挝航空', sx='老挝航空',enairname='Lao Airlines' where code2='QV'
update ehomsom..tbInfAirCompany  set airname='中东航空',sx1='中东航空', sx='中东航空',enairname='Mea - Middle East Airlines' where code2='ME'
update ehomsom..tbInfAirCompany  set airname='维加斯航空',sx1='维加斯航空', sx='维加斯航空',enairname='Air Vanuatu' where code2='NF'
update ehomsom..tbInfAirCompany  set airname='马汉航空',sx1='马汉航空', sx='马汉航空',enairname='Mahan Airlines' where code2='W5'
update ehomsom..tbInfAirCompany  set airname='俄罗斯航空',sx1='俄罗斯航空', sx='俄航',enairname='Aeroflotrussian Airlines' where code2='SU'
update ehomsom..tbInfAirCompany  set airname='沙特阿拉伯航空',sx1='沙特阿拉伯航空', sx='沙特阿拉伯航空',enairname='Saudi Arabian Airlines' where code2='SV'
update ehomsom..tbInfAirCompany  set airname='大西地航空',sx1='大西地航空', sx='大西地航空',enairname='Air Tahiti Nui' where code2='TN'
update ehomsom..tbInfAirCompany  set airname='猎鹰航空',sx1='猎鹰航空', sx='猎鹰航空',enairname='无' where code2='IH'
update ehomsom..tbInfAirCompany  set airname='哈萨克斯坦航空',sx1='哈萨克斯坦航空', sx='哈萨克斯坦航空',enairname='Air Kazakhstan' where code2='9Y'
update ehomsom..tbInfAirCompany  set airname='马耳他航空公司',sx1='马耳他', sx='马耳他',enairname='Air Malta' where code2='KM'
update ehomsom..tbInfAirCompany  set airname='埃塞俄比亚航空',sx1='埃塞俄比亚航空', sx='埃塞俄比亚航空',enairname='Ethiopian Airlines Enterprise' where code2='ET'
update ehomsom..tbInfAirCompany  set airname='葡萄牙航空',sx1='葡萄牙航空', sx='葡萄牙航空',enairname='Tap - Air Portugal' where code2='TP'
update ehomsom..tbInfAirCompany  set airname='塞舌尔航空',sx1='塞舌尔航空', sx='塞舌尔航空',enairname='Air Seychelles' where code2='HM'
update ehomsom..tbInfAirCompany  set airname='意大利VOLARE航空',sx1='意大利VOLARE航空', sx='意大利VOLARE航空',enairname='Volareweb' where code2='VA'
update ehomsom..tbInfAirCompany  set airname='波兰航空',sx1='波兰航空', sx='波兰航空',enairname='Lot Polish Airlines' where code2='LO'
update ehomsom..tbInfAirCompany  set airname='WHYALLA航空',sx1='WHYALLA航空', sx='WHYALLA航空',enairname='Whyalla Airlines' where code2='WW'
update ehomsom..tbInfAirCompany  set airname='亚德里亚航空',sx1='亚德里亚航空', sx='亚德里亚航空',enairname='Adria Aviopromet' where code2='JP'
update ehomsom..tbInfAirCompany  set airname='马来西亚航空',sx1='马来西亚航空', sx='马航',enairname='Malaysia Airlines' where code2='MH'
update ehomsom..tbInfAirCompany  set airname='中国国航',sx1='国航', sx='国航',enairname='Air China' where code2='CA'
update ehomsom..tbInfAirCompany  set airname='圣保罗航空',sx1='圣保罗航空', sx='圣保罗航空',enairname='Viacao Aerea Sao Paulo (Vasp)' where code2='VP'
update ehomsom..tbInfAirCompany  set airname='美国大陆航空',sx1='美国大陆航空', sx='美国大陆航空',enairname='Continental Airlines' where code2='CO'
update ehomsom..tbInfAirCompany  set airname='匈牙利航空',sx1='匈牙利航空', sx='匈牙利航空',enairname='Malev-Hungarian Airlines' where code2='MA'
update ehomsom..tbInfAirCompany  set airname='美国联合航空',sx1='美国联合航空', sx='美联航',enairname='United Airlines' where code2='UA'
update ehomsom..tbInfAirCompany  set airname='斯里兰卡航空',sx1='斯里兰卡航空', sx='斯里兰卡航空',enairname='Srilankan Airlines' where code2='UL'
update ehomsom..tbInfAirCompany  set airname='康多尔航空',sx1='康多尔航空', sx='康多尔航空',enairname='Condor Flugdienst' where code2='DE'
update ehomsom..tbInfAirCompany  set airname='澳门航空',sx1='澳门航空', sx='澳门航空',enairname='Air Macau' where code2='NX'
update ehomsom..tbInfAirCompany  set airname='法国航空',sx1='法国航空', sx='法航',enairname='Air France' where code2='AF'
update ehomsom..tbInfAirCompany  set airname='南方航空',sx1='南航', sx='南航',enairname='China Southern Airlines' where code2='CZ'
update ehomsom..tbInfAirCompany  set airname='乌克兰国际航空',sx1='乌克兰航空', sx='乌克兰航空',enairname='Ukraine Airlines' where code2='PS'
update ehomsom..tbInfAirCompany  set airname='阿尔及利亚航空',sx1='阿国航空', sx='阿国航空',enairname='Air Algérie' where code2='AH'
update ehomsom..tbInfAirCompany  set airname='瑞士航空',sx1='瑞士航空', sx='瑞航',enairname='Swiss International Air Lines' where code2='SR'
update ehomsom..tbInfAirCompany  set airname='日本航空',sx1='日本航空', sx='日航',enairname='Japan Airlines' where code2='JL'
update ehomsom..tbInfAirCompany  set airname='环空航空',sx1='环空航空', sx='环空航空',enairname='Transaero Airlines' where code2='UN'
update ehomsom..tbInfAirCompany  set airname='捷星日本航空',sx1='捷星日本航空', sx='捷星航空',enairname='Jetstar Airways Pty Limited' where code2='GK'
update ehomsom..tbInfAirCompany  set airname='秘鲁福塞特航空',sx1='秘鲁福塞特航空', sx='秘鲁福塞特航空',enairname='City Airline' where code2='CF'
update ehomsom..tbInfAirCompany  set airname='冰岛航空',sx1='冰岛航空', sx='冰岛航空',enairname='Iceland Air' where code2='FI'
update ehomsom..tbInfAirCompany  set airname='叙利亚阿拉伯航空公司',sx1='叙利亚阿拉伯航空', sx='叙利亚阿拉伯航空',enairname='Syrian Arab Airlines' where code2='RB'
update ehomsom..tbInfAirCompany  set airname='新几内亚航空',sx1='新几内亚航空', sx='新几内亚航空',enairname='Air Niugini' where code2='PX'
update ehomsom..tbInfAirCompany  set airname='白俄罗斯航空',sx1='白俄罗斯航空', sx='白俄罗斯航空',enairname='Belavia Belarusian Airlines' where code2='B2'
update ehomsom..tbInfAirCompany  set airname='美国捷蓝航空公司',sx1='美国捷蓝航空公司', sx='捷蓝航空',enairname='JetBlue Airways' where code2='B6'
update ehomsom..tbInfAirCompany  set airname='静空国际航空',sx1='静空航空', sx='静空航空',enairname='Calm Air' where code2='MO'
update ehomsom..tbInfAirCompany  set airname='缅甸国际航空',sx1='缅甸国际航空', sx='缅甸国际航空',enairname='Myanmar Airways,' where code2='8M'
update ehomsom..tbInfAirCompany  set airname='重庆航空',sx1='重庆航空', sx='重庆航空',enairname='Chong Qing Airlines' where code2='OQ'
update ehomsom..tbInfAirCompany  set airname='巴拿马空运',sx1='巴拿马空运', sx='巴拿马空运',enairname='Copa Airlines' where code2='CM'
update ehomsom..tbInfAirCompany  set airname='拉德科智利航空',sx1='拉德智利航空', sx='拉德智利航空',enairname='Ladeco S.A.' where code2='UC'
update ehomsom..tbInfAirCompany  set airname='巴基斯坦国际航空',sx1='巴基斯坦国际航空', sx='巴基斯坦国际航空',enairname='Pakistanairlines' where code2='PK'
update ehomsom..tbInfAirCompany  set airname='华夏航空',sx1='华夏', sx='华夏',enairname='China Express Airlines' where code2='G5'
update ehomsom..tbInfAirCompany  set airname='博特尼亚航空',sx1='博特尼亚航空', sx='博特尼亚航空',enairname='Air Botnia' where code2='KF'
update ehomsom..tbInfAirCompany  set airname='突尼斯航空',sx1='突尼斯航空', sx='突尼斯航空',enairname='Tunis Air' where code2='TU'
update ehomsom..tbInfAirCompany  set airname='波罗的海航空',sx1='波罗的海航空', sx='波罗的海航空',enairname='Air Baltic Corporation' where code2='BT'
update ehomsom..tbInfAirCompany  set airname='摩洛哥皇家航空',sx1='摩皇家航空', sx='摩皇家航空',enairname='Royal Air Maroc Express' where code2='AT'
update ehomsom..tbInfAirCompany  set airname='暹粒国际航空',sx1='暹粒航空', sx='暹粒航空',enairname='Siem Reap Airways' where code2='FT'
update ehomsom..tbInfAirCompany  set airname='哥伦比亚国家航空',sx1='哥伦比亚国家航空', sx='哥伦比亚国家航空',enairname='ACES Colombia' where code2='AV'
update ehomsom..tbInfAirCompany  set airname='乌拉圭国家航空',sx1='乌拉圭航空', sx='乌拉圭航空',enairname='Pluna Lineas Aereas Uruguayas S.A' where code2='PU'
update ehomsom..tbInfAirCompany  set airname='吴哥航空',sx1='吴哥', sx='吴哥',enairname='Angkor Airways' where code2='K6'
update ehomsom..tbInfAirCompany  set airname='新疆航空',sx1='新疆航空', sx='新疆航空',enairname='China Xinjiang Airlines' where code2='XO'
update ehomsom..tbInfAirCompany  set airname='泰国曼谷航空',sx1='泰国曼谷航空', sx='泰国曼谷航空',enairname='Bangkok Airways' where code2='PG'
update ehomsom..tbInfAirCompany  set airname='赞比亚航空',sx1='赞比亚航空', sx='赞比亚航空',enairname='Aero Zambia' where code2='Z9'
update ehomsom..tbInfAirCompany  set airname='北欧航空',sx1='北欧航空', sx='北欧航空',enairname='Scandinavian Airlines' where code2='SK'
update ehomsom..tbInfAirCompany  set airname='毛里求斯航空',sx1='毛里求斯航空', sx='毛里求斯航空',enairname='Air Mauritius' where code2='MK'
update ehomsom..tbInfAirCompany  set airname='酷航',sx1='酷航', sx='酷航',enairname='Scoot Airways' where code2='TR'
update ehomsom..tbInfAirCompany  set airname='泰国微笑航空',sx1='泰国微笑', sx='泰国微笑',enairname='Thai Smile Air' where code2='WE'
update ehomsom..tbInfAirCompany  set airname='龙江航空',sx1='龙江航空', sx='龙江航空',enairname='Longjiang Airlines' where code2='LT'
update ehomsom..tbInfAirCompany  set airname='瑞丽航空',sx1='瑞丽航空', sx='瑞丽航空',enairname='Ruili Airlines' where code2='DR'
update ehomsom..tbInfAirCompany  set airname='俄罗斯普尔科沃航空',sx1='俄罗斯普尔科沃航空', sx='俄罗斯普尔科沃航空',enairname='Pulkovo Airlines' where code2='FV'
update ehomsom..tbInfAirCompany  set airname='俄罗斯西北利亚航空',sx1='俄罗斯西北利亚航空', sx='俄罗斯西北利亚航空',enairname='Siberia Airlines' where code2='S7'
update ehomsom..tbInfAirCompany  set airname='葡萄牙航空',sx1='葡萄牙航空', sx='葡萄牙航空',enairname='TAP Air Portugal' where code2='NI'
update ehomsom..tbInfAirCompany  set airname='阿里亚纳阿富汗',sx1='阿里亚纳阿富汗', sx='阿里亚纳阿富汗',enairname='Ariana Afghan Airlines' where code2='FG'
update ehomsom..tbInfAirCompany  set airname='布拉森斯南美和远东空运',sx1='布拉森斯南美和远东空运', sx='布拉森斯南美和远东空运',enairname='Braathens Safe Air Transport' where code2='BU'
update ehomsom..tbInfAirCompany  set airname='越南航空',sx1='越南航空', sx='越航',enairname='Vietnam Airlines' where code2='VN'
update ehomsom..tbInfAirCompany  set airname='港龙航空',sx1='港龙航空', sx='港龙',enairname='Hong Kong Dragon Airlines' where code2='KA'
update ehomsom..tbInfAirCompany  set airname='马拉维航空',sx1='马拉维航空', sx='马拉维航空',enairname='Air Malawi' where code2='QM'
update ehomsom..tbInfAirCompany  set airname='津巴布韦航空',sx1='津巴布韦航空', sx='津巴布韦航空',enairname='Air Zimbabwe' where code2='UM'
update ehomsom..tbInfAirCompany  set airname='上海航空',sx1='上航', sx='上航',enairname='Shanghai Airlines' where code2='FM'
update ehomsom..tbInfAirCompany  set airname='福州航空',sx1='福州航空', sx='福州航空',enairname='Fuzhou Airlines' where code2='FU'
update ehomsom..tbInfAirCompany  set airname='尼泊尔皇家航空',sx1='尼泊尔皇家航空', sx='尼泊尔皇家航空',enairname='Royal Nepal Airlines' where code2='RA'
update ehomsom..tbInfAirCompany  set airname='克罗地亚航空',sx1='克罗地亚航空', sx='克罗地亚航空',enairname='Croatia Airlines' where code2='OU'
update ehomsom..tbInfAirCompany  set airname='首都航空',sx1='首航', sx='首航',enairname='Deer Airlines' where code2='JD'
update ehomsom..tbInfAirCompany  set airname='泰国金狮航空',sx1='泰国金狮航空', sx='泰国金狮航空',enairname='British Caledonian(BCal)' where code2='9Q'
update ehomsom..tbInfAirCompany  set airname='春秋航空',sx1='春秋', sx='春秋',enairname='Spring Airline' where code2='9C'
update ehomsom..tbInfAirCompany  set airname='达美航空',sx1='达美航空', sx='达美航空',enairname='Delta Air Lines' where code2='DL'
update ehomsom..tbInfAirCompany  set airname='亚洲航空',sx1='亚洲航空', sx='亚洲航空',enairname='Aero Asia International(Private)' where code2='E4'
update ehomsom..tbInfAirCompany  set airname='新西兰航空',sx1='新西兰航空', sx='NULL',enairname='Air New Zealand' where code2='NZ'
update ehomsom..tbInfAirCompany  set airname='塞浦路斯航空',sx1='塞浦路斯航空', sx='塞浦路斯航空',enairname='Cyprus Airways' where code2='CY'
update ehomsom..tbInfAirCompany  set airname='伏尔加第聂伯航空',sx1='伏尔加航空', sx='伏尔加航空',enairname='Volga-Dnepr Airline' where code2='VI'
update ehomsom..tbInfAirCompany  set airname='深圳航空',sx1='深航', sx='深航',enairname='Shenzhen Airlines' where code2='ZH'
update ehomsom..tbInfAirCompany  set airname='南斯拉夫航空',sx1='南斯拉夫航空', sx='南斯拉夫航空',enairname='Jat Yugoslav Airlines' where code2='JU'
update ehomsom..tbInfAirCompany  set airname='瓦力格航空',sx1='瓦力格航空', sx='瓦力格航空',enairname='VRG' where code2='LC'
update ehomsom..tbInfAirCompany  set airname='卢森堡航空',sx1='卢森堡航空', sx='卢森堡航空',enairname='Luxair' where code2='LG'
update ehomsom..tbInfAirCompany  set airname='天津航空',sx1='天津航空', sx='天津航空',enairname='Tianjin Airlines' where code2='GS'
update ehomsom..tbInfAirCompany  set airname='维尔京蓝航空',sx1='维尔京蓝航空', sx='维尔京蓝航空',enairname='Virgin Samoa' where code2='DJ'
update ehomsom..tbInfAirCompany  set airname='默里迪恩纳航空',sx1='默里迪恩航空', sx='默里迪恩航空',enairname='Meridiana Fly' where code2='IG'
update ehomsom..tbInfAirCompany  set airname='多彩贵州航空',sx1='多彩贵州航空', sx='多彩贵州航空',enairname='Colorful Guizhou Airlines' where code2='GY'
update ehomsom..tbInfAirCompany  set airname='日本jalways 航空',sx1='日本jalways 航空', sx='日本jalways 航空',enairname='Jalways ,Ltd' where code2='JO'
update ehomsom..tbInfAirCompany  set airname='澜湄航空',sx1='澜湄航空', sx='澜湄航空',enairname='Lanmei Airlines(Cambodia)Co.,Ltd' where code2='LQ'
update ehomsom..tbInfAirCompany  set airname='威德罗航空',sx1='威德罗航空', sx='威德罗航空',enairname='Wider?E' where code2='WF'
update ehomsom..tbInfAirCompany  set airname='暹罗航空',sx1='暹罗航空', sx='暹罗航空',enairname='Siam Air' where code2='O8'
update ehomsom..tbInfAirCompany  set airname='加拿大航空',sx1='加拿大航空', sx='加航',enairname='Air Canada' where code2='AC'
update ehomsom..tbInfAirCompany  set airname='幸福航空',sx1='幸福航空', sx='幸福航空',enairname='Joy Airlines' where code2='JR'
update ehomsom..tbInfAirCompany  set airname='英国中部航空',sx1='英国中部航空', sx='英国中部航空',enairname='British Midland' where code2='BD'
update ehomsom..tbInfAirCompany  set airname='乌兹别克斯坦航空',sx1='乌兹别克斯坦航空', sx='乌兹别克斯坦航空',enairname='Uzbekistan Airways' where code2='HY'
update ehomsom..tbInfAirCompany  set airname='孟加拉航空',sx1='孟加拉航空', sx='孟加拉航空',enairname='Biman Bangladesh Airlines' where code2='BG'
update ehomsom..tbInfAirCompany  set airname='香港航空',sx1='香港航空', sx='香港航空',enairname='Hong Kong Airlines' where code2='HX'
update ehomsom..tbInfAirCompany  set airname='利比亚泛非航空',sx1='利国泛非航空', sx='利国泛非航空',enairname='Afriqiyah Airways' where code2='8U'
update ehomsom..tbInfAirCompany  set airname='阿曼航空公司',sx1='阿曼航', sx='阿曼航',enairname='Oman Aviation' where code2='WY'
update ehomsom..tbInfAirCompany  set airname='苏里南航空',sx1='苏里南航空', sx='苏里南航空',enairname='Surinam Airways' where code2='PY'
update ehomsom..tbInfAirCompany  set airname='卡塔尔航空',sx1='卡塔尔航空', sx='卡航',enairname='Qatar Airways' where code2='QR'
update ehomsom..tbInfAirCompany  set airname='加拿大WESTJET航空',sx1='加拿大WESTJET航空', sx='加拿大WESTJET航空',enairname='Westjet' where code2='WS'
update ehomsom..tbInfAirCompany  set airname='新加坡酷航航空',sx1='酷航航空', sx='酷航航空',enairname='Scoot' where code2='TZ'
update ehomsom..tbInfAirCompany  set airname='西班牙伏林航空',sx1='西班牙伏林', sx='西班牙伏林',enairname='Vuelingairlines' where code2='VY'
update ehomsom..tbInfAirCompany  set airname='华信航空',sx1='华信航空', sx='华信航空',enairname='Mandarin Airlines' where code2='AE'
update ehomsom..tbInfAirCompany  set airname='青岛航空',sx1='青岛航空', sx='青岛航空',enairname='Qingdao Airlines' where code2='QW'
update ehomsom..tbInfAirCompany  set airname='肯尼亚航空',sx1='肯尼亚航空', sx='肯航',enairname='Kenya Airways' where code2='KQ'
update ehomsom..tbInfAirCompany  set airname='厦门航空',sx1='厦航', sx='厦航',enairname='Xiamen Airlines' where code2='MF'
update ehomsom..tbInfAirCompany  set airname='意大利航',sx1='意大利航', sx='意航',enairname='Alitalia Linee Aeree Italiane Spa' where code2='AZ'
update ehomsom..tbInfAirCompany  set airname='立陶宛航空',sx1='立陶宛航空', sx='立陶宛航空',enairname='Lithuanian Airlines' where code2='TE'
update ehomsom..tbInfAirCompany  set airname='古巴统一航空',sx1='古巴统一航空', sx='古巴统一航空',enairname='Cubana de Aviación' where code2='CU'
update ehomsom..tbInfAirCompany  set airname='金鹏航空',sx1='金鹏航空', sx='金鹏航空',enairname='Transmile Air Services' where code2='Y8'
update ehomsom..tbInfAirCompany  set airname='赞比亚航空',sx1='赞比亚航空', sx='赞比亚航空',enairname='Zambian Airways' where code2='Q3'
update ehomsom..tbInfAirCompany  set airname='四川航空',sx1='川航', sx='川航',enairname='Sichuan Airlines' where code2='3U'
update ehomsom..tbInfAirCompany  set airname='乌克兰航空',sx1='乌克兰航空', sx='乌克兰航空',enairname='Aerosvit Airlines' where code2='VV'
update ehomsom..tbInfAirCompany  set airname='泰国亚洲航空公司',sx1='泰国亚洲航空', sx='泰国亚洲航空',enairname='Thai Air Asia' where code2='FD'
update ehomsom..tbInfAirCompany  set airname='乌鲁木齐航空',sx1='乌鲁木齐航空', sx='乌鲁木齐航空',enairname='Urumqi Air' where code2='UQ'
update ehomsom..tbInfAirCompany  set airname='乌克兰航空',sx1='乌克兰航空', sx='乌克兰航空',enairname='Air Ukraine' where code2='6U'
update ehomsom..tbInfAirCompany  set airname='细甸国际航空',sx1='细甸国际航空', sx='细甸国际航空',enairname='Myanmar Airways' where code2='UB'
update ehomsom..tbInfAirCompany  set airname='马印航空',sx1='马印航空', sx='马印航空',enairname='Natalcoairlines' where code2='OD'
update ehomsom..tbInfAirCompany  set airname='土耳其航空',sx1='土耳其航空', sx='土航',enairname='Turkish Airlines' where code2='TK'
update ehomsom..tbInfAirCompany  set airname='维珍美国航空',sx1='维珍航空', sx='维珍航空',enairname='Virgin America' where code2='VX'
update ehomsom..tbInfAirCompany  set airname='中国西北航空',sx1='中国西北航空', sx='中国西北航空',enairname='Xibei Airlines' where code2='WH'
update ehomsom..tbInfAirCompany  set airname='秘鲁航空',sx1='秘鲁航空', sx='秘鲁航空',enairname='Aeroperu' where code2='PL'
update ehomsom..tbInfAirCompany  set airname='江西航空',sx1='江西航', sx='江西航',enairname='Jiangxi Airlines' where code2='RY'
update ehomsom..tbInfAirCompany  set airname='阿提哈德航空',sx1='阿提哈德航空', sx='阿提哈德航空',enairname='Etihad Airways' where code2='EY'
update ehomsom..tbInfAirCompany  set airname='奥林匹克航空',sx1='奥林匹克航空', sx='奥林匹克航空',enairname='Olympic Airways' where code2='OA'
update ehomsom..tbInfAirCompany  set airname='阿塞拜疆航空',sx1='阿塞拜疆航空', sx='阿塞拜疆航空',enairname='Azal Azerbaijan Airlines' where code2='J2'
update ehomsom..tbInfAirCompany  set airname='法国国内航空',sx1='法国国内航空', sx='法国国内航空',enairname='Air France' where code2='AF'
update ehomsom..tbInfAirCompany  set airname='宿雾航空',sx1='宿雾航空', sx='宿雾航空',enairname='Cebu Pacific' where code2='5J'
update ehomsom..tbInfAirCompany  set airname='喀麦隆航空',sx1='喀麦隆航空', sx='喀麦隆航空',enairname='Cameroon Airlines' where code2='UY'
update ehomsom..tbInfAirCompany  set airname='英国航空',sx1='英国航空', sx='英航',enairname='British Airways' where code2='BA'
update ehomsom..tbInfAirCompany  set airname='中西部捷运',sx1='中西部捷运', sx='中西部捷运',enairname='Midwest Express Airlines .' where code2='YX'
update ehomsom..tbInfAirCompany  set airname='长安航空',sx1='长安航空', sx='长安航空',enairname='Chang An Airlines' where code2='9H'
update ehomsom..tbInfAirCompany  set airname='塔希提航空',sx1='塔希提航空', sx='塔希提航空',enairname='Air Tahiti' where code2='VT'
update ehomsom..tbInfAirCompany  set airname='斯威士兰皇家航空',sx1='斯威士兰航空', sx='斯威士兰航空',enairname='Royal Swazi National Airways' where code2='ZC'
update ehomsom..tbInfAirCompany  set airname='印尼亚洲航空公司',sx1='印尼亚航', sx='印尼亚航',enairname='Airasia Airline' where code2='QZ'
--删除错误信息
delete ehomsom..tbInfAirCompany where code2='EF'