---
- hosts: 
  - ceph
  gather_facts: yes
  tasks:
    - name: register vars
      shell: hostname
      register: info
    - name: display vars
      debug: msg="{{info.stdout}}"

    - name: test hosts var
      debug: msg="role {{ role }}, author {{ author }}"

