{
 "title": "Kubernetes Cluster",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter, nginx ingress controller",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(up{job=~\"kubernetes-node\"},job)"
   },
   {
    "name": "job_cadvisor",
    "label": "job_cadvisor",
    "query": "label_values(up{job=\"kubernetes-node-cadvisor\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Resource",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{job=\"$job\"}) by (instance,job)"
    },
    {
     "expr": "node_os_info{job=\"$job\"}"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"$job\", mode='system'}) by (instance)"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{job=\"$job\"}) by(instance)"
    },
    {
     "expr": "avg((node_filesystem_size_bytes{job=\"$job\",fstype=~\"ext4|xfs\",mountpoint=\"/\"}-node_filesystem_avail_bytes{job=\"$job\",fstype=~\"ext4|xfs\",mountpoint=\"/\"})/node_filesystem_size_bytes{job=\"$job\",fstype=~\"ext4|xfs\",mountpoint=\"/\"} * 100) by (instance)"
    },
    {
     "expr": "avg(node_filesystem_size_bytes{job=\"$job\",fstype=~\"ext4|xfs\",mountpoint=\"/\"}) by (instance)"
    },
    {
     "expr": "avg((1 - ( (node_memory_Buffers_bytes{job=\"$job\"} + node_memory_Cached_bytes{job=\"$job\"} + node_memory_MemFree_bytes{job=\"$job\"}) / node_memory_MemTotal_bytes{job=\"$job\"}) )* 100) by (instance)"
    },
    {
     "expr": "(sum(avg(irate(node_cpu_seconds_total{job=\"$job\",mode!=\"idle\"}[5m])) without(cpu))  by(instance)) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage(avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[5m])) "
    }
   ]
  },
  {
   "title": "Memory Usage (avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 6 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(((node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemAvailable_bytes{job=\"$job\"})/node_memory_MemTotal_bytes{job=\"$job\"}))"
    }
   ]
  },
  {
   "title": "Storage Usage(avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 6 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"} - node_filesystem_avail_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"}) / node_filesystem_size_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"})"
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"kubernetes-kube-state-metric\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Restart Pods number(1h)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[1h]) > 0) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",device=~'eth.*'}[5m])*8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Sent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\",device=~'eth.*'}[5m])*8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"$job\"} + node_memory_Buffers_bytes{job=\"$job\"} + node_memory_Cached_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"} /node_filesystem_size_bytes{job=\"$job\",mountpoint!~\".*(serviceaccount|proc|sys).*\", device!~\"overlay|tmpfs\"}",
     "legendFormat": "{{instance}} | {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IO/ps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{job=\"$job\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Top 10 Pods for Usage Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_usage_bytes{job=\"$job_cadvisor\",image!=\"\",container!=\"POD\"}) by(pod,namespace,job))",
     "legendFormat": "{{ namespace }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Top 10 Container for Usage Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_usage_bytes{job=\"$job_cadvisor\",image!=\"\",container!=\"POD\"}) by(container,pod,namespace,job))",
     "legendFormat": "{{ namespace }} | {{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "Top 10  Pod for Usage CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(irate(container_cpu_usage_seconds_total{image!=\"\",job=\"$job_cadvisor\",container!=\"POD\"}[5m])) by (pod,namespace) * 1000)",
     "legendFormat": "{{namespace}} | {{pod}} | {{container}} "
    }
   ]
  },
  {
   "title": "Top 10  Containers for Usage CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(irate(container_cpu_usage_seconds_total{image!=\"\",job=\"$job_cadvisor\",container!=\"POD\"}[5m])) by (container,pod,namespace) * 1000)",
     "legendFormat": "{{nemaspace}} | {{pod}} | {{container}}"
    }
   ]
  }
 ]
}