{
 "title": "Kubernetes Pods",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers",
 "tags": [
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{kubernetes_io_hostname=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{kubernetes_io_hostname=\"$Node\"}"
    }
   ]
  },
  {
   "title": "All Pod CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node\",container!=\"POD\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "All Pod Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=\"$Node\",container!=\"POD\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "All Pod Cpu Usage(mCores)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node\",container!=\"POD\"}[5m])) * 1000"
    }
   ]
  },
  {
   "title": "All Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=\"$Node\",container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "All Pod Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{kubernetes_io_hostname=\"$Node\",container=\"POD\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{kubernetes_io_hostname=\"$Node\",container=\"POD\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "All Pod Read/Write Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{kubernetes_io_hostname=\"$Node\",container=~\"[a-z].*\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{kubernetes_io_hostname=\"$Node\",container=~\"[a-z].*\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Pods CPU Usage (mCores)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node\",container!=\"POD\"}[5m])) by (pod,namespace) * 1000",
     "legendFormat": "{{namespace}} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Network Sent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{kubernetes_io_hostname=\"$Node\",container=\"POD\"}[5m])) by (pod,namespace)",
     "legendFormat": "{{ namespace }} | {{pod}}"
    }
   ]
  },
  {
   "title": "Pod Network Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{kubernetes_io_hostname=\"$Node\",container=\"POD\"}[5m])) by (pod,namespace)",
     "legendFormat": "{{ namespace }} | {{pod}}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=\"$Node\",container!=\"POD\"}) by (pod,namespace)",
     "legendFormat": "{{ namespace }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod  Read Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{kubernetes_io_hostname=\"$Node\",container=~\"[a-z].*\"}[5m])) by (pod,namespace)",
     "legendFormat": "{{ namespace }} | {{pod}}"
    }
   ]
  },
  {
   "title": "Pod  Write Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{kubernetes_io_hostname=\"$Node\",container=~\"[a-z].*\"}[5m])) by (pod,namespace)",
     "legendFormat": "{{ namespace }} | {{pod}}"
    }
   ]
  },
  {
   "title": "Containers CPU Usage(cores/m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\",container!=\"POD\"}[5m]) * 1000",
     "legendFormat": "{{ namespace }} | {{ pod}} | {{ container}}"
    }
   ]
  },
  {
   "title": "Containers Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=\"$Node\",container!=\"POD\"}",
     "legendFormat": "{{ namespace }} | {{ pod }} | {{ container}}"
    }
   ]
  },
  {
   "title": "Container  Read Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{kubernetes_io_hostname=\"$Node\",container=~\"[a-z].*\"}[5m])) by (container,pod,namespace)",
     "legendFormat": "{{ namespace }} | {{ pod}} | {{ container}}"
    }
   ]
  },
  {
   "title": "Container  Write Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{kubernetes_io_hostname=\"$Node\",container=~\"[a-z].*\"}[5m])) by (container,pod,namespace)",
     "legendFormat": "{{ namespace }} | {{ pod}} | {{ container}}"
    }
   ]
  }
 ]
}