apiVersion: v1
kind: Pod
metadata: 
  name: pod-sa-demo
  namespace: default
  labels: 
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
  serviceAccountName: admin
