{
 "title": "Kubernetes Cluster Monitoring",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Node",
    "query": "label_values(container_memory_working_set_bytes{job=\"kubelet\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{instance=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{instance=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$Node$\"}) / sum (machine_memory_bytes{instance=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage ($interval avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$Node$\"}[$interval])) / sum (machine_cpu_cores{instance=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev.*$\",id=\"/\",instance=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev.*$\",id=\"/\",instance=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$Node$\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev.*\",id=\"/\",instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev.*\",id=\"/\",instance=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pods CPU usage ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[$interval])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "System services CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "System services CPU usage ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=~\"/system.slice/.*\",instance=~\"^$Node$\"}[$interval])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  { "title": "Containers CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Containers CPU usage ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",instance=~\"^$Node$\"}[$interval])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",instance=~\"^$Node$\"}[$interval])) by (instance, name, image)",
     "legendFormat": "docker: {{ instance }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",instance=~\"^$Node$\"}[$interval])) by (instance, rkt_container_name)",
     "legendFormat": "rkt: {{ instance }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage ($interval avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",instance=~\"^$Node$\"}[$interval])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  { "title": "System services memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "System services memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=~\"/system.slice/.*\",instance=~\"^$Node$\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",instance=~\"^$Node$\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",instance=~\"^$Node$\"}) by (instance, name, image)",
       "legendFormat": "docker: {{ instance }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",instance=~\"^$Node$\"}) by (instance, rkt_container_name)",
       "legendFormat": "rkt: {{ instance }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",instance=~\"^$Node$\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network I/O ($interval avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[$interval])) by (pod_name)",
       "legendFormat": "-> {{ pod_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[$interval])) by (pod_name)",
       "legendFormat": "<- {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers network I/O ($interval avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[$interval])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[$interval])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",instance=~\"^$Node$\"}[$interval])) by (instance, name, image)",
       "legendFormat": "-> docker: {{ instance }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",instance=~\"^$Node$\"}[$interval])) by (instance, name, image)",
       "legendFormat": "<- docker: {{ instance }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",instance=~\"^$Node$\"}[$interval])) by (instance, rkt_container_name)",
       "legendFormat": "-> rkt: {{ instance }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",instance=~\"^$Node$\"}[$interval])) by (instance, rkt_container_name)",
       "legendFormat": "<- rkt: {{ instance }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  { "title": "All processes network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "All processes network I/O ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",instance=~\"^$Node$\"}[$interval])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",instance=~\"^$Node$\"}[$interval])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}