{
 "title": "MySQL TokuDB Metrics",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_global_variables_tokudb_cache_size, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$host</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1>"
  },
  {
   "title": "TokuDB Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_tokudb_cache_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "TokuDB Block Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_tokudb_block_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "TokuDB Block Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_tokudb_read_block_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "TokuDB FanOut",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_tokudb_fanout{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "TokuDB Checkpoint Period",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_tokudb_checkpointing_period{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "TokuDB Flush Log on Commit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_tokudb_commit_sync{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "TokuDB DirectIO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_tokudb_directio{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Current Compression Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_tokudb_overall_node_compression_ratio{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Transactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_txn_begin{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_txn_begin{instance=~\"$host\"}[5m])",
       "legendFormat": "Transactions Started "
      },
      {
       "expr": "rate(mysql_global_status_tokudb_txn_begin_read_only{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_txn_begin_read_only{instance=~\"$host\"}[5m])",
       "legendFormat": "Read Only Transactions Started"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_txn_commits{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_txn_commits{instance=~\"$host\"}[5m])",
       "legendFormat": "Transactons Committed"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_txn_aborts{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_txn_aborts{instance=~\"$host\"}[5m])",
       "legendFormat": "Transactions Aborted"
      }
     ]
    },
    {
     "title": "TokuDB Messages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops", "label": "Messages" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_messages_injected_at_root{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_messages_injected_at_root{instance=~\"$host\"}[5m])",
       "legendFormat": "Normal Messages Injected"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_broadcase_messages_injected_at_root{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_broadcase_messages_injected_at_root{instance=~\"$host\"}[5m])",
       "legendFormat": "Broadcase Messages Injected"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_messages_injected_at_root_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_messages_injected_at_root_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Total Size of Messages Injected"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_messages_flushed_from_h1_to_leaves_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_messages_flushed_from_h1_to_leaves_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Total Size of Messages Flushed to Leaves"
      }
     ]
    },
    {
     "title": "TokuDB Compression/Serialization Resource Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_compression_to_memory_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_compression_to_memory_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Compression Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_decompression_to_memory_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_decompression_to_memory_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Decompression Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_serialization_to_memory_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_serialization_to_memory_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Serialization Load "
      },
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_deserialization_to_memory_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_deserialization_to_memory_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Deserialization Load "
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_compression_to_memory_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_compression_to_memory_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Leaf Compression Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_decompression_to_memory_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_decompression_to_memory_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Leaf Decompression Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_serialization_to_memory_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_serialization_to_memory_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Leaf Serialization Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_deserialization_to_memory_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_deserialization_to_memory_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Lead Deserialization"
      }
     ]
    },
    {
     "title": "TokuDB Injections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_injections_at_depth_0{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_0{instance=~\"$host\"}[5m])",
       "legendFormat": "Depth  0 Injections"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_injections_at_depth_1{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_1{instance=~\"$host\"}[5m])",
       "legendFormat": "Depth 1 Injections"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_injections_at_depth_2{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_2{instance=~\"$host\"}[5m])",
       "legendFormat": "Depth 2 Injections"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_injections_at_depth_3{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_3{instance=~\"$host\"}[5m])",
       "legendFormat": "Depth 3 Injections"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_injections_lower_than_depth_3{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_lower_than_depth_3{instance=~\"$host\"}[5m])",
       "legendFormat": "Depth Lower than 3 Injections"
      }
     ]
    },
    {
     "title": "TokuDB Promotion Stopped Reason",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_stopped_nonempty_buffer{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_nonempty_buffer{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Empty Buffer"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_stopped_at_height_1{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_at_height_1{instance=~\"$host\"}[5m])",
       "legendFormat": "Reached Height 1 "
      },
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_stopped_child_locked_or_not_in_memory{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_child_locked_or_not_in_memory{instance=~\"$host\"}[5m])",
       "legendFormat": "Child Locked or Not in Memory"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_stopped_child_not_fully_in_memory{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_child_not_fully_in_memory{instance=~\"$host\"}[5m])",
       "legendFormat": "Child Not Fully in Memory"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_promotion_stopped_after_locking_child{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_after_locking_child{instance=~\"$host\"}[5m])",
       "legendFormat": "After Locking Child"
      }
     ]
    },
    {
     "title": "TokuDB Nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_nodes_created{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_created{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Nodes Created"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_created{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_created{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Leaf Nodes Created"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_nodes_destroyed{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_destroyed{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Nodes Destroyed"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_destroyed{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_destroyed{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Leaf Nodes Destroyed"
      }
     ]
    },
    {
     "title": "TokuDB Wasteful Activities",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_messages_ignored_by_leaf_due_to_msn{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_messages_ignored_by_leaf_due_to_msn{instance=~\"$host\"}[5m])",
       "legendFormat": "Dupplicate Messages Delivered to Leaves"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_cursor_skip_deleted_leaf_entry{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cursor_skip_deleted_leaf_entry{instance=~\"$host\"}[5m])",
       "legendFormat": "Deleted Leaf Entries Scanned"
      },
      {
       "expr": "1-rate(mysql_global_status_tokudb_leaf_entry_apply_gc_bytes_out{instance=~\"$host\"}[1h])/rate(mysql_global_status_tokudb_leaf_entry_apply_gc_bytes_in{instance=~\"$host\"}[1h])",
       "legendFormat": "Leaves Garbage Percent (1h avg)"
      }
     ]
    },
    {
     "title": "TokuDB Open Databases",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(mysql_global_status_tokudb_db_open_current{instance=~\"$host\"}[$interval]) or max_over_time(mysql_global_status_tokudb_db_open_current{instance=~\"$host\"}[5m])",
       "legendFormat": "TokuDB Databases Currently Open"
      },
      {
       "expr": "mysql_global_status_tokudb_db_open_max{instance=~\"$host\"}",
       "legendFormat": "Max TokuDB Open Databases"
      }
     ]
    }
   ]
  },
  {
   "title": "Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB CacheTable Overview",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_tokudb_cachetable_size_limit{instance=~\"$host\"}",
       "legendFormat": "CacheTable Size Limit"
      },
      {
       "expr": "mysql_global_status_tokudb_cachetable_size_current{instance=~\"$host\"}",
       "legendFormat": "CacheTable Size Current"
      },
      {
       "expr": "mysql_global_status_tokudb_cachetable_size_leaf{instance=~\"$host\"}",
       "legendFormat": "Caching Leaf Data"
      },
      {
       "expr": "mysql_global_status_tokudb_cachetable_size_nonleaf{instance=~\"$host\"}",
       "legendFormat": "Caching Non Leaf Data"
      }
     ]
    },
    {
     "title": "TokuDB CacheTable Special",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(mysql_global_status_tokudb_cachetable_size_cloned{instance=~\"$host\"}[$interval]) or max_over_time(mysql_global_status_tokudb_cachetable_size_cloned{instance=~\"$host\"}[5m]) ",
       "legendFormat": "Cloned CacheTable Size"
      },
      {
       "expr": "max_over_time(mysql_global_status_tokudb_cachetable_size_rollback{instance=~\"$host\"}[$interval]) or max_over_time(mysql_global_status_tokudb_cachetable_size_rollback{instance=~\"$host\"}[5m])",
       "legendFormat": "Rollback CacheTable Size"
      },
      {
       "expr": "max_over_time(mysql_global_status_tokudb_cachetable_size_writing{instance=~\"$host\"}[$interval]) or max_over_time(mysql_global_status_tokudb_cachetable_size_writing{instance=~\"$host\"}[5m]) ",
       "legendFormat": "Writing CacheTable Size"
      }
     ]
    },
    {
     "title": "Cache Pressure",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_tokudb_cachetable_size_cachepressure{instance=~\"$host\"}/mysql_global_status_tokudb_cachetable_size_current{instance=~\"$host\"}",
       "legendFormat": "Cache Pressure Ratio"
      }
     ]
    },
    {
     "title": "CacheTable Events",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Misses/Evictions" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_cachetable_evictions{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_evictions{instance=~\"$host\"}[5m])",
       "legendFormat": "Evictions"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_cachetable_miss{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_miss{instance=~\"$host\"}[5m])",
       "legendFormat": "Misses"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_cachetable_miss_time{instance=~\"$host\"}[$interval])/1000000 or irate(mysql_global_status_tokudb_cachetable_miss_time{instance=~\"$host\"}[5m])/100000",
       "legendFormat": "Misses Load "
      },
      {
       "expr": "rate(mysql_global_status_tokudb_cachetable_prefetches{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_prefetches{instance=~\"$host\"}[$interval])",
       "legendFormat": "Prefetches"
      }
     ]
    },
    {
     "title": "Partial Evictions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Eviction Counts" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_node_partial_evictions{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_node_partial_evictions{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Partial Evictions"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_node_partial_evictions{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_node_partial_evictions{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Leaf Partial Evictions"
      },
      {
       "expr": "(rate(mysql_global_status_tokudb_leaf_node_partial_evictions_bytes{instance=~\"$host\"}[$interval]) + rate(mysql_global_status_tokudb_nonleaf_node_partial_evictions_bytes{instance=~\"$host\"}[$interval])) or (irate(mysql_global_status_tokudb_leaf_node_partial_evictions_bytes{instance=~\"$host\"}[5m]) + irate(mysql_global_status_tokudb_nonleaf_node_partial_evictions_bytes{instance=~\"$host\"}[5m]))",
       "legendFormat": "Evicted Bytes"
      }
     ]
    },
    {
     "title": "Full Evictions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Eviction Counts" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_node_full_evictions{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_node_full_evictions{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Full Evictions"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_node_full_evictions{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_node_full_evictions{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Leaf Full Evictions"
      },
      {
       "expr": "(rate(mysql_global_status_tokudb_leaf_node_full_evictions_bytes{instance=~\"$host\"}[$interval]) + rate(mysql_global_status_tokudb_nonleaf_node_full_evictions_bytes{instance=~\"$host\"}[$interval])) or (irate(mysql_global_status_tokudb_leaf_node_full_evictions_bytes{instance=~\"$host\"}[5m]) + irate(mysql_global_status_tokudb_nonleaf_node_full_evictions_bytes{instance=~\"$host\"}[5m]))",
       "legendFormat": "Evicted Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpointing and Flushing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Checkpointing Summary",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_checkpoint_taken{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_checkpoint_taken{instance=~\"$host\"}[5m])",
       "legendFormat": "Checkpoints Taken"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_checkpoint_duration{instance=~\"$host\"}[1h])",
       "legendFormat": "Avg Checkpoint Load (1h)"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_checkpoint_begin_time{instance=~\"$host\"}[$interval])/1000000 or irate(mysql_global_status_tokudb_checkpoint_begin_time{instance=~\"$host\"}[5m])/1000000",
       "legendFormat": "Critical Section (Begin) Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_checkpoint_end_time{instance=~\"$host\"}[$interval])/1000000 or irate(mysql_global_status_tokudb_checkpoint_end_time{instance=~\"$host\"}[5m])/1000000",
       "legendFormat": "Non Critical Section (End) Load"
      },
      {
       "expr": "(rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{instance=~\"$host\"}[$interval])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{instance=~\"$host\"}[$interval])) or (irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{instance=~\"$host\"}[5m])+irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{instance=~\"$host\"}[5m]))",
       "legendFormat": "Disk Flush Load"
      }
     ]
    },
    {
     "title": "TokuDB Checkpoint Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s", "label": "Avg Time" }
     ],
     "targets": [
      {
       "expr": "(rate(mysql_global_status_tokudb_checkpoint_begin_time{instance=~\"$host\"}[$interval])/1000000/rate(mysql_global_status_tokudb_checkpoint_taken{instance=~\"$host\"}[$interval])) or (irate(mysql_global_status_tokudb_checkpoint_begin_time{instance=~\"$host\"}[5m])/1000000/irate(mysql_global_status_tokudb_checkpoint_taken{instance=~\"$host\"}[5m]))",
       "legendFormat": "Avg Critical Section Time"
      },
      {
       "expr": "(rate(mysql_global_status_tokudb_checkpoint_end_time{instance=~\"$host\"}[$interval])/1000000/rate(mysql_global_status_tokudb_checkpoint_taken{instance=~\"$host\"}[$interval])) or ((irate(mysql_global_status_tokudb_checkpoint_end_time{instance=~\"$host\"}[5m])/1000000/irate(mysql_global_status_tokudb_checkpoint_taken{instance=~\"$host\"}[5m])))",
       "legendFormat": "Avg Non Critical Section Time"
      },
      {
       "expr": "(rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{instance=~\"$host\"}[1h])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{instance=~\"$host\"}[1h]))/rate(mysql_global_status_tokudb_checkpoint_taken{instance=~\"$host\"}[1h])",
       "legendFormat": "Bytes Flushed Per Checkpoint (1h avg)"
      },
      {
       "expr": "(rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_uncompressed_bytes{instance=~\"$host\"}[1h])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_uncompressed_by{instance=~\"$host\"}[1h]))/rate(mysql_global_status_tokudb_checkpoint_taken{instance=~\"$host\"}[1h])",
       "legendFormat": "Uncompressed Data Processed Per Checkpoint (1h avg)"
      }
     ]
    },
    {
     "title": "Checkpoint Flushing",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Nodes Flushed Bytes"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Lead Nodes Flushed Bytes"
      },
      {
       "expr": "(rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{instance=~\"$host\"}[5m])) + (rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{instance=~\"$host\"}[5m]))",
       "legendFormat": "Checkpoint Flushed Total"
      }
     ]
    },
    {
     "title": "Not-Checkpoint Flushing",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Nodes Flushed Bytes"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Lead Nodes Flushed Bytes"
      },
      {
       "expr": "(rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{instance=~\"$host\"}[5m])) + (rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{instance=~\"$host\"}[5m]))",
       "legendFormat": "Not Checkpoint Flushed Total"
      }
     ]
    },
    {
     "title": "Avg Flushed Node Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{instance=~\"$host\"}[$interval])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{instance=~\"$host\"}[$interval]))/(rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint{instance=~\"$host\"}[$interval])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint{instance=~\"$host\"}[$interval]))",
       "legendFormat": "Flushed Non Leaf Node Size"
      },
      {
       "expr": "(rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{instance=~\"$host\"}[$interval])+rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{instance=~\"$host\"}[$interval]))/(rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint{instance=~\"$host\"}[$interval])+rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint{instance=~\"$host\"}[$interval]))",
       "legendFormat": "Flushed Leaf Node Size"
      }
     ]
    },
    {
     "title": "Flushing Disk Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Nodes Checkpoint "
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Leaf Nodes Checkpoint"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Leaf Nodes Not Checkpoint"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Non Leaf Nodes Not Checkpoint"
      }
     ]
    }
   ]
  },
  {
   "title": "Pivots, Basements, Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Pivots Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_pivots_fetched_for_query_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_query_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Query Pivots Size"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prefetch Pivots Size"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_pivots_fetched_for_write_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_write_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Write Pivots Size"
      }
     ]
    },
    {
     "title": "TokuDB Pivots Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_pivots_fetched_for_query_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_query_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Query Pivots Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prefetch Pivots Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_pivots_fetched_for_write_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_write_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Write Pivots Load"
      }
     ]
    },
    {
     "title": "TokuDB Basements Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_basements_fetched_target_query_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_target_query_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Query Basements Size"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_basements_fetched_prefetch_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prefetch_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prefetch Basements Size"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_basements_fetched_for_write_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_for_write_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Write Basements Size"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_basements_fetched_prelocked_range_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prelocked_range_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prelocked Range Basements Size"
      }
     ]
    },
    {
     "title": "TokuDB Basements Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_basements_fetched_target_query_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_target_query_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Query Basements Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_basements_fetched_prefetch_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prefetch_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prefetch Basements Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_basements_fetched_for_write_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_for_write_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Write Basements Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_basements_fetched_prelocked_range_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prelocked_range_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prelocked Range Basements Load"
      }
     ]
    },
    {
     "title": "TokuDB Buffers Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_buffers_fetched_target_query_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_target_query_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Query Buffers Size"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_buffers_fetched_prefetch_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prefetch_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prefetch Buffers Size"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_buffers_fetched_for_write_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_for_write_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Write Buffers Size"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prelocked Range Buffers Size"
      }
     ]
    },
    {
     "title": "TokuDB Buffers Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_buffers_fetched_target_query_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_target_query_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Query Buffers Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_buffers_fetched_prefetch_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prefetch_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prefetch Buffers Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_buffers_fetched_for_write_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_for_write_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Write Buffers Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Fetched for Prelocked Range Buffers Load"
      }
     ]
    }
   ]
  },
  {
   "title": "Logger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Logger",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_logger_writes_bytes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_logger_writes_bytes{instance=~\"$host\"}[5m])",
       "legendFormat": "Data written to WAL"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_logger_writes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_logger_writes{instance=~\"$host\"}[5m])",
       "legendFormat": "WAL Writes"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_filesystem_fsync_num{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_filesystem_fsync_num{instance=~\"$host\"}[5m])",
       "legendFormat": "Total Fsyncs  "
      }
     ]
    },
    {
     "title": "TokuDB Logger Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_logger_writes_seconds{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_logger_writes_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Logger Load "
      },
      {
       "expr": "rate(mysql_global_status_tokudb_filesystem_fsync_time{instance=~\"$host\"}[$interval])/1000000  or irate(mysql_global_status_tokudb_filesystem_fsync_time{instance=~\"$host\"}[5m])/1000000",
       "legendFormat": "Fsync Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_filesystem_fsync_time{instance=~\"$host\"}[$interval])/rate(mysql_global_status_tokudb_filesystem_fsync_num{instance=~\"$host\"}[$interval])/1000000  or irate(mysql_global_status_tokudb_filesystem_fsync_time{instance=~\"$host\"}[5m])/irate(mysql_global_status_tokudb_filesystem_fsync_num{instance=~\"$host\"}[5m])/1000000 ",
       "legendFormat": "Fsync Avg Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "LockTree",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB LockTree Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_tokudb_locktree_memory_size_limit{instance=~\"$host\"}",
       "legendFormat": "LockTree Memory Limit"
      },
      {
       "expr": "max_over_time(mysql_global_status_tokudb_locktree_memory_size{instance=~\"$host\"}[$interval])",
       "legendFormat": "Current LockTree Size "
      },
      {
       "expr": "max_over_time(mysql_global_status_tokudb_locktree_open_current{instance=~\"$host\"}[$interval])",
       "legendFormat": "Currently Open LockTrees"
      }
     ]
    },
    {
     "title": "TokuDB LockTree Waits",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(mysql_global_status_tokudb_locktree_pending_lock_requests{instance=~\"$host\"}[$interval])",
       "legendFormat": "Pending Lock Requests"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_locktree_wait_count{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_locktree_wait_count{instance=~\"$host\"}[5m])",
       "legendFormat": "Lock Waits "
      },
      {
       "expr": "rate(mysql_global_status_tokudb_locktree_wait_time{instance=~\"$host\"}[$interval])/1000000 or irate(mysql_global_status_tokudb_locktree_wait_count{instance=~\"$host\"}[5m])/1000000",
       "legendFormat": "Lock Wait Load"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_locktree_timeout_count{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_locktree_timeout_count{instance=~\"$host\"}[5m])",
       "legendFormat": "Lock Wait Timeouts"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Client Thread Pool",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_tokudb_cachetable_pool_client_num_threads{instance=~\"$host\"}",
       "legendFormat": "Client Thread Pool Size"
      },
      {
       "expr": "avg_over_time(mysql_global_status_tokudb_cachetable_pool_client_num_threads_active{instance=~\"$host\"}[$interval])",
       "legendFormat": "Avg Threads Active"
      },
      {
       "expr": "max_over_time(mysql_global_status_tokudb_cachetable_pool_client_num_threads_active{instance=~\"$host\"}[$interval])",
       "legendFormat": "Peak Threads Active"
      },
      {
       "expr": "max_over_time(mysql_global_status_tokudb_cachetable_pool_client_queue_size{instance=~\"$host\"}[$interval])",
       "legendFormat": "Peak Queue Size"
      }
     ]
    },
    {
     "title": "TokuDB CacheTable Thread Pool",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_tokudb_cachetable_pool_cachetable_num_threads{instance=~\"$host\"}",
       "legendFormat": "CacheTable Thread Pool Size"
      },
      {
       "expr": "avg_over_time(mysql_global_status_tokudb_cachetable_pool_cachetable_num_threads_active{instance=~\"$host\"}[$interval])",
       "legendFormat": "Avg Threads Active"
      },
      {
       "expr": "max_over_time(mysql_global_status_tokudb_cachetable_pool_cachetable_num_threads_active{instance=~\"$host\"}[$interval])",
       "legendFormat": "Peak Threads Active"
      }
     ]
    },
    {
     "title": "TokuDB Checkpoint Thread Pool",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_tokudb_cachetable_pool_checkpoint_num_threads{instance=~\"$host\"}",
       "legendFormat": "Checkpoint Thread Pool Size"
      },
      {
       "expr": "avg_over_time(mysql_global_status_tokudb_cachetable_pool_checkpoint_num_threads_active{instance=~\"$host\"}[$interval])",
       "legendFormat": "Avg Threads Active"
      },
      {
       "expr": "max_over_time(mysql_global_status_tokudb_cachetable_pool_checkpoint_num_threads_active{instance=~\"$host\"}[$interval])",
       "legendFormat": "Peak Threads Active"
      }
     ]
    },
    {
     "title": "TokuDB Background Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_tokudb_cachetable_cleaner_executions{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_cleaner_executions{instance=~\"$host\"}[5m])",
       "legendFormat": "Cleaner Executions"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_cachetable_pool_client_total_items_processed{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_pool_client_total_items_processed{instance=~\"$host\"}[5m])",
       "legendFormat": "Client Items Processed"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_cachetable_pool_cachetable_total_items_processed{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_pool_cachetable_total_items_processed{instance=~\"$host\"}[5m])",
       "legendFormat": "Cachetable Items Processed"
      },
      {
       "expr": "rate(mysql_global_status_tokudb_cachetable_pool_checkpoint_total_items_processed{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_pool_checkpoint_total_items_processed{instance=~\"$host\"}[5m])",
       "legendFormat": "Checkpoint Items Processed"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Schema",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Top Wait Events (Count)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,rate(mysql_perf_schema_events_waits_total{instance=~\"$host\",event_name=~\".+/fti/.+|.+/tokudb/.+\"}[$interval]))",
       "legendFormat": "{{event_name}}"
      }
     ]
    },
    {
     "title": "TokuDB Top Wait Events (Load)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rate(mysql_perf_schema_events_waits_seconds_total{instance=~\"$host\",event_name=~\".+/fti/.+|.+/tokudb/.+\"}[$interval]))",
       "legendFormat": "{{event_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Connections and Questions",
     "type": "graph",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval])  or mysql_global_status_threads_connected{instance=~\"$host\"} )",
       "legendFormat": "Current Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_max_used_connections{instance=~\"$host\"}",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_max_connections{instance=~\"$host\"}",
       "legendFormat": "Max Connections"
      },
      {
       "expr": "rate(mysql_global_status_questions{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_questions{instance=~\"$host\"}[5m])",
       "legendFormat": "Questions"
      },
      {
       "expr": "rate(mysql_global_status_connections{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_connections{instance=~\"$host\"}[5m])",
       "legendFormat": "New Connections"
      }
     ]
    },
    {
     "title": "MySQL Client Thread Activity",
     "type": "graph",
     "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[5m])",
       "legendFormat": "Peak Threads Connected"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_threads_running{instance=~\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{instance=~\"$host\"}[5m])",
       "legendFormat": "Peak Threads Running"
      },
      {
       "expr": "avg_over_time(mysql_global_status_threads_running{instance=~\"$host\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{instance=~\"$host\"}[5m])",
       "legendFormat": "Avg Threads Running"
      }
     ]
    },
    {
     "title": "Top Command Counters",
     "type": "graph",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5, rate(mysql_global_status_commands_total{instance=~\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{instance=~\"$host\"}[5m])>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    },
    {
     "title": "MySQL Row Handlers",
     "type": "graph",
     "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_handlers_total{instance=~\"$host\", handler!~\"external_lock|commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=~\"$host\", handler!~\"external_lock|commit|rollback|savepoint.*|prepare\"}[5m])",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=~\"$host\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Saturation and Max Core Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "(avg_over_time(node_procs_running{instance=~\"$host\"}[$interval])-1) / scalar(count(node_cpu{mode=\"user\", instance=~\"$host\"})) or (avg_over_time(node_procs_running{instance=~\"$host\"}[5m])-1) / scalar(count(node_cpu{mode=\"user\", instance=~\"$host\"}))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      },
      {
       "expr": "avg_over_time(node_procs_blocked{instance=~\"$host\"}[$interval]) or avg_over_time(node_procs_blocked{instance=~\"$host\"}[5m])",
       "legendFormat": "IO Load"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "(rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024)",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "(rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024)",
       "legendFormat": "Total"
      },
      {
       "expr": "rate(node_vmstat_pswpin{instance=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "rate(node_vmstat_pswpout{instance=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m])) ",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}