modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
  http_es_onlyread_test:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
      fail_if_body_matches_regexp:
        - 'read_only_allow_delete'
  http_es_health_test:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
      fail_if_body_not_matches_regexp:
        - 'green'
  https_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
      tls_config:
        ca_file: "/certs/my_cert.crt"
  http_custom_httpcode:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_http_versions: ["HTTP/1.1","HTTP/2"]
      valid_status_codes: [200,201,202,203,204,300,301,302]
      preferred_ip_protocol: ip4
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      preferred_ip_protocol: ip4
      headers:
        Content-Type: application/json
      body: '{}'
  http_post_2xx_basic_auth:
    prober: http
    timeout: 5s
    http:
      method: POST
      preferred_ip_protocol: ip4
      headers:
        Host: 'login.baidu.com'
      basic_auth:
        username: 'username'
        password: 'password'
  tcp_connect:
    prober: tcp
    timeout: 3s
    tcp:
      preferred_ip_protocol: ip4
  pop3s_banner:
    prober: tcp
    timeout: 3s
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    timeout: 3s
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
    icmp:
      preferred_ip_protocol: ip4  
  dns:
    prober: dns
    timeout: 3s
    dns:
      query_name: 'homsom.com'
      preferred_ip_protocol: 'ip4'
      source_ip_address: '127.0.0.1'
      transport_protocol: 'udp'
      query_type: 'ANY'

