global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'

rule_files:
  - "/usr/local/prometheus/rules/*.rule"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
    - targets: ['127.0.0.1:9090']
      labels:
        app: "prometheus server"

  - job_name: 'consul-nginx_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: nginx.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-node_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: node.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul_aliyun-node_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: aliyun_node.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-xenserver'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*xenserver.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-cadvisor_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: cadvisor.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul_aliyun-cadvisor_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: aliyun_cadvisor.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-redis_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
       - source_labels: [__meta_consul_service]
         regex: redis.*
         action: keep
       - regex: __meta_consul_service_metadata_(.+)
         action: labelmap

  - job_name: 'consul_aliyun-redis_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
       - source_labels: [__meta_consul_service]
         regex: aliyun_redis.*
         action: keep
       - regex: __meta_consul_service_metadata_(.+)
         action: labelmap

  - job_name: 'consul-mysqld_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
       - source_labels: [__meta_consul_service]
         regex: mysql.*
         action: keep
       - regex: __meta_consul_service_metadata_(.+)
         action: labelmap

  - job_name: 'consul_aliyun-mysqld_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
       - source_labels: [__meta_consul_service]
         regex: aliyun_mysql.*
         action: keep
       - regex: __meta_consul_service_metadata_(.+)
         action: labelmap

  - job_name: 'consul-elasticsearch_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: elasticsearch.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul_aliyun-elasticsearch_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: aliyun_elasticsearch.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-windows_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*windows_exporter.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-wmi_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*wmi_exporter.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-blackbox_icmp'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [icmp]
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*icmp.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: (.*):(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.13.236:9115

  - job_name: 'consul-blackbox_http_elasticsearch_readonly'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_es_onlyread_test]
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*blackbox_http_elasticsearch_readonly.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: \[(.*)\]:(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.13.236:9115

  - job_name: 'consul-blackbox_http_elasticsearch_health'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_es_health_test]
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*blackbox_http_elasticsearch_health.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: \[(.*)\]:(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.13.236:9115

  - job_name: 'consul-blackbox-http'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_custom_httpcode]
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*blackbox_http,
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: \[(.*)\]:(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.13.236:9115

  - job_name: 'consul-blackbox-http-services'
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [http_custom_httpcode_200]
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*blackbox_http_services,
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: \[(.*)\]:(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.13.236:9115

  - job_name: 'consul-blackbox-tcp'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*blackbox_tcp.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: \[(.*)\]:(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.13.236:9115

  - job_name: 'consul-snmp_exporter'
    scrape_interval: 30s
    metrics_path: /snmp
    params:
      module: [if_mib]
      community: [public]
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*snmp_exporter.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: (.*):(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [community]
        target_label: __param_community
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
        replacement: 192.168.13.236:9116

  - job_name: 'consul-snmp_idrac_exporter'
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: /snmp
    params:
      module: [dell_idrac]
      community: [public]
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*snmp_idrac_exporter.*
        action: keep
      - source_labels: [__meta_consul_service_id]
        regex: .*192.168.50.50
        action: drop
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: (.*):(.*)
        target_label: __param_target
        replacement: ${1}:161
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [community]
        target_label: __param_community
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
        replacement: 192.168.13.236:9117

  - job_name: 'consul-snmp_idrac_exporter_tiger'
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: /snmp
    params:
      module: [dell_idrac]
      community: [public]
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service_id]
        regex: snmp_idrac_exporter-192.168.50.50
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: (.*):(.*)
        target_label: __param_target
        replacement: ${1}:161
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [community]
        target_label: __param_community
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
        replacement: 36.150.108.179:19116

  - job_name: 'consul-rabbitmq_exporter'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*rabbitmq.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-apollo'
    metrics_path: /prometheus
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: apollo.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-docker_app'
    metrics_path: /metrics
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: docker_app.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'consul-mssql_exporter_fat'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*mssql_exporter.*
        action: keep
      - source_labels: [__meta_consul_service_metadata_env]
        regex: .*uat.*
        action: drop
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: (.*):(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.13.236:9399

  - job_name: 'consul-mssql_exporter_uat'
    scrape_interval: 15s
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*mssql_exporter.*
        action: keep
      - source_labels: [__meta_consul_service_metadata_env]
        regex: .*fat.*
        action: drop
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: (.*):(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.13.236:9400

  - job_name: 'consul-ipmi_exporter'
    scrape_interval: 15s
    metrics_path: /ipmi
    consul_sd_configs:
    - server: '192.168.13.236:8500'
      services: []
    relabel_configs:
      - source_labels: [__meta_consul_service_id]
        regex: ipmi_exporter-192.168.0.203
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
      - source_labels: [__address__]
        regex: (.*):(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.13.236:9290

