version: '3.4'
services:
  zabbix-mysql-server:                    # 服务名称
    image: harbor:8888/zabbix/mysql:5.7      # 使用的镜像
    container_name: zabbix-mysql-server   # 容器名称
    hostname: zabbix-mysql-server
    restart: always                 # 失败自动重启策略
    environment:                                    
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
    volumes:
      - /data/docker/zabbix/mysql/data:/var/lib/mysql
    ports:
      - 33061:3306
    command: 
      - --character-set-server=utf8
      - --collation-server=utf8_bin
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 200M
  zabbix-server-mysql:                    # 服务名称
    image: harbor:8888/zabbix/zabbix-server-mysql:centos-3.4.15      # 使用的镜像
    container_name: zabbix-server-mysql   # 容器名称
    hostname: zabbix-server-mysql
    links:
      - zabbix-mysql-server:mysql
    restart: always                 # 失败自动重启策略
    environment:                                    
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
    depends_on:
      - zabbix-mysql-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/docker/zabbix/zabbix-server/alertscripts:/usr/lib/zabbix/alertscripts
      - /data/docker/zabbix/zabbix-server/externalscripts:/usr/lib/zabbix/externalscripts
    ports:
      - 10051:10051
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          memory: 50M
  zabbix-web-nginx-mysql:                    # 服务名称
    image: harbor:8888/zabbix/zabbix-web-nginx-mysql:centos-3.4.15     # 使用的镜像
    container_name: zabbix-web-nginx-mysql   # 容器名称
    hostname: zabbix-web-nginx-mysql
    links:
      - zabbix-mysql-server:mysql
      - zabbix-server-mysql:zabbix-server
    restart: always                 # 失败自动重启策略
    environment:    
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Shanghai
    volumes:
      - /data/docker/zabbix/graphfont.ttf:/usr/share/zabbix/fonts/graphfont.ttf
    depends_on:
      - zabbix-mysql-server
      - zabbix-server-mysql
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          memory: 100M
networks:
  default:
    driver: bridge
