<VERSION>4.1.1</VERSION>
<SQLQUERY>
<REMARK>
[标题]

[应用背景]

[结果列描述]

[必要的查询条件]

[实现方法]

--2012-9-18 新增单据的金额、完成日期、对账日期
alter table H4RTMP_STKINSUM add (fildate date, paydate date , 
total number(20,4), tax number(20,4));
alter table H4RTMP_STKINTOPAY add (fildate date, paydate date , 
total number(20,4), tax number(20,4));

[其它]
</REMARK>
<BEFORERUN>
DECLARE
V_STKINNUM     STKIN.NUM%TYPE;
V_STKINCLS     STKIN.CLS%TYPE;
V_VDRCHKNUM    VDRCHKRCV.NUM%TYPE;
V_VDRCHKCLS    VDRCHKRCV.CLS%TYPE;
V_PVINUM       PVI.NUM%TYPE;
V_PAYNUM       PAY.NUM%TYPE;
V_FLAG         VARCHAR2(20);
V_VDRCODE	varchar2(2000);
VUSERCODE       varchar2(200);
BEGIN



  VUSERCODE := '\(USERCODE)';
delete TMP_VCODE;
insert into TMP_VCODE
select v.code  from psvdremp p ,employee e ,vendor v where p.vendor = v.gid and p.empgid = e.gid 
and e.code = VUSERCODE;




  V_VDRCODE   := TRIM('\(1,1)');
  V_STKINNUM   := TRIM('\(2,1)'); 
  V_STKINCLS   := TRIM('\(3,1)');

  V_VDRCHKNUM  := TRIM('\(4,1)');
  V_VDRCHKCLS  := TRIM('\(5,1)');
  V_PVINUM     := TRIM('\(6,1)');
  V_PAYNUM     := TRIM('\(7,1)');
  V_FLAG       := TRIM('\(8,1)'); -- 是否发票登记标志
  
  DELETE FROM H4RTMP_STKINSUM;
  DELETE FROM H4RTMP_STKINTOPAY;
  DELETE FROM H4RTMP_STKINTOPAY;
  COMMIT;
  
    -- 找已完成的进货单
    -- 自营进货单
    INSERT INTO H4RTMP_STKINSUM(VDRGID,NUM, CLS, PAYDATE,FILDATE,TOTAL ,TAX) SELECT S.VENDOR , S.NUM, S.CLS , S.PAYDATE,S.FILDATE , S.TOTAL,S.TAX
    FROM STKIN S 
    WHERE S.STAT = 300 AND (S.NUM = V_STKINNUM OR V_STKINNUM IS NULL) AND (S.CLS = V_STKINCLS OR V_STKINCLS IS NULL)
         AND (S.VENDOR IN (SELECT GID FROM VENDORH WHERE CODE = V_VDRCODE) OR V_VDRCODE IS NULL);  
    
    -- 自营进货退后单
    INSERT INTO H4RTMP_STKINSUM(VDRGID , NUM, CLS, PAYDATE,FILDATE,TOTAL ,TAX) SELECT SB.VENDOR,SB.NUM, SB.CLS , SB.FILDATE PAYDATE,SB.FILDATE , -SB.TOTAL, -SB.TAX
    FROM STKINBCK SB 
    WHERE SB.STAT = 300
    AND (SB.NUM = V_STKINNUM OR V_STKINNUM IS NULL) AND (SB.CLS = V_STKINCLS OR V_STKINCLS IS NULL)
    AND (SB.VENDOR IN (SELECT GID FROM VENDORH WHERE CODE = V_VDRCODE) OR V_VDRCODE IS NULL); 
    
    -- 直配
    INSERT INTO H4RTMP_STKINSUM(VDRGID,NUM, CLS, PAYDATE,FILDATE,TOTAL ,TAX) SELECT D.VENDOR , D.NUM, D.CLS ,  D.PAYDATE,D.FILDATE , DECODE(D.CLS ,'直配出退',-1,1)*D.TOTAL,DECODE(D.CLS ,'直配出退',-1,1)*D.TAX 
    FROM DIRALC D 
    WHERE D.STAT = 300 AND (D.NUM = V_STKINNUM OR V_STKINNUM IS NULL) AND (D.CLS = V_STKINCLS OR V_STKINCLS IS NULL)
     AND (D.VENDOR IN (SELECT GID FROM VENDORH WHERE CODE = V_VDRCODE) OR V_VDRCODE IS NULL);          
    
    
    -- 1.写入进货单登记过经销对账单VDRCHKRCV，登记过普通发票PVI，登记过付款单CNTRPAYCASH的信息
    INSERT INTO H4RTMP_STKINTOPAY(VDRGID, STKINNUM, STKINCLS ,PAYDATE,FILDATE,TOTAL ,TAX, VDRCHKNUM, VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT, FLAG)
    SELECT S.VDRGID,S.NUM STKINNUM, S.CLS STKINCLS, S.PAYDATE,S.FILDATE,S.TOTAL ,S.TAX,V.NUM VDRCHKNUM, V.CLS VDRCHKCLS, M1.STATNAME, P.NUM PVINUM, P.CLS PVICLS, M2.STATNAME PVISTAT, C.NUM, '付款单', M3.STATNAME, V_FLAG
    FROM H4RTMP_STKINSUM S, VDRCHKRCV V, VDRCHKRCVDTL VDTL, PVI P, 
    (SELECT DISTINCT P.SRCNUM, P.SRCCLS, P.NUM, P.CLS FROM PVIDTL P) PDTL, CNTRPAYCASH C, CNTRPAYCASHDTL CDTL,
    MODULESTAT M1, MODULESTAT M2, MODULESTAT M3
    WHERE S.NUM = VDTL.SRCNUM
    AND S.CLS = VDTL.SRCCLS
    AND S.NUM = PDTL.SRCNUM
    AND S.CLS = PDTL.SRCCLS
    AND PDTL.NUM = CDTL.SRCNUM
    AND PDTL.CLS = CDTL.CHGTYPE
    AND V.NUM = VDTL.NUM
    AND V.CLS = VDTL.CLS
    AND P.NUM = PDTL.NUM
    AND P.CLS = PDTL.CLS
    AND C.NUM = CDTL.NUM
    AND V.STAT = M1.NO
    AND P.STAT = M2.NO
    AND C.STAT = M3.NO;

    -- 2.写入进货单登记过经销按销对账单PurchaseBySaleCTBDTL2，登记过普通发票PVI，登记过付款单CNTRPAYCASH的信息
    INSERT INTO H4RTMP_STKINTOPAY(VDRGID,STKINNUM, STKINCLS, PAYDATE,FILDATE,TOTAL ,TAX, VDRCHKNUM, VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT, FLAG)
    SELECT S.VDRGID,S.NUM STKINNUM, S.CLS STKINCLS, S.PAYDATE,S.FILDATE,S.TOTAL ,S.TAX, V.NUM VDRCHKNUM, '经销按销对账单' VDRCHKCLS, M1.STATNAME, P.NUM PVINUM, P.CLS PVICLS, M2.STATNAME PVISTAT, C.NUM, '付款单', M3.STATNAME, V_FLAG
    FROM H4RTMP_STKINSUM S, PurchaseBySaleCTB V, PurchaseBySaleCTBDTL2 VDTL, PVI P, 
    (SELECT DISTINCT P.SRCNUM, P.SRCCLS, P.NUM, P.CLS FROM PVIDTL P) PDTL, CNTRPAYCASH C, CNTRPAYCASHDTL CDTL,
    MODULESTAT M1, MODULESTAT M2, MODULESTAT M3
    WHERE S.NUM = VDTL.SRCNUM
    AND S.CLS = VDTL.SCLS
    AND S.NUM = PDTL.SRCNUM
    AND S.CLS = PDTL.SRCCLS
    AND PDTL.NUM = CDTL.SRCNUM
    AND PDTL.CLS = CDTL.CHGTYPE
    AND V.NUM = VDTL.NUM
    AND P.NUM = PDTL.NUM
    AND P.CLS = PDTL.CLS
    AND C.NUM = CDTL.NUM
    AND V.STAT = M1.NO
    AND P.STAT = M2.NO
    AND C.STAT = M3.NO;
    
    -- 3.写入进货单登记过经销对账单VDRCHKRCV，登记过普通发票PVI，没有登记过付款单CNTRPAYCASH的信息
    INSERT INTO H4RTMP_STKINTOPAY(VDRGID,STKINNUM, STKINCLS, PAYDATE,FILDATE,TOTAL ,TAX, VDRCHKNUM, VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT, FLAG)
    SELECT S.VDRGID,S.NUM STKINNUM, S.CLS STKINCLS, S.PAYDATE,S.FILDATE,S.TOTAL ,S.TAX, V.NUM VDRCHKNUM, V.CLS VDRCHKCLS, M1.STATNAME, P.NUM PVINUM, P.CLS PVICLS, M2.STATNAME PVISTAT, '', '', '', V_FLAG
    FROM H4RTMP_STKINSUM S, VDRCHKRCV V, VDRCHKRCVDTL VDTL, PVI P, 
    (SELECT DISTINCT P.SRCNUM, P.SRCCLS, P.NUM, P.CLS FROM PVIDTL P) PDTL,
    MODULESTAT M1, MODULESTAT M2
    WHERE S.NUM = VDTL.SRCNUM
    AND S.CLS = VDTL.SRCCLS
    AND S.NUM = PDTL.SRCNUM
    AND S.CLS = PDTL.SRCCLS
    AND V.NUM = VDTL.NUM
    AND V.CLS = VDTL.CLS
    AND P.NUM = PDTL.NUM
    AND P.CLS = PDTL.CLS
    AND V.STAT = M1.NO
    AND P.STAT = M2.NO
    AND NOT EXISTS (SELECT 1 FROM H4RTMP_STKINTOPAY WHERE STKINNUM = S.NUM AND STKINCLS = S.CLS AND VDRCHKNUM = V.NUM
                    AND VDRCHKCLS = V.CLS AND PVINUM = P.NUM AND PVICLS = P.CLS);

    -- 4.写入进货单登记过经销按销对账单PurchaseBySaleCTBDTL2，登记过普通发票PVI，没有登记过付款单CNTRPAYCASH的信息
    INSERT INTO H4RTMP_STKINTOPAY(VDRGID,STKINNUM, STKINCLS, PAYDATE,FILDATE,TOTAL ,TAX, VDRCHKNUM, VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT, FLAG)
    SELECT S.VDRGID,S.NUM STKINNUM, S.CLS STKINCLS, S.PAYDATE,S.FILDATE,S.TOTAL ,S.TAX, V.NUM VDRCHKNUM, '经销按销对账单' VDRCHKCLS, M1.STATNAME, P.NUM PVINUM, P.CLS PVICLS, M2.STATNAME PVISTAT, '', '', '', V_FLAG
    FROM H4RTMP_STKINSUM S, PurchaseBySaleCTB V, PurchaseBySaleCTBDTL2 VDTL, PVI P, 
    (SELECT DISTINCT P.SRCNUM, P.SRCCLS, P.NUM, P.CLS FROM PVIDTL P) PDTL,
    MODULESTAT M1, MODULESTAT M2
    WHERE S.NUM = VDTL.SRCNUM
    AND S.CLS = VDTL.SCLS
    AND S.NUM = PDTL.SRCNUM
    AND S.CLS = PDTL.SRCCLS
    AND V.NUM = VDTL.NUM
    AND P.NUM = PDTL.NUM
    AND P.CLS = PDTL.CLS
    AND V.STAT = M1.NO
    AND P.STAT = M2.NO
    AND NOT EXISTS (SELECT 1 FROM H4RTMP_STKINTOPAY WHERE STKINNUM = S.NUM AND STKINCLS = S.CLS AND VDRCHKNUM = V.NUM
                    AND PVINUM = P.NUM AND PVICLS = P.CLS);
                                                            
    -- 5. 写入进货单登记过经销对账单VDRCHKRCV，没有登记过普通发票PVI，没有登记过付款单CNTRPAYCASH的信息
    INSERT INTO H4RTMP_STKINTOPAY(VDRGID,STKINNUM, STKINCLS, PAYDATE,FILDATE,TOTAL ,TAX, VDRCHKNUM, VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT, FLAG)
    SELECT S.VDRGID,S.NUM STKINNUM, S.CLS STKINCLS, S.PAYDATE,S.FILDATE,S.TOTAL ,S.TAX, V.NUM VDRCHKNUM, V.CLS VDRCHKCLS, M1.STATNAME, '' PVINUM, '' PVICLS, '' PVISTAT, '' PAYNUM, '' PAYCLS, '' PAYSTAT, V_FLAG FLAG
    FROM H4RTMP_STKINSUM S, VDRCHKRCV V, VDRCHKRCVDTL VDTL, MODULESTAT M1
    WHERE S.NUM = VDTL.SRCNUM
    AND S.CLS = VDTL.SRCCLS
    AND V.NUM = VDTL.NUM
    AND V.CLS = VDTL.CLS
    AND V.STAT = M1.NO
    AND NOT EXISTS (SELECT 1 FROM H4RTMP_STKINTOPAY WHERE STKINNUM = S.NUM AND STKINCLS = S.CLS AND VDRCHKNUM = V.NUM
                    AND VDRCHKCLS = V.CLS);                  

    -- 6. 写入进货单登记过经销按销对账单PurchaseBySaleCTBDTL2，没有登记过普通发票PVI，没有登记过付款单CNTRPAYCASH的信息
    INSERT INTO H4RTMP_STKINTOPAY(VDRGID,STKINNUM, STKINCLS, PAYDATE,FILDATE,TOTAL ,TAX, VDRCHKNUM, VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT, FLAG)
    SELECT S.VDRGID,S.NUM STKINNUM, S.CLS STKINCLS, S.PAYDATE,S.FILDATE,S.TOTAL ,S.TAX, V.NUM VDRCHKNUM, '经销按销对账单' VDRCHKCLS, M1.STATNAME, '' PVINUM, '' PVICLS, '' PVISTAT, '' PAYNUM, '' PAYCLS, '' PAYSTAT, V_FLAG FLAG
    FROM H4RTMP_STKINSUM S, PurchaseBySaleCTB V, PurchaseBySaleCTBDTL2 VDTL, MODULESTAT M1
    WHERE S.NUM = VDTL.SRCNUM
    AND S.CLS = VDTL.SCLS
    AND V.NUM = VDTL.NUM
    AND V.STAT = M1.NO
    AND NOT EXISTS (SELECT 1 FROM H4RTMP_STKINTOPAY WHERE STKINNUM = S.NUM AND STKINCLS = S.CLS AND VDRCHKNUM = V.NUM);  

    ----7. 没有启用对账模型的 跟踪模式，进货单-发票 --已付款

    INSERT INTO H4RTMP_STKINTOPAY(VDRGID,STKINNUM, STKINCLS, PAYDATE,FILDATE,TOTAL ,TAX, VDRCHKNUM, 
VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT, FLAG)
    SELECT S.VDRGID,S.NUM STKINNUM, S.CLS STKINCLS, S.PAYDATE,S.FILDATE,S.TOTAL ,S.TAX, '' VDRCHKNUM, '' VDRCHKCLS, 
'', P.NUM PVINUM, P.CLS PVICLS, M1.STATNAME PVISTAT, C.NUM PAYNUM, C.CLS PAYCLS,
 M2.STATNAME PAYSTAT, V_FLAG FLAG
    FROM H4RTMP_STKINSUM S, PVI P, 
    (SELECT DISTINCT P.SRCNUM, P.SRCCLS, P.NUM, P.CLS FROM PVIDTL P) PDTL , 
CNTRPAYCASH C, CNTRPAYCASHDTL CDTL, MODULESTAT M1 , MODULESTAT M2
    WHERE S.NUM = PDTL.SRCNUM
    AND S.CLS = PDTL.SRCCLS
    AND P.NUM = PDTL.NUM
    AND C.NUM = CDTL.NUM
    AND P.NUM = CDTL.SRCNUM
    AND P.CLS = CDTL.CHGTYPE
    AND P.STAT = M1.NO
    AND C.STAT = M2.NO
    AND NOT EXISTS (SELECT 1 FROM PurchaseBySaleCTBDTL2 WHERE SCLS = S.CLS AND 
SRCNUM = S.NUM) --经销按销对账单PurchaseBySaleCTBDTL2
    AND NOT EXISTS (SELECT 1 FROM VDRCHKRCVDTL WHERE SRCCLS = S.CLS AND SRCNUM 
= S.NUM)  --经销对账单VDRCHKRCV
    AND NOT EXISTS (SELECT 1 FROM H4RTMP_STKINTOPAY WHERE STKINNUM = S.NUM AND 
STKINCLS = S.CLS );   

    ----8. 没有启用对账模型的 跟踪模式，进货单-发票 --未付款

    INSERT INTO H4RTMP_STKINTOPAY(VDRGID,STKINNUM, STKINCLS, PAYDATE,FILDATE,TOTAL ,TAX, VDRCHKNUM, 
VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT, FLAG)
    SELECT S.VDRGID,S.NUM STKINNUM, S.CLS STKINCLS, S.PAYDATE,S.FILDATE,S.TOTAL ,S.TAX, '' VDRCHKNUM, '' VDRCHKCLS, 
'', P.NUM PVINUM, P.CLS PVICLS, M1.STATNAME PVISTAT, '' PAYNUM, '' PAYCLS, '' 
PAYSTAT, V_FLAG FLAG
    FROM H4RTMP_STKINSUM S, PVI P, 
    (SELECT DISTINCT P.SRCNUM, P.SRCCLS, P.NUM, P.CLS FROM PVIDTL P) PDTL , 
MODULESTAT M1 
    WHERE S.NUM = PDTL.SRCNUM
    AND S.CLS = PDTL.SRCCLS
    AND P.NUM = PDTL.NUM
    AND P.STAT = M1.NO
    AND NOT EXISTS (SELECT 1 FROM PurchaseBySaleCTBDTL2 WHERE SCLS = S.CLS AND 
SRCNUM = S.NUM) --经销按销对账单PurchaseBySaleCTBDTL2
    AND NOT EXISTS (SELECT 1 FROM VDRCHKRCVDTL WHERE SRCCLS = S.CLS AND SRCNUM 
= S.NUM)  --经销对账单VDRCHKRCV
    AND NOT EXISTS (SELECT 1 FROM H4RTMP_STKINTOPAY WHERE STKINNUM = S.NUM AND 
STKINCLS = S.CLS );    
                    
    -- 写入进货单没有登记过经销对账单VDRCHKRCV且没有登记过经销按销对账单PurchaseBySaleCTBDTL2，没有登记过普通发票PVI，没有登记过付款单CNTRPAYCASH的信息
    INSERT INTO H4RTMP_STKINTOPAY(VDRGID,STKINNUM, STKINCLS, PAYDATE,FILDATE,TOTAL ,TAX, VDRCHKNUM, VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT, FLAG)
    SELECT S.VDRGID,S.NUM STKINNUM, S.CLS STKINCLS, S.PAYDATE,S.FILDATE,S.TOTAL ,S.TAX, '' VDRCHKNUM, '' VDRCHKCLS, '' VDRSTAT, '' PVINUM, '' PVICLS, '' PVISTAT, '' PAYNUM, '' PAYCLS, '' PAYSTAT, V_FLAG FLAG
    FROM H4RTMP_STKINSUM S
    WHERE NOT EXISTS (SELECT 1 FROM H4RTMP_STKINTOPAY WHERE STKINNUM = S.NUM AND STKINCLS = S.CLS);   
 
   
/*  IF V_FLAG = '非多次登记' OR  V_FLAG =  '全部' OR  V_FLAG IS NULL THEN          
    SELECT STKINNUM, STKINCLS, VDRCHKNUM, VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT 
    FROM H4RTMP_STKINTOPAY
    GROUP BY STKINNUM, STKINCLS, VDRCHKNUM, VDRCHKCLS, VDRSTAT, PVINUM, PVICLS, PVISTAT, PAYNUM, PAYCLS, PAYSTAT
    HAVING COUNT(1) > 0; 
  */
   IF V_FLAG = '未对账' THEN 
     DELETE FROM H4RTMP_STKINTOPAY WHERE (VDRCHKNUM IS NOT NULL);
   END IF; 

   IF V_FLAG = '已对账未发票登记' THEN 
     DELETE FROM H4RTMP_STKINTOPAY WHERE (VDRCHKNUM = '' OR VDRCHKNUM IS NULL) OR (PVINUM IS NOT NULL);
   END IF;  
  
   IF V_FLAG = '已发票登记未付款' THEN 
     DELETE FROM H4RTMP_STKINTOPAY WHERE (VDRCHKNUM = '' OR VDRCHKNUM IS NULL) OR (PVINUM = '' OR PVINUM IS NULL) OR (PAYNUM IS NOT NULL);
   END IF; 
END;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>H4RTMP_STKINTOPAY</TABLE>
    <ALIAS>H4RTMP_STKINTOPAY</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
  <TABLEITEM>
    <TABLE>VENDORH</TABLE>
    <ALIAS>VENDORH</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
  <TABLEITEM>
    <TABLE>TMP_VCODE</TABLE>
    <ALIAS>TMP_VCODE</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
  <JOINITEM>
    <LEFT>H4RTMP_STKINTOPAY.VDRGID</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>VENDORH.GID</RIGHT>
  </JOINITEM>
  <JOINITEM>
    <LEFT>TMP_VCODE.vcode</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>VENDORH.CODE</RIGHT>
  </JOINITEM>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>0</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>VENDORH.CODE</COLUMN>
    <TITLE>供应商代码</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>CODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>VENDORH.NAME</COLUMN>
    <TITLE>供应商名称</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>NAME</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.STKINNUM</COLUMN>
    <TITLE>进货单号</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STKINNUM</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.STKINCLS</COLUMN>
    <TITLE>进货单据类型</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STKINCLS</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.FILDATE</COLUMN>
    <TITLE>完成日期</TITLE>
    <FIELDTYPE>11</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>FILDATE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>16711680</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.PAYDATE</COLUMN>
    <TITLE>对账日期</TITLE>
    <FIELDTYPE>11</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PAYDATE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>255</CFONTCOLOR>
    <CDISFORMAT>yyyy.MM.dd</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.TOTAL</COLUMN>
    <TITLE>含税金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>TOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>33023</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.TOTAL-H4RTMP_STKINTOPAY.TAX</COLUMN>
    <TITLE>去税金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>AMT</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>33023</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.TAX</COLUMN>
    <TITLE>税额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>TAX</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>33023</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.VDRCHKNUM</COLUMN>
    <TITLE>对账单号</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>VDRCHKNUM</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.VDRCHKCLS</COLUMN>
    <TITLE>对账单据类型</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>VDRCHKCLS</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.VDRSTAT</COLUMN>
    <TITLE>对账单状态</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>VDRSTAT</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.PVINUM</COLUMN>
    <TITLE>普通发票单号</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PVINUM</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.PVICLS</COLUMN>
    <TITLE>普通发票单据类型</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PVICLS</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.PVISTAT</COLUMN>
    <TITLE>普通发票状态</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PVISTAT</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.PAYNUM</COLUMN>
    <TITLE>付款单号</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PAYNUM</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.PAYCLS</COLUMN>
    <TITLE>付款单据类型</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PAYCLS</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.PAYSTAT</COLUMN>
    <TITLE>付款单状态</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PAYSTAT</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_STKINTOPAY.FLAG</COLUMN>
    <TITLE>是否发票登记标志</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>FLAG</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>68</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>242</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>131</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>95</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>133</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>122</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>107</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>88</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>94</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>104</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>111</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>124</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>184</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>124</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>184</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>124</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>124</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>184</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>进货单号</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
  <ORDERITEM>
    <COLUMN>对账单号</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
  <ORDERITEM>
    <COLUMN>普通发票单号</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>VENDORH.CODE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINTOPAY.STKINNUM</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINTOPAY.STKINCLS</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>自营进</PICKNAMEITEM>
      <PICKNAMEITEM>自营进退</PICKNAMEITEM>
      <PICKNAMEITEM>直配出</PICKNAMEITEM>
      <PICKNAMEITEM>直配出退</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>自营进</PICKVALUEITEM>
      <PICKVALUEITEM>自营进退</PICKVALUEITEM>
      <PICKVALUEITEM>直配出</PICKVALUEITEM>
      <PICKVALUEITEM>直配出退</PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINTOPAY.VDRCHKNUM</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINTOPAY.VDRCHKCLS</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>经销对账</PICKNAMEITEM>
      <PICKNAMEITEM>经销按销对账</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>经销对账</PICKVALUEITEM>
      <PICKVALUEITEM>经销按销对账</PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINTOPAY.PVINUM</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINTOPAY.PAYNUM</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_STKINTOPAY.FLAG</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>未对账</PICKNAMEITEM>
      <PICKNAMEITEM>已对账未发票登记</PICKNAMEITEM>
      <PICKNAMEITEM>已发票登记未付款</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>未对账</PICKVALUEITEM>
      <PICKVALUEITEM>已对账未发票登记</PICKVALUEITEM>
      <PICKVALUEITEM>已发票登记未付款</PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>107</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>114</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>138</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>122</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>115</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>118</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>124</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>124</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>0</NUMOFNEXTQRY>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>FALSE</DXLOADMETHOD>
  <DXSHOWGROUP>FALSE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>FALSE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>FALSE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>16777215</DXCOLORODDROW>
  <DXCOLOREVENROW>15921906</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERTYPE></DXFILTERTYPE>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE></RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>0</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
</RPTREPORTLIST>
</SQLREPORT>

