<VERSION>4.1.1</VERSION>
<SQLQUERY>
<REMARK>
[标题]

[应用背景]

[结果列描述]

[必要的查询条件]

[实现方法]

[其它]
</REMARK>
<BEFORERUN>
DECLARE
  VBDATE  DATE;
  VEDATE  DATE;
  VNUM    VARCHAR2(2000);
  VGDCODE  VARCHAR2(20);
  VSTATNAME VARCHAR2(200);
  VFILTER1 VARCHAR2(1000);
  VCLS  VARCHAR2(14);
  VUSERCODE varchar2(200);
BEGIN

  VUSERCODE := '\(USERCODE)';
delete TMP_VCODE;
insert into TMP_VCODE
select v.code  from psvdremp p ,employee e ,vendor v where p.vendor = v.gid and p.empgid = e.gid 
and e.code = VUSERCODE;


  VBDATE :=TO_DATE('\(1,1)','YYYY.MM.DD');
  VEDATE :=TO_DATE('\(2,1)','YYYY.MM.DD');
  VNUM :=TRIM('\(3,1)');
  --PPS_CONVERSTR(VFILTER1,',',VNUM);
  VGDCODE:=TRIM('\(4,1)');
  --VSTATNAME :=TRIM('\(5,1)');
  VCLS := TRIM('\(5,1)');

  DELETE FROM H4RTMP_PHMX;
  COMMIT;
    ---插入自营进数据
  INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE)
    SELECT STKIN.NUM , STKIN.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      VENDOR.NAME , STKINDTL.QTY , STKINDTL.QTYSTR , 
      STKINDTL.PRICE , STKINDTL.TOTAL , STKINDTL.TAX , STKINDTL.CAMT , 
      STKINDTL.CTAX , STKINDTL.RTOTAL , MODULESTAT.STATNAME,STKINLOG.TIME,STKINDTL.LINE,VENDOR.CODE
    FROM STKIN STKIN, STKINLOG STKINLOG, STKINDTL STKINDTL, GOODSH GOODSH, MODULESTAT MODULESTAT, VENDOR VENDOR
      WHERE ((STKIN.NUM = STKINDTL.NUM)
       and  (STKIN.CLS = STKINDTL.CLS)
       and  (STKIN.NUM = STKINLOG.NUM)
       and  (STKIN.CLS = STKINLOG.CLS)
       and  (STKIN.STAT = MODULESTAT.NO)
       and  (STKINDTL.GDGID = GOODSH.GID)
       and  ((STKIN.CLS = VCLS AND VCLS IS NOT NULL) OR (STKIN.CLS ='自营进' AND VCLS IS NULL))
       and  (STKIN.BILLTO = VENDOR.GID)
       --and  (STKIN.STAT = STKINLOG.STAT)
       and  (STKINLOG.STAT IN (1000, 1020, 1040, 320, 340))
       and  (STKINLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKINLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (STKIN.NUM LIKE VNUM||'%' OR VNUM IS NULL)
       and  (GOODSH.CODE LIKE VGDCODE||'%' OR VGDCODE IS NULL));
  COMMIT;
    ---插入自营进退数据
  INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE)
    SELECT STKIN.NUM , STKIN.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      VENDOR.NAME , -STKINDTL.QTY , '-'||STKINDTL.QTYSTR , 
      STKINDTL.PRICE , -STKINDTL.TOTAL , -STKINDTL.TAX , -STKINDTL.CAMT , 
      -STKINDTL.CTAX , -STKINDTL.RTOTAL , MODULESTAT.STATNAME,STKINLOG.TIME,STKINDTL.LINE,VENDOR.CODE
    FROM STKINBCK STKIN, STKINBCKLOG STKINLOG, STKINBCKDTL STKINDTL, GOODSH GOODSH, MODULESTAT MODULESTAT, VENDOR VENDOR
      WHERE ((STKIN.NUM = STKINDTL.NUM)
       and  (STKIN.CLS = STKINDTL.CLS)
       and  (STKIN.NUM = STKINLOG.NUM)
       and  (STKIN.CLS = STKINLOG.CLS)
       and  (STKIN.STAT = MODULESTAT.NO)
       and  (STKINDTL.GDGID = GOODSH.GID)
       and  ((STKIN.CLS = VCLS AND VCLS IS NOT NULL) OR (STKIN.CLS ='自营进退' AND VCLS IS NULL))
       and  (STKIN.BILLTO = VENDOR.GID)
       --and  (STKIN.STAT = STKINLOG.STAT)
       and  (STKINLOG.STAT IN (700, 720, 740, 320, 340) )
       and  (STKINLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKINLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (STKIN.NUM LIKE VNUM||'%' OR VNUM IS NULL)
       and  (GOODSH.CODE LIKE VGDCODE||'%' OR VGDCODE IS NULL));
commit;
    ---插入直配出数据
  INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE)
    SELECT STKIN.NUM , STKIN.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      VENDOR.NAME , STKINDTL.QTY , STKINDTL.QTYSTR , 
      STKINDTL.PRICE , STKINDTL.TOTAL , STKINDTL.TAX , STKINDTL.CAMT , 
      STKINDTL.CTAX , STKINDTL.RTOTAL , MODULESTAT.STATNAME,STKINLOG.TIME,STKINDTL.LINE,VENDOR.CODE
    FROM DIRALC STKIN, DIRALCLOG STKINLOG, DIRALCDTL STKINDTL, GOODSH GOODSH, MODULESTAT MODULESTAT, VENDOR VENDOR
      WHERE ((STKIN.NUM = STKINDTL.NUM)
       and  (STKIN.CLS = STKINDTL.CLS)
       and  (STKIN.NUM = STKINLOG.NUM)
       and  (STKIN.CLS = STKINLOG.CLS)
       and  (STKIN.STAT = MODULESTAT.NO)
       and  (STKINDTL.GDGID = GOODSH.GID)
       and  ((STKIN.CLS = VCLS AND VCLS IS NOT NULL) OR (STKIN.CLS ='直配出' AND VCLS IS NULL))
       and  (STKIN.BILLTO = VENDOR.GID)
       --and  (STKIN.STAT = STKINLOG.STAT)
       and  (STKINLOG.STAT IN (1000, 1020, 1040, 320, 340))
       and  (STKINLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKINLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (STKIN.NUM LIKE VNUM||'%' OR VNUM IS NULL)
       and  (GOODSH.CODE LIKE VGDCODE||'%' OR VGDCODE IS NULL));
  COMMIT;
    ---插入直配出退数据
  INSERT INTO H4RTMP_PHMX(NUM,CLS,GDCODE,GDNAME,GDCODE2,STNAME,QTY,QTYSTR,PRICE,TOTAL,TAX,CAMT,CTAX,RTOTAL,STATNAME,FILDATE,LINE,STCODE)
    SELECT STKIN.NUM , STKIN.CLS , GOODSH.CODE , GOODSH.NAME , GOODSH.CODE2 , 
      VENDOR.NAME , -STKINDTL.QTY ,'-'|| STKINDTL.QTYSTR , 
      STKINDTL.PRICE , -STKINDTL.TOTAL , -STKINDTL.TAX , -STKINDTL.CAMT , 
      -STKINDTL.CTAX , -STKINDTL.RTOTAL , MODULESTAT.STATNAME,STKINLOG.TIME,STKINDTL.LINE,VENDOR.CODE
    FROM DIRALC STKIN, DIRALCLOG STKINLOG, DIRALCDTL STKINDTL, GOODSH GOODSH, MODULESTAT MODULESTAT, VENDOR VENDOR
      WHERE ((STKIN.NUM = STKINDTL.NUM)
       and  (STKIN.CLS = STKINDTL.CLS)
       and  (STKIN.NUM = STKINLOG.NUM)
       and  (STKIN.CLS = STKINLOG.CLS)
       and  (STKIN.STAT = MODULESTAT.NO)
       and  (STKINDTL.GDGID = GOODSH.GID)
       and  ((STKIN.CLS = VCLS AND VCLS IS NOT NULL) OR (STKIN.CLS ='直配出退' AND VCLS IS NULL))
       and  (STKIN.BILLTO = VENDOR.GID)
       --and  (STKIN.STAT = STKINLOG.STAT)
       and  (STKINLOG.STAT IN (700, 720, 740, 320, 340))
       and  (STKINLOG.TIME >= VBDATE OR VBDATE IS NULL)
       and  (STKINLOG.TIME < VEDATE OR VEDATE IS NULL)
       and  (STKIN.NUM LIKE VNUM||'%' OR VNUM IS NULL)
       and  (GOODSH.CODE LIKE VGDCODE||'%' OR VGDCODE IS NULL));
  COMMIT;
END;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>H4RTMP_PHMX</TABLE>
    <ALIAS>H4RTMP_PHMX</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
  <TABLEITEM>
    <TABLE>TMP_VCODE</TABLE>
    <ALIAS>TMP_VCODE</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
  <JOINITEM>
    <LEFT>H4RTMP_PHMX.STCODE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>TMP_VCODE.VCODE</RIGHT>
  </JOINITEM>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>4</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>NUM</COLUMN>
    <TITLE>单号</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>NUM</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>cls</COLUMN>
    <TITLE>单据类型</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>cls</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>line</COLUMN>
    <TITLE>行号</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>line</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>gdcode</COLUMN>
    <TITLE>商品代码</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>gdcode</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>gdname</COLUMN>
    <TITLE>商品名称</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>gdname</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>gdcode2</COLUMN>
    <TITLE>商品条码</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>gdcode2</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>qty</COLUMN>
    <TITLE>数量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>qty</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>qtystr</COLUMN>
    <TITLE>包装数量</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>qtystr</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>price</COLUMN>
    <TITLE>包装规格价</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>price</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>total</COLUMN>
    <TITLE>进货含税金额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>total</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>tax</COLUMN>
    <TITLE>进货税额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>tax</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>camt</COLUMN>
    <TITLE>进货去税成本额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>camt</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>ctax</COLUMN>
    <TITLE>进货成本税额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>ctax</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>rtotal</COLUMN>
    <TITLE>进货零售额</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>rtotal</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>,0.00</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>statname</COLUMN>
    <TITLE>单据状态</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>statname</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>fildate</COLUMN>
    <TITLE>收发货操作时间</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>fildate</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>stname</COLUMN>
    <TITLE>供应商名称</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>stname</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>STCODE</COLUMN>
    <TITLE>供应商代码</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>STCODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>92</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>56</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>32</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>56</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>224</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>86</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>71</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>56</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>68</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>102</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>84</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>92</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>80</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>68</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>56</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>122</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>224</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>68</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
  <GROUPITEM>
    <COLUMN>NUM</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>cls</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>line</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>gdcode</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>gdname</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>gdcode2</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>qtystr</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>price</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>statname</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>fildate</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>stname</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>STCODE</COLUMN>
  </GROUPITEM>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>数量</COLUMN>
    <ORDER>DESC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>fildate</LEFT>
    <OPERATOR>>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>fildate</LEFT>
    <OPERATOR><</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>NUM</LEFT>
    <OPERATOR>LIKE</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>gdcode</LEFT>
    <OPERATOR>LIKE</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>cls</LEFT>
    <OPERATOR>IN</OPERATOR>
    <RIGHT>
      <RIGHTITEM>直配出</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
      <PICKNAMEITEM>自营进</PICKNAMEITEM>
      <PICKNAMEITEM>自营进退</PICKNAMEITEM>
      <PICKNAMEITEM>直配出</PICKNAMEITEM>
      <PICKNAMEITEM>直配出退</PICKNAMEITEM>
    </PICKNAME>
    <PICKVALUE>
      <PICKVALUEITEM>自营进</PICKVALUEITEM>
      <PICKVALUEITEM>自营进退</PICKVALUEITEM>
      <PICKVALUEITEM>直配出</PICKVALUEITEM>
      <PICKVALUEITEM>直配出退</PICKVALUEITEM>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>STCODE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>151</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>122</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>170</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>153</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>99</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>124</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM>直配出</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>0</NUMOFNEXTQRY>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>TRUE</DXLOADMETHOD>
  <DXSHOWGROUP>TRUE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>TRUE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>TRUE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>16777215</DXCOLORODDROW>
  <DXCOLOREVENROW>15921906</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERTYPE></DXFILTERTYPE>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE>入库单明细查询（配货业务）</RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>18</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
  <RPTCOLUMNWIDTHITEM>92</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>32</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>97</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>86</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>38</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>80</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>92</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>80</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>122</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>128</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>56</RPTCOLUMNWIDTHITEM>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
</RPTREPORTLIST>
</SQLREPORT>

