<VERSION>4.1.1</VERSION>
<SQLQUERY>
<REMARK>
[标题]

[应用背景]

[结果列描述]

[必要的查询条件]

[实现方法]

[其它]
</REMARK>
<BEFORERUN>
DECLARE
  vdate     date;
  vbgndata  date;
  venddate  date;
  VSTAT     INT;
  VCOUNT    INT;
  VCODE     VARCHAR2(24);
  VVDRGID   VARCHAR2(24);
  VTOTAL    NUMBER(24,2);
  VSALETOTAL NUMBER(24,2);
  VFEETOTAL  NUMBER(24,2);
  VPAYTOTAL   NUMBER(24,2);
  VTAX        NUMBER(24,2);
  VPREPAYTOTAL  NUMBER(24,2);
  VPREPAYBCKTOTAL   NUMBER(24,2);
  VDPTBILLTOTAL  NUMBER(24,2);
  VVDRPAYTOTAL   NUMBER(24,2);
  VVDRPAYBCKTOTAL   NUMBER(24,2);
  VPAY_SALETOTAL   NUMBER(24,2);
  VPAY_FEETOTAL   NUMBER(24,2);
  VPAY_PREPAYTOTAL   NUMBER(24,2);
  CURSOR C IS SELECT FILDATE,VENDOR
                 FROM H4RTMP_CWTZ ORDER BY FILDATE ASC;
begin

  delete from H4RTMP_CWTZ;
  delete from H4RTMP_CWTZ_TMP;
  delete from H4RTMP_CWTZ01;
  commit;



  vbgndata:=to_date('\(1,1)','yyyy.mm.dd');
  venddate:=to_date('\(2,1)','yyyy.mm.dd')+1; 
  VCODE:='\(3,1)';
-----------------供应商进/退货明细 
  INSERT INTO H4RTMP_CWTZ(CLS,NUM,SETTLENO,VENDOR,FILDATE,STKINAMT,
  ORDNUM,stat)
  select s.cls,s.num,s.settleno,s.billto,l.time,s.total,s.ordnum,decode(s.ivcreg,1,1,s.ivcpay) 
  from stkin s , stkinlog l
  where
     s.num=l.num
     and s.cls=l.cls  
     and l.stat in (1000, 1020, 1040, 320 ,340) 
        and l.time < venddate 
        and l.time >= vbgndata 
        ORDER BY l.time;
   INSERT INTO H4RTMP_CWTZ(CLS,NUM,SETTLENO,VENDOR,FILDATE,STKINAMT,
  ORDNUM,stat)
  select d.cls,d.num,d.settleno,d.billto,l.time,d.total,d.ordnum ,decode(d.ivcreg,1,1,d.ivcpay)
         from DIRALC d,diralclog l
         where   d.num =l.num
          and d.cls=l.cls
          and l.stat in (1000, 1020, 1040, 320, 340)
          and l.cls='直配出'
          and l.time< venddate 
          and l.time>= vbgndata  
  ORDER BY l.time;

  INSERT INTO H4RTMP_CWTZ(CLS,NUM,SETTLENO,VENDOR,FILDATE,
  STKBCKAMT,stat)
  select s.cls,s.num,s.settleno,s.billto,l.time,-s.total,decode(s.ivcreg,1,1,s.ivcpay) 
  from stkinbck s,stkinbcklog l
       where   s.num=l.num
     and s.cls=l.cls  
     and l.stat in (700,720,740,320,340) 
        and l.time < venddate 
        and l.time >= vbgndata 
        ORDER BY l.time;
   INSERT INTO H4RTMP_CWTZ(CLS,NUM,SETTLENO,VENDOR,FILDATE,STKINAMT,stat)
  select d.cls,d.num,d.settleno,d.billto,l.time,-d.total,decode(d.ivcreg,1,1,d.ivcpay)
  from DIRALC d,diralclog l
         where   d.num =l.num
          and d.cls=l.cls
          and l.stat in (700, 720, 740, 320, 340)
       and l.cls='直配出退' 
       and l.time < venddate 
       and l.time >= vbgndata 
  ORDER BY l.time;
 ------------费用（预付款、费用、压库金额）
  
  INSERT INTO H4RTMP_CWTZ(CLS,NUM,VENDOR,FILDATE,PREPAY)
  SELECT  '预付款',NUM,VENDOR,ocrdate,CNTRPREPAY.TOTAL
  FROM CNTRPREPAY
  WHERE stat in (900,300)
  and ocrdate < venddate 
  AND  ocrdate >= vbgndata  
  ORDER BY ocrdate;
  ------1
  INSERT INTO H4RTMP_CWTZ(CLS,NUM,VENDOR,FILDATE,PREPAYBCK)
  SELECT  '预付款还款',NUM,VENDOR,ocrdate,CTPrePayRtn.TOTAL
  FROM CTPrePayRtn
  WHERE stat in (900,300)
  and ocrdate <   venddate
  AND  ocrdate >= vbgndata  
  ORDER BY ocrdate;
  
  INSERT INTO H4RTMP_CWTZ(CLS,NUM,SETTLENO,VENDOR,FEE,FILDATE) 
  SELECT '费用',NUM,SETTLENO,BILLTO,REALAMT*paydirect,ocrdate
  FROM CHGBOOK
  WHERE STAT in (500,300)
  and ocrdate < venddate
  AND  ocrdate >= vbgndata  
  ORDER BY ocrdate;
  
  INSERT INTO H4RTMP_CWTZ(CLS,NUM,VENDOR,DPTBILL,FILDATE) 
  SELECT CLS||'压库金额',NUM,VENDOR,DECODE(CLS,'收',1,'付',-1,0)*TOTAL,FILDATE
  FROM CNTRDPTBILL
  WHERE STAT in (1800,900,300)
  and FILDATE < venddate
  AND  FILDATE >= vbgndata  
  ORDER BY FILDATE; 

   -----------交款单
   INSERT INTO H4RTMP_CWTZ(CLS,NUM,SETTLENO,VENDOR,FILDATE,VDRPAY)
   select '交款单',a.num,A.SETTLENO,a.vgid,a.FILDATE,a.paytotal
   from VDRPAY a
   where   a.stat in (500,300,1800)
     and a.FILDATE < venddate 
     AND  a.FILDATE >= vbgndata;

   -----------交款退款单
   INSERT INTO H4RTMP_CWTZ(CLS,NUM,VENDOR,FILDATE,VDRPAYBCK)
   select '交款退款单',a.num,a.vendor,a.ocrdate,a.total
   from CTVDRPAYRTN a
   where   a.stat in(900,300)
     and a.FILDATE < venddate 
     AND  a.FILDATE >= vbgndata ;

  --------付款金额  
  INSERT INTO H4RTMP_CWTZ(CLS,NUM,SETTLENO,VENDOR,FILDATE,PAY,stat,pay_sale,pay_fee,pay_prepay)
  select a.cls,a.num,A.SETTLENO,a.vdrgid,a.ocrdate,a.paytotal,2,saletotal,feetotal,prepaytotal
  from cntrpaycash a 
  where 
   a.stat in (900,300)
  and a.ocrdate < venddate 
  AND  a.ocrdate >= vbgndata  
  ORDER BY A.ocrdate;

 IF VCODE IS NOT NULL THEN
   SELECT COUNT(*) INTO VCOUNT FROM VENDOR WHERE CODE=VCODE;
     IF VCOUNT<>0  THEN
         SELECT GID INTO VVDRGID FROM VENDOR WHERE CODE=VCODE;
         DELETE FROM H4RTMP_CWTZ WHERE VENDOR<>VVDRGID;
         COMMIT;
     ELSE
       DELETE H4RTMP_CWTZ;
       COMMIT;
     END IF;
 END IF;

 --- 按日期统计供应商的账款情况
  INSERT INTO H4RTMP_CWTZ_TMP(VENDOR, FILDATE , TOTAL , SALETOTAL ,
    PREPAYTOTAL  ,PREPAYBCKTOTAL, FEETOTAL ,  DPTBILLTOTAL , VDRPAYTOTAL ,
    VDRPAYBCKTOTAL , PAYTOTAL ,PAY_SALETOTAL,PAY_FEETOTAL,PAY_PREPAYTOTAL, TAX )
    SELECT VENDOR, FILDATE , SUM(STKINAMT) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VTOTAL,----供应商进/退货 
      SUM(STKBCKAMT) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VSALETOTAL,----供应商进/退货 
      SUM(PREPAY) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VPREPAYTOTAL,---预付款
      SUM(PREPAYBCK) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VPREPAYBCKTOTAL,---预付款还款
      SUM(FEE) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VFEETOTAL,-----费用
      SUM(DPTBILL) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VDPTBILLTOTAL,------压库金额
      SUM(VDRPAY) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VVDRPAYTOTAL,------交款单
      SUM(VDRPAYBCK) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VVDRPAYTOTAL,------交款退款单
      SUM(PAY) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VPAYTOTAL ,--付款金额
      SUM(PAY_SALE) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VPAY_SALETOTAL ,--付款单中货款金额
      SUM(PAY_FEE) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VPAY_FEETOTAL ,--付款中费用金额
      SUM(PAY_PREPAY) OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING) VPAY_PREPAYTOTAL ,--付款中预付款金额   
      SUM(STKINAMT+STKBCKAMT-PREPAY+PREPAYBCK-FEE-DPTBILL-PAY+VDRPAY-VDRPAYBCK) 
      OVER (PARTITION BY VENDOR ORDER BY FILDATE
           RANGE UNBOUNDED PRECEDING)  VTAX --应付账款
     FROM H4RTMP_CWTZ  ;
     
    UPDATE H4RTMP_CWTZ SET 
     TOTAL = (SELECT max(TOTAL) FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ),
     SALETOTAL = (SELECT max(SALETOTAL) FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ),
     PREPAYTOTAL = (SELECT max(PREPAYTOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ), 
     PREPAYBCKTOTAL = (SELECT max(PREPAYBCKTOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ), 
     FEETOTAL = (SELECT  max(FEETOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ), 
     DPTBILLTOTAL = (SELECT  max(DPTBILLTOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ), 
     VDRPAYTOTAL = (SELECT  max(VDRPAYTOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ),
     VDRPAYBCKTOTAL = (SELECT max(VDRPAYBCKTOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ),
     PAYTOTAL = (SELECT  max(PAYTOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ),
     PAY_SALETOTAL = (SELECT  max(PAY_SALETOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ), 
     PAY_FEETOTAL = (SELECT  max(PAY_FEETOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ), 
     PAY_PREPAYTOTAL = (SELECT  max(PAY_PREPAYTOTAL)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE ),  
     TAX = (SELECT  max(TAX)  FROM H4RTMP_CWTZ_TMP
      WHERE VENDOR = H4RTMP_CWTZ.VENDOR  AND FILDATE = H4RTMP_CWTZ.FILDATE )
     ;
     
  /**FOR R IN C LOOP
      SELECT SUM(STKINAMT) INTO VTOTAL----供应商进/退货
             FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;
      UPDATE H4RTMP_CWTZ SET TOTAL=VTOTAL 
         WHERE 
             VENDOR=R.VENDOR AND FILDATE=R.FILDATE;

      SELECT SUM(STKBCKAMT) INTO VSALETOTAL----供应商进/退货
             FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;
      UPDATE H4RTMP_CWTZ SET SALETOTAL=VSALETOTAL 
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE ;

      SELECT SUM(PREPAY) INTO VPREPAYTOTAL---预付款
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;
      UPDATE H4RTMP_CWTZ SET PREPAYTOTAL=VPREPAYTOTAL 
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;

      SELECT SUM(PREPAYBCK) INTO VPREPAYBCKTOTAL---预付款还款
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE+1;
      UPDATE H4RTMP_CWTZ SET PREPAYBCKTOTAL = VPREPAYBCKTOTAL 
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE+1;

      SELECT SUM(FEE) INTO VFEETOTAL-----费用
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;
      UPDATE H4RTMP_CWTZ SET FEETOTAL=VFEETOTAL 
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;

      SELECT SUM(DPTBILL) INTO VDPTBILLTOTAL------压库金额
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;
      UPDATE H4RTMP_CWTZ SET DPTBILLTOTAL=VDPTBILLTOTAL 
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;

      SELECT SUM(VDRPAY) INTO VVDRPAYTOTAL------交款单
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;
      UPDATE H4RTMP_CWTZ SET VDRPAYTOTAL=VVDRPAYTOTAL
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;

      SELECT SUM(VDRPAYBCK) INTO VVDRPAYBCKTOTAL------交款退款单
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;
      UPDATE H4RTMP_CWTZ SET VDRPAYBCKTOTAL =VVDRPAYBCKTOTAL
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;
      ----付款单金额
      SELECT SUM(PAY) INTO VPAYTOTAL  
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;    
      UPDATE H4RTMP_CWTZ SET PAYTOTAL=VPAYTOTAL 
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;
      ----付款单中货款金额
      SELECT SUM(PAY_SALE) INTO VPAY_SALETOTAL  
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;    
      UPDATE H4RTMP_CWTZ SET PAY_SALETOTAL=VPAY_SALETOTAL
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;
      ----付款单中费用金额
      SELECT SUM(PAY_FEE) INTO VPAY_FEETOTAL  
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;    
      UPDATE H4RTMP_CWTZ SET PAY_FEETOTAL=VPAY_FEETOTAL 
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;
      ----付款单中预付款金额
      SELECT SUM(PAY_PREPAY) INTO VPAY_PREPAYTOTAL  
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;    
      UPDATE H4RTMP_CWTZ SET PAY_PREPAYTOTAL=VPAY_PREPAYTOTAL 
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;

      SELECT SUM(STKINAMT+STKBCKAMT-PREPAY+PREPAYBCK-FEE-DPTBILL-PAY+VDRPAY-VDRPAYBCK) INTO VTAX
              FROM H4RTMP_CWTZ WHERE VENDOR=R.VENDOR AND FILDATE<=R.FILDATE;
     SUM(STKINAMT+STKBCKAMT-PREPAY-FEE-DPTBILL-PAY+VDRPAY-VDRPAYBCK) 
      UPDATE H4RTMP_CWTZ SET TAX=VTAX 
         WHERE 
              VENDOR=R.VENDOR AND FILDATE=R.FILDATE;
      END LOOP;***/

   ----MODIFY BY CHE 090326  修改交款汇总列TOTAL
  INSERT INTO H4RTMP_CWTZ(CLS,VENDOR,FILDATE,STKINAMT,STKBCKAMT,PREPAY,PREPAYBCK,FEE,DPTBILL,VDRPAYTOTAL,VDRPAYBCKTOTAL,PAY,TAX,STAT,PAY_SALE,PAY_FEE,PAY_PREPAY)
  select '合计',VENDOR,vbgndata,SUM(STKINAMT),SUM(STKBCKAMT),SUM(PREPAY),SUM(PREPAYBCK),sum(FEE),SUM(DPTBILL),SUM(VDRPAY),
  SUM(VDRPAYBCK),sum(PAY),SUM(STKINAMT+STKBCKAMT-PREPAY+PREPAYBCK-FEE+DPTBILL-PAY+VDRPAY-VDRPAYBCK),100,SUM(PAY_SALE),SUM(PAY_FEE),SUM(PAY_PREPAY)               
  from H4RTMP_CWTZ
  group by VENDOR;
  commit;

  insert into H4RTMP_CWTZ01(CLS,PVICLS,NUM,PVINUM,SETTLENO,VENDOR,FILDATE,PAYDATE,TOTAL,TAX,ORDNUM,STAT,PAYMODE,GDGID
		,IVCAMT,SALETOTAL,FEETOTAL,PAYTOTAL,PREPAYTOTAL,PREPAYBCKTOTAL,DPTBILLTOTAL,STKINAMT,STKBCKAMT,PAY,FEE,PREPAY,PREPAYBCK,DPTBILL,VDRPAY
		,VDRPAYBCK,VDRPAYTOTAL,VDRPAYBCKTOTAL,BGNDATE,ENDDATE,LINE,PAY_SALETOTAL,PAY_FEETOTAL,PAY_PREPAYTOTAL,PAY_SALE,PAY_FEE,PAY_PREPAY) 
	select CLS,PVICLS,NUM,PVINUM,SETTLENO,VENDOR,FILDATE,PAYDATE,TOTAL,TAX,ORDNUM,STAT,PAYMODE,GDGID
		,IVCAMT,SALETOTAL,FEETOTAL,PAYTOTAL,PREPAYTOTAL,PREPAYBCKTOTAL,DPTBILLTOTAL,STKINAMT,STKBCKAMT,PAY,FEE,PREPAY,PREPAYBCK,DPTBILL,VDRPAY
		,VDRPAYBCK,VDRPAYTOTAL,VDRPAYBCKTOTAL,BGNDATE,ENDDATE,LINE,PAY_SALETOTAL,PAY_FEETOTAL,PAY_PREPAYTOTAL ,PAY_SALE,PAY_FEE,PAY_PREPAY
         from  H4RTMP_CWTZ; 
end;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>VENDORH</TABLE>
    <ALIAS>VENDORH</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
  <TABLEITEM>
    <TABLE>H4RTMP_CWTZ</TABLE>
    <ALIAS>H4RTMP_CWTZ</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
  <JOINITEM>
    <LEFT>H4RTMP_CWTZ.VENDOR</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>VENDORH.GID</RIGHT>
  </JOINITEM>
  <JOINITEM>
    <LEFT>H4RTMP_CWTZ.STAT</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>100</RIGHT>
  </JOINITEM>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>0</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>VENDORH.CODE</COLUMN>
    <TITLE>供应商代码</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>CODE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>VENDORH.NAME</COLUMN>
    <TITLE>供应商名称</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>NAME</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.STKINAMT</COLUMN>
    <TITLE>进货金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>TOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.STKBCKAMT</COLUMN>
    <TITLE>退货金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>SALETOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.STKINAMT+H4RTMP_CWTZ.STKBCKAMT</COLUMN>
    <TITLE>净进货金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>JJHJINE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.PREPAY</COLUMN>
    <TITLE>预付款总额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PREPAYTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.PAY</COLUMN>
    <TITLE>付款总额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PAYTOTAL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.TAX</COLUMN>
    <TITLE>应付款</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>TAX</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.PREPAYBCK</COLUMN>
    <TITLE>预付款还款金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PREPAYBCK</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.PAY_SALE</COLUMN>
    <TITLE>已付款货款</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PAY_SALE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION>SUM</AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.PAY_PREPAY</COLUMN>
    <TITLE>预付款付款金额</TITLE>
    <FIELDTYPE>6</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION>SUM</GAGGREGATION>
    <DISPLAYINNEXT>TRUE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PAY_PREPAY</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>VENDORH.PAYTERMS</COLUMN>
    <TITLE>付款天数</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>PAYTERMS</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>H4RTMP_CWTZ.FILDATE</COLUMN>
    <TITLE>记帐日期</TITLE>
    <FIELDTYPE>0</FIELDTYPE>
    <VISIBLE>FALSE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>FILDATE</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>68</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>176</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>92</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>93</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>92</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>90</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>86</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>64</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>102</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>103</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>114</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>78</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>74</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>90</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>73</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>102</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
  <GROUPITEM>
    <COLUMN>VENDORH.CODE</COLUMN>
  </GROUPITEM>
  <GROUPITEM>
    <COLUMN>VENDORH.NAME</COLUMN>
  </GROUPITEM>
</GROUPLIST>
<ORDERLIST>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>H4RTMP_CWTZ.FILDATE</LEFT>
    <OPERATOR>>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2014.12.01</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>月初</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>H4RTMP_CWTZ.FILDATE</LEFT>
    <OPERATOR><=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>2014.12.03</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>2</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE>今天</DEFAULTVALUE>
    <ISREQUIRED>TRUE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>VENDORH.CODE</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
  <CRITERIAITEM>
    <LEFT>VENDORH.NAME</LEFT>
    <OPERATOR>LIKE</OPERATOR>
    <RIGHT>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>114</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>102</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
  <CRITERIAWIDTHITEM>100</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM>2014.12.01</SGLINEITEM>
    <SGLINEITEM>2014.12.03</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>1</NUMOFNEXTQRY>
  <NCRITERIALIST>
    <NEXTQUERY>供应商台账明细.sql</NEXTQUERY>
    <NCRITERIAITEM>
      <LEFT>供应商代码等于</LEFT>
      <RIGHT>供应商代码</RIGHT>
    </NCRITERIAITEM>
    <NCRITERIAITEM>
      <LEFT>.记帐日期大于等于</LEFT>
      <RIGHT>记帐日期大于等于</RIGHT>
    </NCRITERIAITEM>
    <NCRITERIAITEM>
      <LEFT>.记帐日期小于等于</LEFT>
      <RIGHT>记帐日期小于等于</RIGHT>
    </NCRITERIAITEM>
  </NCRITERIALIST>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>FALSE</DXLOADMETHOD>
  <DXSHOWGROUP>FALSE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>FALSE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>FALSE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>15921906</DXCOLORODDROW>
  <DXCOLOREVENROW>-2147483643</DXCOLOREVENROW>
  <DXFILTERNAME>TAX</DXFILTERNAME>
  <DXFILTERTYPE></DXFILTERTYPE>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE>供应商台账</RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>11</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
  <RPTCOLUMNWIDTHITEM>64</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>141</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>62</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>93</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>80</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>44</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>68</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>85</RPTCOLUMNWIDTHITEM>
  <RPTCOLUMNWIDTHITEM>75</RPTCOLUMNWIDTHITEM>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
供应商台账.frf
</RPTREPORTLIST>
</SQLREPORT>

