---
- name: copy nginx source code package to remote host
  copy: src=nginx/nginx-1.20.2.tar.gz dest=/usr/local/src/nginx-1.20.2.tar.gz
  tags: copyNginxPackage
- name: unzip nginx source code package and compile install nginx
  shell: cd /usr/local/src && tar zxf nginx-1.20.2.tar.gz && cd nginx-1.20.2 && ./configure --prefix=/usr/local/nginx --user=nginx --group=nginx --with-http_ssl_module --with-http_stub_status_module --with-http_gzip_static_module --with-file-aio --with-http_dav_module --with-http_sub_module --with-http_realip_module --with-stream --with-pcre=/usr/local/src/pcre-8.37 && make && make install && chown -R nginx:nginx /usr/local/nginx
