apiVersion: v1
kind: Service
metadata:
  name: service-redis
  namespace: default
spec:
  selector:
    app: redis
    role: logstor
  type: ClusterIP
  clusterIP: 10.97.97.97
  ports:
  - name: service-redis
    port: 6379
    targetPort: 6379
    protocol: TCP
    
