version: '3'
services:
  redis:
    image: redis:6.0.6
    container_name: redis
    hostname: redis
    restart: always
    volumes:
      - /data/elasticsearch/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/elasticsearch/redis:/data
      - /etc/localtime:/etc/localtime
    ports:
      - 6379:6379
    command:
      - "/bin/sh"
      - "-c"
      - "redis-server /usr/local/etc/redis/redis.conf"
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 2G
        reservations:
           cpus: '0.5'
           memory: 100M
networks:
  default:
    external:
      name: elk

