version: '3'
services:
  elasticsearch:        
    image: elasticsearch:7.1.1    
    container_name: elasticsearch  
    hostname: elasticsearch
    restart: always                 
    #network_mode: host
    environment:                                    
      - discovery.type=single-node 
      - node.name=els-master             
      - network.publish_host=192.168.3.150
      - network.host=0.0.0.0               
      - bootstrap.memory_lock=true  
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"   
    ulimits:             
      memlock:
        soft: -1      
        hard: -1
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 3G
        reservations:
           cpus: '0.5'
           memory: 200M
    volumes:
      - /data/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
      - esdata:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    ports:
      - 9200:9200 
      - 9300:9300  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    hostname: kibana
    restart: always                 
    #network_mode: host
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200 
    depends_on:
      - elasticsearch  
    restart: always
    volumes:
      - /data/elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /etc/localtime:/etc/localtime
    ports:
      - 5601:5601
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 1G
        reservations:
           cpus: '0.5'
           memory: 100M
  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    container_name: logstash
    hostname: logstash
    restart: always
    #network_mode: host
    volumes:
      - /data/elasticsearch/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /etc/localtime:/etc/localtime
    depends_on:
      - elasticsearch
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 2G
        reservations:
           cpus: '0.5'
           memory: 200M
volumes:
  esdata:
    driver: local
networks:
  default:
    external:
      name: elk
