version: '3'
services:
  nginx:
    image: nginx:1.19.1
    container_name: nginx
    hostname: nginx
    restart: always
    #network_mode: host
    volumes:
      - /data/elasticsearch/.login.txt:/etc/nginx/.login.txt
      - /data/elasticsearch/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5602:5601
      - 9201:9200
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 500M
        reservations:
           cpus: '0.5'
           memory: 100M
networks:
  default:
    external:
      name: elk
