version: '3'
services:
  nginx:
    image: nginx:1.19.1
    container_name: nginx
    hostname: nginx
    restart: always
    network_mode: host
    volumes:
      - /data/elasticsearch/.users:/etc/nginx/.users
      - /data/elasticsearch/default.conf:/etc/nginx/conf.d/default.conf
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 500M
        reservations:
           cpus: '0.5'
           memory: 100M
