filebeat.inputs:
- type: log
  enabled: true
  paths:
    /home/ywtest/jar/web-forward/log/web-forward.log
  tags: ["web-forward-log-access"]
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}\:[0-9]{2}\:[0-9]{2}\.[0-9]{3}'
  multiline.negate: true
  multiline.match: after
- type: log
  enabled: true
  paths:
    /home/ywtest/jar/web-forward/log/web-forward_error.log
  tags: ["web-forward-log-error"]
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}\:[0-9]{2}\:[0-9]{2}\.[0-9]{3}'
  multiline.negate: true
  multiline.match: after
output.redis:
  hosts: ["127.0.0.1:6379"]
  key: web-forward-log
  password: jack
  db: 10
