filebeat.inputs:
- type: log
  enabled: true
  paths:
  - /home/ywtest/jar/web-forward/log/web-forward.log
  - /home/ywtest/jar/web-forward/log/web-forward_error.log
  tags: ["web-forward-log"]
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}\:[0-9]{2}\:[0-9]{2}\.[0-9]{3}'
  multiline.negate: true
  multiline.match: after
  fields:
    hostIP: 106.15.42.147
  fields_under_root: true
output.redis:
  hosts: ["58.33.49.196:9379"]
  key: haohong-log
  db: 10
  password: "testpw"
