apiVersion: v1
kind: Pod
metadata: 
  name: pod-hostpath
  namespace: default
spec:
  containers:
  - name: myapp
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    command: ["/bin/sh","-c","/bin/httpd -f -h /data/web/html"]
    volumeMounts:
    - name: html
      mountPath: /data/web/html
  volumes:
  - name: html
    hostPath:
      path: /data/pod/volume1
      type: DirectoryOrCreate
  
