apiVersion: v1
kind: Pod
metadata: 
  name: pod-emptydir
  namespace: default
  labels: 
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp
    image: busybox:latest
    ports:
    - name: http
      containerPort: 80
    command: ["/bin/sh","-c","/bin/httpd -f -h /data/web/html"]
    volumeMounts:
    - name: html
      mountPath: /data/web/html
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: html
      mountPath: /data
    command:
    - "/bin/sh"
    - "-c"
    - "while true;do echo $(date) >> /data/index.html;sleep 2;done"
  volumes:
  - name: html
    emptyDir: {}
  
