apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret-env
  namespace: default
  labels: 
    app: myapp
    tier: frontend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    env: 
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-userpassword
          key: password 
          optional: true
