--账单撤销
select TrainBillStatus,* from Topway..AccountStatement 
--update Topway..AccountStatement  set TrainBillStatus=1
where BillNumber='019394_20190301'

--2018年4月26日之后，添加过“国内特殊线路”的差旅客户名单

select t1.cmpid as 单位编号,t1.cmpname as 单位名称
,(case CustomerType when 'A' then '差旅单位客户' when 'C' then '旅游单位客户' else '' end) as 单位类型
,(CASE hztype WHEN 0 THEN '我方终止合作' WHEN 1 THEN '正常合作正常月结' WHEN 2 THEN '正常合作仅限现结' WHEN 3 THEN '正常合作临时月结' WHEN 4 THEN '对方终止合作'  ELSE '' END) as 合作状态
,(select top 1t9.name from homsomDB..SSO_Users t9 inner join homsomDB..Trv_UnitCompanies_AccountManagers t6 on t9.ID=t6.EmployeeID where t6.UnitCompanyID=t4.id) as 客户经理
,(select top 1t9.name from homsomDB..SSO_Users t9 inner join homsomDB..Trv_TktUnitCompanies_TktTCs t8 on t9.id=t8.TktTCID where t8.TktUnitCompanyID=t4.ID) as 差旅业务顾问
from tbCompanyM t1
left join homsomdb..Trv_UnitCompanies t4 on t1.cmpid=t4.Cmpid
left join homsomDB..Trv_UnitCompies_Sales t5 on t4.ID=t5.UnitCompayID
--客户经理
left join homsomDB..Trv_UnitCompanies_AccountManagers t6 on t4.ID=t6.UnitCompanyID
--维护人
left join homsomDB..Trv_UnitCompanies_KEYAccountManagers t10 on t10.UnitCompanyID=t4.ID
--差旅业务顾问
left join homsomDB..Trv_TktUnitCompanies_TktTCs t8 on t8.TktUnitCompanyID=t4.ID
--人员信息
left join homsomDB..SSO_Users t9 on
t9.ID=t5.EmployeeID and t9.ID=t6.EmployeeID and t9.ID=t8.TktTCID 
where
t4.ID in (Select UnitCompanyID from homsomDB..Trv_FlightAdvancedPolicies where Name='国内机票特殊线路' and CreateDate>='2018-04-26')
and t4.Type='A'
and t4.Cmpid not in ('000003','000006')



select EmployeeName,Duty,Department from ApproveBase..HR_Employee where DeptCode='差旅运营部'
order by Department

select * from ApproveBase..HR_Employee  where DeptCode='差旅运营部'

--导入成本中心
--select * from homsomDB..Trv_UnitCompanies where Cmpid='017745'
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='许伟丽')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='于真真')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='赵伟')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈冲')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐健')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李源安')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郑小军')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='周刚')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张大林')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王琳')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='钟德显')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='刘晓江')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='吕炜洪')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王天宁')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='樊秋燕')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郑良')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郑君')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='石泓泽')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='胡存根')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈涛')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张蓓')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='单永梅')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='韩娟')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王雪')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郑韵')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='宋斌')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='胡俊忠')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张若曦')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杜文斯')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郭荣')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐斌')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='费凤仙')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='孙丽')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈文静')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈岗')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='沈永彩')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨阳')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='宋晓明')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='刘凯')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='刘莉莉')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='裴雪平')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='周德静')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='许涛')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='黄海涛')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='何鹏')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='韩强')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='邹磊')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='何东平')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李文斌')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='龙俊成')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐涌')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈娟')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='冯睿')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='任伟')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='程鑫')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐长安')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李轲')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨玉峰')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王方浪')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张屹')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='涂婷')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='宋素敏')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='罗丹')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨昌勇')

--（产品专用）申请费来源/金额信息（国际）
select feiyong,feiyonginfo,* from Topway..tbcash 
--update Topway..tbcash set feiyong=1816
where coupno='AS002367325'

--旅游预算单信息
--select * from Topway..tbCusholderM where mobilephone='13916402029'
select Custid,Custinfo,* from Topway..tbTravelBudget 
--update Topway..tbTravelBudget set Custid='D442836',Custinfo='13916402029@向雯娴@UC016646@德闻计量设备（上海）有限公司@向雯娴@13916402029@D170603'
where TrvId='29562'

--销售单匹配授权码
SELECT c.coupno,AuthorizationCode FROM tbcash c 
LEFT JOIN homsomDB..Trv_DomesticTicketRecord r ON c.coupno=r.RecordNumber
LEFT JOIN homsomDB..Trv_PnrInfos p ON r.PnrInfoID=p.ID
LEFT JOIN homsomDB..Trv_tktBookings i ON p.ItktBookingID=i.ID
where c.coupno in 
('AS002267511',
'AS002267513',
'AS002267693',
'AS002282083',
'AS002261661',
'AS002282133',
'AS002248910',
'AS002260080',
'AS002267560',
'AS002258973',
'AS002248912',
'AS002250055',
'AS002267562',
'AS002250053')

--销售单匹配成本中心
update homsomDB..Trv_UnitPersons set CostCenterID=(
Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') 
where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID 
where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨昌勇')

select h.Name,c.Name from homsomDB..Trv_UnitPersons u
left join homsomDB..Trv_Human h on h.ID=u.ID
left join homsomDB..Trv_CostCenter c on c.ID=u.CostCenterID
where h.IsDisplay=1 
and u.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1'
and h.Name in('吴展丞',
'文虎',
'寿岳峰',
'胡伟峰',
'王天宁',
'邹雨航',
'冉允召',
'李俊',
'刘晓燕',
'徐健',
'张存明',
'李晨熹',
'郭荣',
'费凤仙',
'王博',
'沈健玮',
'陈渺凤',
'徐斌',
'张庆鲁',
'周刚',
'赵广宇',
'黄小强',
'曹瑜',
'陆华',
'张大林',
'钟德显',
'张蓓',
'王颖',
'陈涛',
'陈岗',
'张雪',
'杨丽华',
'韩娟',
'王振成',
'李源安',
'刘莉莉',
'归捷',
'李学思',
'王伟君',
'朱艳',
'闫雪',
'唐蕊',
'胡俊忠')

--设置成本中心
--select * from homsomDB..Trv_UnitCompanies where Cmpid='017745'
--上海分公司
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='许伟丽')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='于真真')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='赵伟')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈冲')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐健')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李源安')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郑小军')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='周刚')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张大林')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王琳')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='钟德显')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='刘晓江')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='吕炜洪')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王天宁')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='樊秋燕')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郑良')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郑君')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='石泓泽')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海分公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='胡存根')

--上海子分公司

update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李晓明')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张存明')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='文虎')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王轶鹏')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张卉芳')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='胡晓红')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='辛惠君')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='雷新华')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈渺凤')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='赵晖')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='沈健玮')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='黄琼烨')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨丽华')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李晶')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='戴斯琪')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='姚凌怡')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='赵燕')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='邱锋')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='朱艳')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='秦依雯')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐羽')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='乔剑平')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='钟昊')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='冉允召')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='茅宋萍')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨燕霞')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='汤御雷')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='邱越峰')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='黄丽瑾')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='罗懿')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='沈俊敏')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张晓莉')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐连')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='邢春燕')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张晓立')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈晓东')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张姝')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈洁')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张玮')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='季寅')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李宁')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张雪')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王方')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='叶五彩')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李文彬')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='毛莉萍')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='于智华')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陆晓勤')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='闵莎莎')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王云')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='胡伟峰')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='孙莉')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='施琦')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='蒋珺')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王振成')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='赵广宇')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='闫雪')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='尉亚婷')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈超')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='马积文')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='钱俊杰')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='胡晓芸')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='LIUSONG')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李朝阳')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='曾红刚')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='蔡俊恺')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张晓云')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王友玮')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张庆鲁')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陆元炯')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='孙颖')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李晨熹')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='石少君')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='刘晓燕')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='包博')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='刘久毅')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨希')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张娅')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='戚骜')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='刘怡')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='姚建东')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='周如伟')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='储鑫')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陆燕')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李文俊')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='袁毅超')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李利君')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='黄小强')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张丽娜')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='安小霞')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张寅')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='曹瑜')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='归捷')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张文淼')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='贾诺明')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陆华')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='寿岳峰')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='钱鸿虎')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='袁惠君')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='俞璟珺')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='胡乐骏')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李文玲')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张婷')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈扬')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陆慧')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陆慧诚')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王静')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张咏华')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='汪晓婷')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='游博')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐雪梅')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='吴展丞')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='柳晓菲')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨周')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='梁京凯')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐盛裔')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王颖')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈涛')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张蓓')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='单永梅')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='韩娟')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王雪')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郑韵')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='宋斌')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='胡俊忠')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张若曦')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杜文斯')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='郭荣')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐斌')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='费凤仙')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='孙丽')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈文静')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈岗')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='沈永彩')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨阳')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='宋晓明')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='上海子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='刘凯')

--成都子分公司
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='刘莉莉')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='裴雪平')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='周德静')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='许涛')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='黄海涛')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='何鹏')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='韩强')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='邹磊')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='何东平')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李文斌')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='龙俊成')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐涌')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='陈娟')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='冯睿')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='任伟')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='程鑫')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='徐长安')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='李轲')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨玉峰')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='王方浪')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='张屹')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='涂婷')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='宋素敏')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='罗丹')
update homsomDB..Trv_UnitPersons set CostCenterID=(Select ID from homsomDB..Trv_CostCenter  where Name='成都子公司' and CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1') where ID in(Select up.ID from homsomDB..Trv_UnitPersons up inner join homsomDB..Trv_Human hu on hu.ID=up.ID where up.CompanyID='0AB3E1BC-2B6A-4CF7-BC81-853CC2C701E1' and IsDisplay=1 and hu.Name='杨昌勇')


--修改退票状态
select status2,* from Topway..tbReti 
--update Topway..tbReti  set status2=2
where reno in ('0430663','0430661')

--旅游收款单信息
select PayBak,* from Topway..tbTrvKhSk 
--update Topway..tbTrvKhSk set PayBak='羊海兰:20190329200040011100540018356809'
where TrvId='29784' and id='227471'


Select * from Topway..Emppwd  
--update Topway..Emppwd set team='差旅运营十组'
where idnumber=0686

Select * from Topway..Emppwd  
--update Topway..Emppwd set team='差旅运营二组'
where idnumber=0686

Select * from Topway..Emppwd  where team='差旅运营十组'

--（产品部专用）机票供应商来源（国际）
select t_source,* from Topway..tbcash 
--update Topway..tbcash set t_source='ZSBSPETI'
where coupno='AS002356636'

select totprice,price,fuprice,tax,* from Topway..tbcash where cmpcode='020459'
and datetime>='2018-08-01'
and datetime<'2018-12-01'
and inf=1
and fuprice<>0

--国内机票服务费销量
SELECT SUBSTRING(T1.ModifyBillNumber,8,6) 月份,SUM(price) 国内机票服务费销量 FROM Topway..tbcash T1 WITH (NOLOCK)
WHERE  cmpcode='020459'
AND T1.inf=0
AND T1.tickettype not IN ('改期费', '升舱费','改期升舱')
AND ISNULL(T1.ModifyBillNumber,'') <> ''
--AND (@CUSTID ='' OR @CUSTID IS NULL OR @CUSTID=T1.custid)
AND CAST(SUBSTRING(T1.ModifyBillNumber,8,6)+'01' AS DATETIME)>=CAST('2018-11'+'-01' AS DATETIME)
AND CAST(SUBSTRING(T1.ModifyBillNumber,8,6)+'01' AS DATETIME)<=CAST('2018-12'+'-01' AS DATETIME)
GROUP BY T1.ModifyBillNumber


--康宝莱部门分析表
select Department 部门,SUM(price) 不含税销量,count(*) 张数,SUM(price)/SUM(CAST(priceinfo AS DECIMAL)) 平均折扣率 
from Topway..V_TicketInfo where cmpcode='020459'
and ModifyBillNumber in ('020459_20180701','020459_20180801','020459_20180901','020459_20181001','020459_20181201')
and tickettype NOT IN ('改期费', '升舱费','改期升舱')
and inf=1
group by Department
order by 不含税销量 desc

select SUM(price) 合计不含税销量,count(*) 张数,SUM(price)/SUM(CAST(priceinfo AS DECIMAL)) 合计平均折扣率 
from Topway..V_TicketInfo where cmpcode='020459'
and ModifyBillNumber in ('020459_20180701','020459_20180801','020459_20180901','020459_20181001','020459_20181201')
and tickettype NOT IN ('改期费', '升舱费','改期升舱')
and inf=1
