global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'

rule_files:
  - "/usr/local/prometheus/rules/*.rule"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: 
      - '192.168.13.215:9100'
      - '192.168.13.218:9100'
      - '127.0.0.1:9100'
      - '192.168.13.21:9100'
      - '192.168.13.160:9100'
      - '192.168.13.161:9100'
      - '192.168.13.162:9100'
      - '192.168.13.223:9100'
      - '192.168.13.235:9100'
      - '192.168.13.237:9100'
      - '192.168.13.238:9100'
      - '192.168.13.239:9100'
      - '192.168.13.213:9100'
      - '192.168.13.206:9100'
      - '192.168.13.212:9100'
      - '192.168.13.31:9100'
      - '192.168.13.214:9100'
      - '192.168.13.33:9100'
      - '192.168.13.230:9100'
      - '192.168.13.32:9100'
      - '192.168.13.221:9100'
      - '192.168.13.116:9100'
  - job_name: 'blackbox-icmp'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - '58.246.78.149'
        labels:
          group: 'ISP:unicom'
      - targets:
        - '222.66.21.209'
        labels:
          group: 'ISP:telecom'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        replacement: ICMP:${1}
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: 'blackbox-http-elasticsearch-readonly'
    metrics_path: /probe
    params:
      module: [http_es_onlyread_test]
    static_configs:
      - targets:
        - http://hlog.hs.com:9200/clog/_settings?pretty=true
        - http://clog.hs.com:9200/clog/_settings?pretty=true
        - http://blog.hs.com:9200/homsom_log/_settings?pretty=true
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 127.0.0.1:9115
      - source_labels: [__param_target]
        replacement: HTTP:${1}
        target_label: instance
  - job_name: 'blackbox-http-elasticsearch-health'
    metrics_path: /probe
    params:
      module: [http_es_health_test]
    static_configs:
      - targets:
        - http://blog.hs.com:9200/_cat/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 127.0.0.1:9115
      - source_labels: [__param_target]
        replacement: HTTP:${1}
        target_label: instance
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_custom_httpcode]
    static_configs:
      - targets:
        - http://nexus.hs.com/
        - http://conf.hs.com
        - http://clog.hs.com
        - http://blog.hs.com
        - http://hlog.hs.com
        - http://jenkins.hs.com/login
        - http://newjenkins.hs.com/login
        - http://pm.hs.com/
        - http://gitlab.hs.com/
        - http://172.168.2.174:55505/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 127.0.0.1:9115
      - source_labels: [__param_target]
        replacement: HTTP:${1}
        target_label: instance
  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - 192.168.13.195:6379
        labels:
          description: 'pdredis1.hs.com,windows redis server'
      - targets:
        - 192.168.13.235:6379
        labels:
          description: 'pdredis2.hs.com,linux redis server'
      - targets:
        - 192.168.13.21:8081
        - 192.168.13.21:8090
        - 192.168.13.160:8081
        - 192.168.13.160:26389
        - 192.168.13.160:6379
        - 192.168.13.161:26379
        - 192.168.13.162:26399
        - 192.168.13.162:6379
        - 192.168.13.162:8081
        - 192.168.13.223:6002
        - 192.168.13.223:6001
        - 192.168.13.223:8002
        - 192.168.13.223:8001
        - 192.168.13.223:9200
        - 192.168.13.235:8000
        - 192.168.13.237:9200
        - 192.168.13.238:80
        - 192.168.13.238:8090
        - 192.168.13.238:8999
        - 192.168.13.238:8989
        - 192.168.13.238:10890
        - 192.168.13.238:10900
        - 192.168.13.238:10880
        - 192.168.13.238:11990
        - 192.168.13.238:11980
        - 192.168.13.238:8081
        - 192.168.13.239:9800
        - 192.168.13.239:11980
        - 192.168.13.239:8081
        - 192.168.13.239:8092
        - 192.168.13.239:11990
        - 192.168.13.239:8090
        - 192.168.13.239:9000
        - 192.168.13.239:10890
        - 192.168.13.239:10900
        - 192.168.13.239:10880
        - 192.168.13.239:8080
        - 192.168.13.239:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        replacement: TCP:${1}
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: 'docker'
    static_configs:
    - targets: 
      - '192.168.13.21:7070'
      - '192.168.13.160:7070'
      - '192.168.13.161:7070'
      - '192.168.13.162:7070'
      - '192.168.13.223:7070'
      - '192.168.13.235:7070'
      - '192.168.13.237:7070'
      - '192.168.13.238:7070'
      - '192.168.13.239:7070'
