# my global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
  - /usr/local/prometheus/rules/*.rule

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['localhost:9100']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['localhost:8080','192.168.15.202:8080','192.168.15.201:8080','192.168.15.199:8080']
