apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hpa-custom-deployment
  labels: 
    app: hpa-custom-deployment
  namespace: default
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ikubernetes/metrics-app
        ports:
        - name: http
          containerPort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa-v2-custom
  namespace: default
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: myapp   
  minReplicas: 1
  maxReplicas: 10 
  metrics:
  - type: Pods
    pods:
      metricName: http_requests
      targetAverageValue: 800m
