pkgInstall:
  pkg.installed:
    - pkgs:
      - gcc 
      - glibc
      - gcc-c++
      - pcre-devel
      - openssl-devel
      - net-tools
      - tree
      - iproute
      - screen
      - lrzsz
      - tree
      - lsof
      - unzip
      - zip
      - vim-enhanced
      - bind-utils
      - bc
      - bash-completion
      - lua-devel
