#!/bin/sh
#
# redis - this script starts and stops the redis-sentinel daemon
#
# chkconfig:   - 86 14
# description: redis sentinel service shell 
# processname: redis-sentinel
# config:      /usr/local/redis/sentinel.conf

 
# Source function library.
. /etc/rc.d/init.d/functions
 
# Source networking configuration.
. /etc/sysconfig/network
 
# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0
 
redis_sentinel="/usr/local/redis/bin/redis-sentinel"
prog=$(basename $redis_sentinel)
pid=$(ps aux | grep "${redis_sentinel}" | grep -v 'grep' | awk '{print $2}')
 
REDIS_SERVER_CONF_FILE="/usr/local/redis/sentinel.conf"
 
[ -f /etc/sysconfig/redis_sentinel ] && . /etc/sysconfig/redis_sentinel
 
lockfile=/var/lock/subsys/redis_sentinel.lock
 
start() {
    [ -x $redis_sentinel ] || exit 5
    [ -f $REDIS_SERVER_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    $redis_sentinel $REDIS_SERVER_CONF_FILE
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}
 
stop() {
    echo -n $"Stopping $prog: "
    kill -QUIT ${pid}
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}
 
restart() {
    stop
    sleep 1
    start
}
 
status() {
    /usr/bin/ps aux | /usr/bin/grep ${redis_sentinel} | /usr/bin/grep -v 'grep'  >& /dev/null && echo "$prog is running...." || echo "$prog is stop"
}
 
case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    status)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
