apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pvc-dynamic-longhorn-demo
spec: 
  accessModes: ["ReadWriteOnce"]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
