<VERSION>4.1.0</VERSION>
<SQLQUERY>
<REMARK>
[标题]
[应用背景] ：该报表由谁提出，要解决什么问题，用途
该报表是为了让系统管理员更方便地查询系统里的标准数据表的字段，利于平时的报表编辑，但
是对于自定义的非系统标准数据表暂时不在此报表范围之内。是作为数据表查询报表的下一查询
来使用。

[结果列描述] ：

[必要的查询条件] ：
数据表编号

[实现方法] ：简要描述报表的数据源、构造算法，以及关键列的算法
直接从collate和collateitem表中取数据，目前不涉及其他数据表。


[临时表结构]：如果有用到临时表，需要附加临时表的创建sql
为了方便系统表的查询，创建一张两个报表（系统表查询和数据表字段查询）都可以用的临时表
create global temporary table h4rtmp_collate
( 
  COLLATENO  INTEGER,
  TABLENAME  VARCHAR2(32),
  TABLELABEL VARCHAR2(64),
  STYLE      VARCHAR2(2),
  MASTER     INTEGER,
  ITEMNO     INTEGER,
  FIELDNAME  VARCHAR2(32),
  FIELDLABEL VARCHAR2(64),
) on commit preserve rows;
exec hdcreatesynonym('h4rtmp_collate','HD40');
exec granttoqryrole('h4rtmp_collate');

[版本记录]： 时间+创建人/修改人，后续修改在原有基础上追加
2010年10月02日 21:39 创建人：邹勇

[其它]：可选
</REMARK>
<BEFORERUN>
/*创建临时表，详情请见报表说明
create global temporary table h4rtmp_collate
( 
  COLLATENO  INTEGER,  --数据表编号
  TABLENAME  VARCHAR2(32),--数据表英文名
  TABLELABEL VARCHAR2(64),--数据表中文名
  STYLE      VARCHAR2(2),--数据表类型
  MASTER     INTEGER,--对应的主表编号
  ITEMNO     INTEGER,--数据表字段编号
  FIELDNAME  VARCHAR2(32),--数据表字段英文名
  FIELDLABEL VARCHAR2(64)--数据表字段中文名
) on commit preserve rows;
exec hdcreatesynonym('h4rtmp_collate','HD40');
exec granttoqryrole('h4rtmp_collate');
*/

DECLARE
VCOLLATENO  INTEGER;
--VTABLENAME  VARCHAR2(32);--数据表英文名
--VTABLELABEL VARCHAR2(64);--数据表中文名
--VFIELDNAME  VARCHAR2(32);--数据表字段英文名
--VFIELDLABEL VARCHAR2(64);--数据表字段中文名

BEGIN
VCOLLATENO:= '\(1,1)'; 
--VTABLENAME:= '\(2,1)'; 
--VTABLELABEL:= '\(3,1)';
--VFIELDNAME:='\(4,1)';
--VFIELDLABEL:='\(5,1)';


--清空临时表中数据
DELETE FROM h4rtmp_collate; 
--一定要提交事务
COMMIT;		           

INSERT INTO h4rtmp_collate(COLLATENO,TABLENAME,TABLELABEL,FIELDNAME,FIELDLABEL)
select a.no,a.tablename,a.tablelabel,b.FIELDNAME,b.FIELDLABEL
from collate a,collateitem b
where --upper(a.tablename) like '%'||upper(VTABLENAME)||'%'
--and a.tablelabel like '%'||VTABLELABEL||'%'
a.no=b.collateno
--and upper(b.FIELDNAME) like '%'||upper(VFIELDNAME)||'%'
--and b.FIELDLABEL like '%'||VFIELDLABEL||'%'
and a.no =VCOLLATENO;

COMMIT;
end;
</BEFORERUN>
<AFTERRUN>
</AFTERRUN>
<TABLELIST>
  <TABLEITEM>
    <TABLE>h4rtmp_collate</TABLE>
    <ALIAS>h4rtmp_collate</ALIAS>
    <INDEXNAME></INDEXNAME>
    <INDEXMETHOD></INDEXMETHOD>
  </TABLEITEM>
</TABLELIST>
<JOINLIST>
</JOINLIST>
<COLUMNLIST>
  <FIXEDCOLUMNS>5</FIXEDCOLUMNS>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>upper(h4rtmp_collate.FIELDNAME)</COLUMN>
    <TITLE>字段英文名</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>FIELDNAME</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>h4rtmp_collate.FIELDLABEL</COLUMN>
    <TITLE>字段中文名</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>FIELDLABEL</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>h4rtmp_collate.COLLATENO</COLUMN>
    <TITLE>数据表编号</TITLE>
    <FIELDTYPE>3</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>COLLATENO</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT>##########</CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>upper(h4rtmp_collate.tablename)</COLUMN>
    <TITLE>数据表英文名</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>tablename</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
  <COLUMNITEM>
    <AGGREGATION></AGGREGATION>
    <COLUMN>h4rtmp_collate.tablelabel</COLUMN>
    <TITLE>数据表中文名</TITLE>
    <FIELDTYPE>1</FIELDTYPE>
    <VISIBLE>TRUE</VISIBLE>
    <GAGGREGATION></GAGGREGATION>
    <DISPLAYINNEXT>FALSE</DISPLAYINNEXT>
    <ISKEY>FALSE</ISKEY>
    <COLUMNNAME>tablelabel</COLUMNNAME>
    <CFILTER>FALSE</CFILTER>
    <CFONTCOLOR>0</CFONTCOLOR>
    <CDISFORMAT></CDISFORMAT>
    <CGROUPINDEX>-1</CGROUPINDEX>
  </COLUMNITEM>
</COLUMNLIST>
<COLUMNWIDTH>
  <COLUMNWIDTHITEM>134</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>178</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>81</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>193</COLUMNWIDTHITEM>
  <COLUMNWIDTHITEM>388</COLUMNWIDTHITEM>
</COLUMNWIDTH>
<GROUPLIST>
</GROUPLIST>
<ORDERLIST>
  <ORDERITEM>
    <COLUMN>字段英文名</COLUMN>
    <ORDER>ASC</ORDER>
  </ORDERITEM>
</ORDERLIST>
<CRITERIALIST>
  <WIDTHLIST>
  </WIDTHLIST>
  <CRITERIAITEM>
    <LEFT>h4rtmp_collate.COLLATENO</LEFT>
    <OPERATOR>=</OPERATOR>
    <RIGHT>
      <RIGHTITEM>15002</RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
      <RIGHTITEM></RIGHTITEM>
    </RIGHT>
    <ISHAVING>FALSE</ISHAVING>
    <ISQUOTED>0</ISQUOTED>
    <PICKNAME>
    </PICKNAME>
    <PICKVALUE>
    </PICKVALUE>
    <DEFAULTVALUE></DEFAULTVALUE>
    <ISREQUIRED>FALSE</ISREQUIRED>
    <WIDTH>0</WIDTH>
  </CRITERIAITEM>
</CRITERIALIST>
<CRITERIAWIDTH>
  <CRITERIAWIDTHITEM>123</CRITERIAWIDTHITEM>
</CRITERIAWIDTH>
<SG>
  <LINE>
  </LINE>
  <LINE>
    <SGLINEITEM>条件 1：</SGLINEITEM>
    <SGLINEITEM>15002</SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 2：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 3：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
    <SGLINEITEM>  或 4：</SGLINEITEM>
    <SGLINEITEM></SGLINEITEM>
  </LINE>
  <LINE>
  </LINE>
</SG>
<CHECKLIST>
  <CAPTION>
  </CAPTION>
  <EXPRESSION>
  </EXPRESSION>
  <CHECKED>
  </CHECKED>
  <ANDOR> and </ANDOR>
</CHECKLIST>
<UNIONLIST>
</UNIONLIST>
<NCRITERIAS>
  <NUMOFNEXTQRY>0</NUMOFNEXTQRY>
</NCRITERIAS>
<MULTIQUERIES>
  <NUMOFMULTIQRY>0</NUMOFMULTIQRY>
</MULTIQUERIES>
<FUNCTIONLIST>
</FUNCTIONLIST>
<DXDBGRIDITEM>
  <DXLOADMETHOD>FALSE</DXLOADMETHOD>
  <DXSHOWGROUP>FALSE</DXSHOWGROUP>
  <DXSHOWFOOTER>TRUE</DXSHOWFOOTER>
  <DXSHOWSUMMARY>FALSE</DXSHOWSUMMARY>
  <DXSHOWPREVIEW>FALSE</DXSHOWPREVIEW>
  <DXSHOWFILTER>FALSE</DXSHOWFILTER>
  <DXPREVIEWFIELD></DXPREVIEWFIELD>
  <DXCOLORODDROW>-2147483643</DXCOLORODDROW>
  <DXCOLOREVENROW>12632256</DXCOLOREVENROW>
  <DXFILTERNAME></DXFILTERNAME>
  <DXFILTERLIST>
  </DXFILTERLIST>
  <DXSHOWGRIDLINE>1</DXSHOWGRIDLINE>
</DXDBGRIDITEM>
</SQLQUERY>
<SQLREPORT>
<RPTTITLE></RPTTITLE>
<RPTGROUPCOUNT>0</RPTGROUPCOUNT>
<RPTGROUPLIST>
</RPTGROUPLIST>
<RPTCOLUMNCOUNT>0</RPTCOLUMNCOUNT>
<RPTCOLUMNWIDTHLIST>
</RPTCOLUMNWIDTHLIST>
<RPTLEFTMARGIN>20</RPTLEFTMARGIN>
<RPTORIENTATION>0</RPTORIENTATION>
<RPTCOLUMNS>1</RPTCOLUMNS>
<RPTHEADERLEVEL>0</RPTHEADERLEVEL>
<RPTPRINTCRITERIA>TRUE</RPTPRINTCRITERIA>
<RPTVERSION></RPTVERSION>
<RPTNOTE></RPTNOTE>
<RPTFONTSIZE>10</RPTFONTSIZE>
<RPTLINEHEIGHT>宋体</RPTLINEHEIGHT>
<RPTPAGEHEIGHT>66</RPTPAGEHEIGHT>
<RPTPAGEWIDTH>80</RPTPAGEWIDTH>
<RPTTITLETYPE>0</RPTTITLETYPE>
<RPTCURREPORT></RPTCURREPORT>
<RPTREPORTLIST>
</RPTREPORTLIST>
</SQLREPORT>

